var a;function CalSourceType(){this.data={};this.timer=null}a=CalSourceType.prototype;a.prepareCategory=function(b,c){if(c==null)c=false;if(c||this.data[b]==null){this.data[b]!=null&&this.data[b].current_CalEvents!=null&&send2Calendar("removeEventSource",this.data[b].current_CalEvents);this.data[b]={};this.data[b].status="new";this.data[b].events={}}};
a.needData=function(b,c){if(c==null)c=false;this.prepareCategory(b,c);if(this.data[b].status!="loaded"){this.data[b].status="needData";this.data[b].name=this.getName(b);this.triggerCollectTimer()}};a.getName=function(b){return"Unknown["+b+"]"};a.triggerCollectTimer=function(){var b=this;b.timer!=null&&window.clearTimeout(b.timer);b.timer=window.setTimeout(function(){b.collectData();b.timer=null},100)};
a.hideData=function(b){this.prepareCategory(b);this.data[b].status="hide";this.data[b].current_CalEvents!=null&&send2Calendar("removeEventSource",this.data[b].current_CalEvents)};a.refreshView=function(b){var c=this;if(b!=null){this.hideData(b);this.needData(b,false)}else $.each(c.data,function(g,k){if(k.status=="loaded"){c.hideData(g);c.needData(g,false)}})};a.collectData=function(){var b=[];$.each(this.data,function(c,g){g.status=="needData"&&b.push(c)});b.length>0&&this.jsonCall(b)};
a.jsonCall=function(){throw new Exception("Not implemented!");};Temp.prototype=CalSourceType.prototype;function CalCCType(){CalSourceType.call(this)}CalCCType.prototype=new Temp;var calCCType=new CalCCType;
CalCCType.prototype.jsonCall=function(b){var c=this;churchInterface.jsendRead({func:"getCalPerCategory",category_ids:b},function(g,k){if(g)k!=null&&$.each(k,function(f,d){c.data[f].events=d;$.each(c.data[f].events,function(e,j){j.startdate=j.startdate.toDateEn(true);j.enddate=j.enddate.toDateEn(true);if(j.repeat_until!=null)j.repeat_until=j.repeat_until.toDateEn(false)});if(c.data[f].status!="hide"){c.data[f].status="loaded";d=mapEvents(c.data[f].events,true);c.data[f].current_CalEvents={container:c,
category_id:f,events:d,color:"black",editable:categoryEditable(f)};send2Calendar("addEventSource",c.data[f].current_CalEvents)}});else alert("Fehler: "+status)})};CalCCType.prototype.getName=function(b){return masterData.category[b].bezeichnung};function CalBirthdayType(){CalSourceType.call(this)}CalBirthdayType.prototype=new Temp;var calBirthdayType=new CalBirthdayType;
CalBirthdayType.prototype.jsonCall=function(b){var c=this,g=b[0];churchInterface.jsendRead({func:"getBirthdays"},function(k,f){if(k){var d=new Date,e=[];$.each(f,function(j,h){for(j=-1;j<=1;j++){var i=Object();i.title=h.name;i.allDay=true;var l=h.birthday.toDateEn();l.setYear(d.getFullYear()+j);i.start=l;e.push(i)}});if(c.data[g].status!="hide"){c.data[g].status="loaded";c.data[g].current_CalEvents={container:c,category_id:g,events:e,color:"lightblue",editable:false};send2Calendar("addEventSource",
c.data[g].current_CalEvents)}}else alert("Fehler: "+status)})};CalBirthdayType.prototype.getName=function(){return"Geburtstage (Gruppe)"};function CalAllBirthdayType(){CalSourceType.call(this)}CalAllBirthdayType.prototype=new Temp;var calAllBirthdayType=new CalAllBirthdayType;
CalAllBirthdayType.prototype.jsonCall=function(b){var c=this,g=b[0];churchInterface.jsendRead({func:"getBirthdays",all:true},function(k,f){if(k){var d=new Date,e=[];$.each(f,function(j,h){for(j=-1;j<=1;j++){var i=Object();i.title=h.name;i.allDay=true;var l=h.birthday.toDateEn();l.setYear(d.getFullYear()+j);i.start=l;e.push(i)}});if(c.data[g].status!="hide"){c.data[g].status="loaded";c.data[g].current_CalEvents={container:c,category_id:g,events:e,color:"lightblue",editable:false};send2Calendar("addEventSource",
c.data[g].current_CalEvents)}}else alert("Fehler: "+status)})};CalAllBirthdayType.prototype.getName=function(){return"Geburtstage (Alle)"};function CalResourceType(){CalSourceType.call(this)}CalResourceType.prototype=new Temp;var calResourceType=new CalResourceType;
CalResourceType.prototype.jsonCall=function(b){var c=this;churchInterface.jsendRead({func:"getResource",resource_id:b},function(g,k){g?$.each(k,function(f,d){var e=[];c.data[f].events=d;$.each(c.data[f].events,function(j,h){h.startdate=h.startdate.toDateEn(true);h.enddate=h.enddate.toDateEn(true);if(h.repeat_until!=null)h.repeat_until=h.repeat_until.toDateEn(false);h.enddate.getTime();h.startdate.getTime();$.each(churchcore_getAllDatesWithRepeats(h),function(i,l){i=Object();i.title=h.bezeichnung+
(h.repeat_id>0?"{R}":"")+" ("+masterData.resourcen[h.resource_id].bezeichnung+")";if(h.status_id==1)i.title='<font color="lightgray">'+i.title+"?</font>";else if(h.status_id==3)i.title='<span style="color:lightgray;text-decoration:line-through;">'+i.title+"</span>";i.status=h.status;i.start=l.startdate;i.end=l.enddate;i.allDay=false;e.push(i)})});if(c.data[f].status!="hide"){c.data[f].status="loaded";c.data[f].current_CalEvents={container:c,category_id:f,events:e,color:"green",editable:false};send2Calendar("addEventSource",
c.data[f].current_CalEvents)}}):alert("Fehler: "+status)})};CalResourceType.prototype.getName=function(b){return masterData.resourcen[b].bezeichnung};function CalMyServicesType(){CalSourceType.call(this)}CalMyServicesType.prototype=new Temp;var calMyServicesType=new CalMyServicesType;
CalMyServicesType.prototype.jsonCall=function(b){var c=this;churchInterface.jsendRead({func:"getMyServices"},function(g,k){if(g){var f=[];c.data[b].events=k;$.each(c.data[b].events,function(d,e){d=Object();d.title=e.zugesagt_yn==1?e.dienst+" ("+e.servicegroup+")":"Anfrage: "+e.dienst+" ("+e.servicegroup+")";d.title=d.title+" "+e.event;d.start=e.startdate.toDateEn(true);d.end=e.enddate.toDateEn(true);d.allDay=false;f.push(d)});if(c.data[b].status!="hide"){c.data[b].status="loaded";c.data[b].current_CalEvents=
{container:c,category_id:b,events:f,color:"blue",editable:false};send2Calendar("addEventSource",c.data[b].current_CalEvents)}}else alert("Fehler: "+status)})};CalMyServicesType.prototype.getName=function(){return"Meine Dienste"};function CalAbsentsType(){CalSourceType.call(this)}CalAbsentsType.prototype=new Temp;var calAbsentsType=new CalAbsentsType;
CalAbsentsType.prototype.jsonCall=function(b){var c=this;cals=[];$.each(filter.filterGruppenKalender.selected,function(g,k){k>100&&cals.push(k-100)});cals.length>0&&churchInterface.jsendRead({func:"getAbsents",cal_ids:cals},function(g,k){if(g){var f=[];c.data[b].events=k;$.each(c.data[b].events,function(d,e){d=Object();d.id=e.p_id;d.title=e.vorname+" "+e.name;d.start=e.startdate.toDateEn(true);d.end=e.enddate.toDateEn(true);if(masterData.absent_reason[e.reason_id]!=null){if(masterData.absent_reason[e.reason_id].color!=
"")d.color=masterData.absent_reason[e.reason_id].color;d.bezeichnung=masterData.absent_reason[e.reason_id].bezeichnung}d.allDay=d.start.getHours()==0&&d.end.getHours()==0?true:false;f.push(d)});if(c.data[b].status!="hide"){c.data[b].status="loaded";c.data[b].current_CalEvents={container:c,category_id:b,events:f,color:"lightgreen",editable:false};send2Calendar("addEventSource",c.data[b].current_CalEvents)}}else alert("Fehler: "+status)})};CalAbsentsType.prototype.getName=function(){return"Abwesenheiten "};
