masterData={};allPersons=allEvents=currentEvent=calendar=null;allData={};viewName="calView";filterName="";monthNames=["Januar","Februar","M&auml;rz","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"];filterCategoryIds=null;var filter={},embedded=false,minical=false,max_entries=50;
function mapEvents(a){var c=[];$.each(a,function(b,e){if(filterCategoryIds==null||churchcore_inArray(e.category_id,filterCategoryIds))if(!embedded||e.intern_yn==0)$.each(churchcore_getAllDatesWithRepeats(e),function(f,d){f=Object();f.id=e.id;f.title=e.bezeichnung;if(e.notizen!=null&&e.notizen!="")f.notizen=e.notizen;if(e.link!=null&&e.link!="")f.link=e.link;if(e.ort!=null&&e.ort!="")f.title=f.title+" ("+e.ort+")";f.start=d.startdate;f.end=d.enddate;f.allDay=churchcore_isAllDayDate(f.start,f.end);
if(e.category_id!=null&&masterData.category[e.category_id].color!=null)f.color=masterData.category[e.category_id].color;c.push(f)})});return c}function getEventFromEventSource(a){return a.source.container.data==null||a.source.category_id==0||a.source.container.data[a.source.category_id]==null?null:a.source.container.data[a.source.category_id].events[a.id]}
function _eventDrop(a,c,b,e,f){var d=getEventFromEventSource(a);if(d==null){alert("Fehler oder keine Rechte!");f();return null}d.startdate.addDays(c);d.enddate.addDays(c);d.startdate.setMinutes(d.startdate.getMinutes()+b);d.enddate.setMinutes(d.enddate.getMinutes()+b);b={};b.func="updateEvent";b.startdate=d.startdate;b.enddate=d.enddate;b.id=a.id;b.bookings=d.bookings;b.bezeichnung=d.bezeichnung;b.category_id=d.category_id;if(e){b.startdate=b.startdate.toStringDe(false).toDateDe(false);b.enddate=
b.enddate==null?new Date(b.startdate):b.enddate.toStringDe(false).toDateDe(false)}else if(b.enddate==null){b.enddate=new Date(b.startdate);b.enddate.setMinutes(b.startdate.getMinutes()+90);a.end=b.enddate}d.repeat_id>0&&c!=0&&calCCType.refreshView(d.category_id);churchInterface.jsendWrite(b,function(g,i){if(!g){alert(i);f()}},true,false)}
function _eventResize(a,c,b,e){var f=getEventFromEventSource(a);if(f==null||masterData.auth["edit category"]==null||masterData.auth["edit category"][a.source.category_id]==null){alert("Fehler oder keine Rechte!");e();return null}if(f!=null){f.enddate.addDays(c);f.enddate.setMinutes(f.enddate.getMinutes()+b);churchInterface.jsendWrite({func:"updateEvent",id:a.id,startdate:f.startdate,enddate:f.enddate,bezeichnung:a.title,category_id:f.category_id,bookings:f.bookings},function(d,g){if(!d){alert(g);
e()}},true,false)}}function _select(a,c,b,e,f){b={};b.startdate=a;b.enddate=c;editEvent(b,f.name=="month");calendar.fullCalendar("unselect")}
function _renderViewChurchResource(a){if(masterData.resources==null){churchInterface.jsonRead({func:"getMasterData"},function(f){if(f=="error")alert("Fehler beim Holen der Ressourcen: "+f);else{masterData.resources=f.res;masterData.resourcesTypes=f.resTypes;masterData.status=f.status;if(masterData.resources==null)masterData.resources={};_renderEditEventContent(a,currentEvent)}},"churchresource");a.find("#cal_content").html("Lade Daten...")}else{var c=[];$.each(churchcore_sortMasterData(masterData.resourcesTypes,
"sortkey"),function(f,d){c.push({id:"",bezeichnung:"-- "+d.bezeichnung+" --"});$.each(churchcore_sortMasterData(masterData.resources,"sortkey"),function(g,i){i.resourcetype_id==d.id&&c.push({id:i.id,bezeichnung:i.bezeichnung})})});var b=[];b.push({id:0,bezeichnung:"-"});b.push({id:15,bezeichnung:"15 Minuten"});b.push({id:30,bezeichnung:"30 Minuten"});b.push({id:45,bezeichnung:"45 Minuten"});b.push({id:60,bezeichnung:"1 Stunde"});b.push({id:90,bezeichnung:"1,5 Stunden"});b.push({id:120,bezeichnung:"2 Stunden"});
b.push({id:150,bezeichnung:"2,5 Stunden"});b.push({id:180,bezeichnung:"3 Stunden"});b.push({id:240,bezeichnung:"4 Stunden"});b.push({id:300,bezeichnung:"5 Stunden"});b.push({id:360,bezeichnung:"6 Stunden"});b.push({id:1440,bezeichnung:"1 Tag"});var e=new CC_Form;if(currentEvent.minpre==null){currentEvent.minpre=0;currentEvent.minpost=0}e.addSelect({cssid:"ressource_new",htmlclass:"resource",freeoption:true,label:"Ressource ausw&auml;hlen",data:c,sort:false});e.addSelect({label:"Im Vorfeld buchen",
cssid:"min_pre_new",sort:false,selected:currentEvent.minpre,data:b});e.addSelect({label:"Nachher buchen",cssid:"min_post_new",sort:false,selected:currentEvent.minpost,data:b});e.addButton({cssid:"ressource-add",controlgroup:true,htmlclass:"add",label:"Ressource hinzuf&uuml;gen"});if(currentEvent.bookings!=null){e.addHtml("<legend>Vorhandene Buchungen</legend>");e.addHtml('<div class="w_ell"><table class="table table-condensed"><tr><th>Ressource<th>Vorher<th>Nachher<th>Status<th>');$.each(currentEvent.bookings,
function(f,d){e.addHtml("<tr><td>");e.addHtml(masterData.resources[d.resource_id].bezeichnung);e.addHtml("<td>");e.addSelect({type:"small",cssid:"min-pre-"+d.resource_id,controlgroup:false,sort:false,selected:d.minpre,data:b});e.addHtml("<td>");e.addSelect({type:"small",cssid:"min-post-"+d.resource_id,controlgroup:false,sort:false,selected:d.minpost,data:b});e.addHtml("<td>");d.status_id!=null&&e.addHtml("<i>"+masterData.status[d.status_id].bezeichnung+"</i>");e.addHtml("<td>");d.status_id!=99&&e.addImage({src:"trashbox.png",
cssid:"trash",width:20,data:[{name:"id",value:d.resource_id}]})});e.addHtml("</table></div>")}a.find("#cal_content").html(e.render(null,"horizontal"));a.find("#ressource-add").click(function(){if(a.find("select.resource").val()>0){if(currentEvent.bookings==null)currentEvent.bookings={};currentEvent.minpre=a.find("#min_pre_new").val();currentEvent.minpost=a.find("#min_post_new").val();currentEvent.bookings[a.find("select.resource").val()]={resource_id:a.find("select.resource").val(),minpre:currentEvent.minpre,
minpost:currentEvent.minpost,status_id:1};_renderEditEventContent(a,currentEvent)}});a.find("select").change(function(){if($(this).attr("id").indexOf("min-pre-")==0){currentEvent.bookings[$(this).attr("id").substr(8,99)].minpre=$(this).val();_renderEditEventContent(a,currentEvent)}else if($(this).attr("id").indexOf("min-post-")==0){currentEvent.bookings[$(this).attr("id").substr(9,99)].minpost=$(this).val();_renderEditEventContent(a,currentEvent)}});a.find("#trash").click(function(){currentEvent.bookings[$(this).attr("data-id")].status_id=
99;_renderEditEventContent(a,currentEvent);return false})}}function currentEvent_addException(a){if(currentEvent.exceptions==null)currentEvent.exceptions={};if(currentEvent.exceptionids==null)currentEvent.exceptionids=0;currentEvent.exceptionids-=1;currentEvent.exceptions[currentEvent.exceptionids]={id:currentEvent.exceptionids,except_date_start:a.toStringEn(),except_date_end:a.toStringEn()}}
function _renderEditEventContent(a,c){var b=[];if(c.view=="view-main"){b.push('<form class="form-horizontal">');b.push(form_renderInput({value:c.bezeichnung,cssid:"inputBezeichnung",label:"Bezeichnung"}));b.push(form_renderInput({value:c.ort,cssid:"inputOrt",label:"Ort",placeholder:""}));if(masterData.category[c.category_id]!=null&&masterData.category[c.category_id].oeffentlich_yn==1)b.push(form_renderCheckbox({label:" Termin nur intern sichtbar",controlgroup:true,controlgroup_class:"",cssid:"inputIntern",
checked:c.intern_yn!=null&&c.intern_yn==1?true:false}));b.push('<div id="dates"></div>');b.push('<div id="wiederholungen"></div>');var e=[],f=[];f.push({id:-1,bezeichnung:"-- Pers&ouml;nliche Kalender --"});$.each(churchcore_sortMasterData(masterData.category),function(d,g){g.privat_yn==1&&categoryEditable(g.id)&&f.push(g)});if(f.length>1)e=e.concat(f);f=[];f.push({id:-1,bezeichnung:"-- Gruppenkalender --"});$.each(churchcore_sortMasterData(masterData.category),function(d,g){g.oeffentlich_yn==0&&
g.privat_yn==0&&categoryEditable(g.id)&&f.push(g)});if(f.length>1)e=e.concat(f);f=[];f.push({id:-1,bezeichnung:"-- Gemeindekalender --"});$.each(churchcore_sortMasterData(masterData.category),function(d,g){g.oeffentlich_yn==1&&categoryEditable(g.id)&&f.push(g)});if(f.length>1)e=e.concat(f);b.push(form_renderSelect({data:e,sort:false,cssid:"inputCategory",selected:c.category_id,label:"Kalender"}));b.push(form_renderTextarea({data:c.notizen,label:"Weitere Infos",cssid:"inputNote",rows:2,cols:100}));
b.push(form_renderInput({value:c.link,label:"Link",cssid:"inputLink"}));b.push("</form>");c.id!=null&&b.push('<p align="right"><small>#'+c.id+"</small>");a.find("#cal_content").html(b.join(""));form_renderDates({elem:$("#dates"),data:c,deleteException:function(d){delete c.exceptions[d.id]},addException:function(d,g){currentEvent_addException(g.toDateDe());return c},deleteAddition:function(d){delete c.additions[d.id]},addAddition:function(d,g,i){if(c.additions==null)c.additions={};if(c.exceptionids==
null)c.exceptionids=0;c.exceptionids-=1;c.additions[c.exceptionids]={id:c.exceptionids,add_date:g.toDateDe().toStringEn(),with_repeat_yn:i};return c}});$("#inputBezeichnung").focus();a.find("#inputCategory").change(function(){churchInterface.jsonWrite({func:"saveSetting",sub:"category_id",val:$(this).val()});masterData.settings.category_id=$(this).val();c.category_id=$(this).val();_renderEditEventNavi(a,c)})}else if(c.view=="view-invite"){b.push("<legend>Besprechungsanfrage an alle Kalenderteilnehmer</legend>");
a.find("#cal_content").html(b.join(""))}else if(c.view=="view-churchresource")_renderViewChurchResource(a);else if(c.view=="view-churchservice")if(masterData.eventTemplate==null)churchInterface.jsendRead({func:"getEventTemplates"},function(d,g){if(d){masterData.eventTemplate=g;if(masterData.eventTemplate==null)masterData.eventTemplate={};_renderEditEventContent(a,c)}else alert("Fehler beim Holen der Templates: "+g)},null,null,"churchservice");else{if(c.event_id==null){e=new CC_Form;e.addCaption({text:"<p>Hier kann direkt f&uuml;r <i>"+
masterData.churchservice_name+"</i> ein Event angelegt werden. Bitte dazu eine Vorlage ausw&auml;hlen."});e.addSelect({cssid:"eventTemplate",freeoption:true,selected:c.eventTemplate,label:"Event-Vorlage ausw&auml;hlen",data:masterData.eventTemplate});b.push(e.render(null,"horizontal"))}else if(c.copyevent){e=new CC_Form;e.addCheckbox({label:"Alle zugeh&ouml;rigen Event-Daten aus "+masterData.churchservice_name+" mit kopieren",checked:c.copychurchservice,cssid:"copychurchservice"});e.addSelect({cssid:"eventTemplate",
freeoption:true,selected:c.eventTemplate,label:"Eine Event-Vorlage w&auml;hlen",data:masterData.eventTemplate});b.push(e.render(null,"horizontal"))}else b.push("Der Eintrag ist mit <i>"+masterData.churchservice_name+'</i> verbunden. <br><br><a class="btn" href="?q=churchservice&id='+c.event_id+'">Event aufrufen</a>');a.find("#cal_content").html(b.join(""));a.find("#copychurchservice").change(function(){c.copychurchservice=$(this).attr("checked")=="checked";if(c.copychurchservice){a.find("#eventTemplate").val("");
c.eventTemplate=null}});a.find("#eventTemplate").change(function(){a.find("#copychurchservice").removeAttr("checked");c.copychurchservice=null;if(c.repeat_id!=0&&$(this).val()!=""){alert("Leider geht das nicht bei Wiederholungsterminen! Hierzu bitte die Kopier-Funktion verwenden.");a.find("#eventTemplate").val("")}else c.eventTemplate=$(this).val()})}}
function _renderEditEventNavi(a,c){var b=new CC_Navi;b.addEntry(c.view=="view-main","view-main","Kalender");masterData.category[c.category_id].privat_yn==0&&masterData.auth["view churchservice"]&&b.addEntry(c.view=="view-churchservice","view-churchservice",masterData.churchservice_name);masterData.auth["view churchresource"]&&b.addEntry(c.view=="view-churchresource","view-churchresource",masterData.churchresource_name);b.renderDiv("cal_menu",churchcore_handyformat());a.find("ul.nav a").click(function(){c.view==
"view-main"&&getCalEditFields(c);c.view=$(this).attr("id");_renderEditEventNavi(a,c);_renderEditEventContent(a,c)})}function getCalEditFields(a){form_getDatesInToObject(a);a.bezeichnung=$("#inputBezeichnung").val();a.ort=$("#inputOrt").val();a.intern_yn=$("#inputIntern").attr("checked")=="checked"?1:0;a.notizen=$("#inputNote").val();a.link=$("#inputLink").val();a.category_id=$("#inputCategory").val()}
function saveEvent(){var a=currentEvent,c=a.category_id;currentEvent.view=="view-main"&&getCalEditFields(a);if(currentEvent.repeat_id>0&&currentEvent.eventTemplate!=null&&currentEvent.eventTemplate!=""){alert("So lange ein Termin von "+masterData.churchservice_name+" verbunden ist, kann daraus kein Wiederholungstermin erstellt werden.");return false}else if(currentEvent.repeat_id>0&&currentEvent.event_id!=null){alert("Der Termin ist bereits mit "+masterData.churchservice_name+" verbunden. Es kann leider kein Wiederholungstermin erstellt werden.");
return false}if(currentEvent.id!=null){a.func="updateEvent";a.currentEvent_id=currentEvent.id}else a.func="createEvent";churchInterface.jsendWrite(a,function(b,e){if(b){c!=a.category_id&&c!=null&&calCCType.needData(c,true);calCCType.needData(a.category_id,true);a.bookings!=null&&calResourceType.refreshView()}else alert("Fehler beim Anpassen des Events: "+e)},false,false);return true}
function editEvent(a,c,b){currentEvent=jQuery.extend({},a);currentEvent.view="view-main";c&&currentEvent.allDay==null&&currentEvent.startdate.getHours()==0&&currentEvent.startdate.getDate()==currentEvent.enddate.getDate()&&currentEvent.startdate.setHours(10);if(currentEvent.enddate==null){currentEvent.enddate=new Date(currentEvent.startdate);currentEvent.startdate.getHours()>0&&currentEvent.enddate.setHours(currentEvent.startdate.getHours()+1)}if(currentEvent.bezeichnung==null)currentEvent.bezeichnung=
"";if(currentEvent.category_id==null)currentEvent.category_id=masterData.settings.category_id;if(!categoryEditable(currentEvent.category_id)){$.each(masterData.category,function(f){if(categoryEditable(f)){currentEvent.category_id=f;return false}});if(currentEvent.category_id==null){if(masterData["edit category"]!=null){alert("Um einen Termin anzulegen, muss erst ein Kalender erstellt werden!");editCategory(null,0)}return null}}a=[];a.push('<div id="cal_menu"><br/></div>');a.push('<div id="cal_content"></div>');
var e=form_showDialog(currentEvent.id==null?"Neuen Termin erstellen":"Termin editieren",a.join(""),560,600,{"Termin speichern":function(){saveEvent()&&$(this).dialog("close")}});_renderEditEventContent(e,currentEvent);if(currentEvent.id!=null)b!=null&&currentEvent.startdate.toStringDe()!=b.toStringDe()?e.dialog("addbutton","Nur aktuellen Termin entfernen",function(){if(confirm("Termin wirklich entfernen?")){var f=false;if(currentEvent.additions!=null){$.each(currentEvent.additions,function(d,g){if(g.add_date.toDateEn().toStringDe(false)==
b.toStringDe(false)){f=true;delete currentEvent.additions[d];churchInterface.jsendWrite({func:"delAddition",id:d});return false}});calCCType.refreshView(currentEvent.category_id)}if(!f){currentEvent_addException(b);saveEvent()}e.dialog("close")}}):e.dialog("addbutton",l("L\u00f6schen"),function(){delEvent(currentEvent,function(){e.dialog("close")})});e.dialog("addbutton","Abbrechen",function(){$(this).dialog("close")});_renderEditEventNavi(e,currentEvent)}
function copyEvent(a){a=$.extend({},a);a.orig_id=a.id;a.id=null;a.copyevent=true;a.copychurchservice=false;editEvent(a,"week")}function delEvent(a,c){if(a.event_id!=null)alert("Es sind in "+masterData.churchservice_name+" noch ein Event vorhanden bitte erst das l\u00f6schen!");else if(confirm("Termin wirklich entfernen?")){calCCType.hideData(a.category_id);churchInterface.jsendWrite({func:"deleteEvent",id:a.id},function(){calCCType.needData(a.category_id,true);c!=null&&c()})}}
function _viewChanged(a){if(masterData.settings.viewName==null||masterData.settings.viewName!=a.name)churchInterface.jsonWrite({func:"saveSetting",sub:"viewName",val:a.name})}function categoryEditable(a){if(a==null)return false;if(masterData.auth["edit category"]!=null&&masterData.auth["edit category"][a]!=null)return true;return false}
function _eventClick(a,c,b){clearTooltip(true);c=[];c.push("<legend>"+a.title+"</legend>");c.push("<p>Startdatum: "+a.start.toStringDe(!a.allDay));a.end!=null&&c.push("<p>Enddatum: "+a.end.toStringDe(!a.allDay));var e=getEventFromEventSource(a);e!=null&&categoryEditable(e.category_id)?editEvent(e,b.name=="month",a.start):form_showOkDialog("Termin: "+a.title,c.join(""),400,400)}var tooltip_elem=null,tooltip_hold=false,tooltip_inhide=false;
function initCalendarView(){calendar=$("#calendar");if(viewName=="calView"){calendar.fullCalendar({header:{left:"prev,next today",center:"title",right:"agendaDay,agendaWeek,month"},firstDay:1,contentHeight:600,defaultEventMinutes:90,editable:true,monthNames:monthNames,weekNumbers:true,weekNumberTitle:"KW",monthNamesShort:["Jan.","Feb.","Mar.","Apr.","Mai.","Jun.","Jul.","Aug.","Sep.","Okt.","Nov.","Dez."],dayNames:dayNames,dayNamesShort:["So","Mo","Di","Mi","Do","Fr","Sa"],buttonText:{prev:"&nbsp;&#9668;&nbsp;",
next:"&nbsp;&#9658;&nbsp;",prevYear:"&nbsp;&lt;&lt;&nbsp;",nextYear:"&nbsp;&gt;&gt;&nbsp;",today:"Heute",month:"Monat",week:"Woche",day:"Tag"},timeFormat:{agenda:"H:mm{-H:mm}","":"H(:mm)'h'"},allDayText:"Ganzt&auml;gig",firstHour:10,defaultView:masterData.settings!=null&&masterData.settings.viewName!=null?masterData.settings.viewName:"month",axisFormat:"H:mm",columnFormat:{month:"ddd",week:"ddd d.M.",day:"dddd d.M."},eventDragStart:function(){clearTooltip(true)},eventResizeStart:function(){clearTooltip(true)},
eventDrop:_eventDrop,eventResize:_eventResize,viewDisplay:_viewChanged,eventClick:_eventClick,eventMouseover:_eventMouseover,eventMouseout:function(){clearTooltip()},eventRender:function(c,b){b.find("div.fc-event-title").html(b.find("div.fc-event-title").text());b.find("span.fc-event-title").html(b.find("span.fc-event-title").text())},selectable:true,selectHelper:true,select:_select});if(!embedded){$("td.fc-header-right").append('<span id="yearView" class="fc-button fc-state-default fc-corner-right"><span class="fc-button-inner"><span class="fc-button-content">Jahr</span><span class="fc-button-effect"><span></span></span></span></span>');
$("td.fc-header-right").append('<span id="eventView" class="fc-button fc-state-default fc-corner-right"><span class="fc-button-inner"><span class="fc-button-content"><i class="icon-list"></i></span><span class="fc-button-effect"><span></span></span></span></span>')}$("#header").html("");if($("#viewdate").val()!=null){var a=$("#viewdate").val().toDateEn();calendar.fullCalendar("gotoDate",a.getFullYear(),a.getMonth(),a.getDate())}}else if(viewName=="yearView"){calendar.yearCalendar({});$("#header").append('<span id="calView" class="fc-button fc-state-default fc-corner-right"><span class="fc-button-inner"><span class="fc-button-content">Kalender</span><span class="fc-button-effect"><span></span></span></span></span>');
$("#header").append('<span id="yearView" class="fc-button fc-state-default fc-corner-right"><span class="fc-button-inner"><span class="fc-button-content">Jahr</span><span class="fc-button-effect"><span></span></span></span></span>');$("#header").append('<span id="eventView" class="fc-button fc-state-default fc-corner-right"><span class="fc-button-inner"><span class="fc-button-content"><i class="icon-list"></i></span><span class="fc-button-effect"><span></span></span></span></span>')}else if(viewName==
"eventView"){calendar.eventCalendar({});$("#header").append(form_renderInput({controlgroup:false,cssid:"searchEntry",placeholder:"Suche",htmlclass:"input-medium search-query"}));$("#header").append('<span id="calView" class="fc-button fc-state-default fc-corner-right"><span class="fc-button-inner"><span class="fc-button-content">Kalender</span><span class="fc-button-effect"><span></span></span></span></span>');$("#header").append('<span id="yearView" class="fc-button fc-state-default fc-corner-right"><span class="fc-button-inner"><span class="fc-button-content">Jahr</span><span class="fc-button-effect"><span></span></span></span></span>');
$("#header").append('<span id="eventView" class="fc-button fc-state-default fc-corner-right"><span class="fc-button-inner"><span class="fc-button-content"><i class="icon-list"></i></span><span class="fc-button-effect"><span></span></span></span></span>')}else alert("Unbekannter viewname!");$("#calView").click(function(){window.location.href="?q=churchcal&viewname=calView"});$("#yearView").click(function(){window.location.href="?q=churchcal&viewname=yearView"});$("#eventView").click(function(){window.location.href=
"?q=churchcal&viewname=eventView"});$("#searchEntry").keyup(function(){filterName=$(this).val();send2Calendar("render")});$("#searchEntry").focus()}function send2Calendar(a,c){if(viewName=="calView")calendar.fullCalendar(a,c);else if(viewName=="yearView")calendar.yearCalendar(a,c);else viewName=="eventView"?calendar.eventCalendar(a,c):alert("Unbeaknnter send Calendar")}
function _eventMouseover(a,c){if(!tooltip_hold){tooltip_elem!=null&&clearTooltip(true);tooltip_elem=$(this);var b=[],e=a.title;b.push('<div id="tooltip_inner" class="CalView">');b.push("<ul><li>");if(a.end==null)b.push(a.start.toStringDe(!a.allDay));else if(a.end.toStringDe(false)!=a.start.toStringDe(false))b.push(a.start.toStringDe(!a.allDay)+" - "+a.end.toStringDe(!a.allDay));else{var f=(""+a.end.getMinutes()).length==1?"0"+a.end.getMinutes():a.end.getMinutes();b.push(a.start.toStringDe(!a.allDay)+
" - "+a.end.getHours()+":"+f)}var d=getEventFromEventSource(a);if(d!=null){d.allDay=a.allDay;e=d.bezeichnung;if(d.intern_yn==1)e+=" (intern)";if(categoryEditable(d.category_id)){e=e+'<span class="pull-right">&nbsp;<nobr>'+form_renderImage({cssid:"copyevent",label:l("Kopieren"),src:"copy.png",width:20});e=e+"&nbsp;"+form_renderImage({cssid:"delevent",label:l("L\u00f6schen"),src:"trashbox.png",width:20})+"</nobr></span>"}d.ort!=null&&d.ort!=""&&b.push("<li>Ort: "+d.ort);d.category_id!=null&&b.push("<li>Kategorie: <i>"+
masterData.category[d.category_id].bezeichnung+"</i>");d.notizen!=null&&d.notizen!=""&&b.push("<li>Notizen: <small> "+d.notizen.trim(60)+"</small>");d.link!=null&&d.link!=""&&b.push('<li>Link: <small> <a href="'+d.link+'" target="_clean">'+d.link+"</a></small>")}a.status!=null&&b.push("<li>Status: "+a.status);b.push("</ul>");if(d!=null){d.booking_id!=null&&b.push('<a href="?q=churchresource&id='+d.booking_id+'"><span class="label label-info">'+masterData.churchresource_name+"</label></a>&nbsp;");
d.event_id!=null&&b.push('<a href="?q=churchservice&id='+d.event_id+'"><span class="label label-info">'+masterData.churchservice_name+"</label></a>&nbsp;")}else{if(a.bezeichnung!=null)e=e+" ("+a.bezeichnung+")";b.push("<small><i>Termin von ");b.push(a.source.container.data[a.source.category_id].name);b.push("</i></small>")}b.push("</div>");a="bottom";if(c.pageX>$("#calendar").width()+$("#calendar").position().left-100)a="left";else if(c.pageY>$("#calendar").height()+$("#calendar").position().top-
200)a="top";else if(c.pageX<$("#calendar").position().left+130)a="right";tooltip_elem.popover({title:e,trigger:"manual",html:true,content:b.join(""),placement:a}).popover("show");$("#copyevent").click(function(){clearTooltip(true);copyEvent(d);return false});$("#editevent").click(function(){clearTooltip(true);editEvent(d);return false});$("#delevent").click(function(){clearTooltip(true);delEvent(d);return false});tooltip_indraw=true;$(".popover").hover(function(){tooltip_hold=true},function(){tooltip_hold=
false;clearTooltip()})}}function clearTooltip(a){if(tooltip_elem!=null){tooltip_indraw=false;if(a==null)a=false;if(a)tooltip_hold=false;if(a){tooltip_elem.popover("hide");tooltip_elem.data("popover",null);tooltip_elem=null}else window.setTimeout(function(){if(!tooltip_hold&&!tooltip_indraw&&tooltip_elem!=null){tooltip_elem.popover("hide");tooltip_elem.data("popover",null);tooltip_elem=null}},200)}}
function createMultiselect(a,c){filter[a]=new CC_MultiSelect(c,function(e,f){masterData.settings[a]=this.getSelectedAsArrayString();churchInterface.jsonWrite({func:"saveSetting",sub:a,val:masterData.settings[a]});if(e=="allSelected")filter[a]!=null&&$.each(filter[a].data,function(d){churchcore_inArray(d,filter[a].selected)?needData(a,d):hideData(a,d)});else f?needData(a,e):hideData(a,e)});if(a=="filterGemeindekalendar"){if($("#filtercategory_select").val()!=null){var b=[];$.each($("#filtercategory_select").val().split(","),
function(e,f){b.push(f*1+100)});masterData.settings[a]="["+b.join(",")+"]"}masterData.settings[a]==null?filter[a].selectAll():filter[a].setSelectedAsArrayString(masterData.settings[a])}else filter[a].setSelectedAsArrayString(masterData.settings[a])}function filterMultiselect(a,c){filter[a]!=null&&filter[a].render2Div(a,{label:c,controlgroup:!embedded})}
function _loadAllowedGroups(a){var c=form_showCancelDialog("Lade Daten...","");churchInterface.jsendRead({func:"getAllowedGroups"},function(b,e){c.dialog("close");if(b){masterData.groups=e;a()}else{alert("Fehler beim Holen der Gruppen: "+e);masterData.groups=[]}if(masterData.groups==null)masterData.groups=[]})}
function _loadAllowedPersons(a){var c=form_showCancelDialog("Lade Daten...","");churchInterface.jsendRead({func:"getAllowedPersons"},function(b,e){c.dialog("close");if(b){allPersons={};e!=null&&$.each(e,function(f,d){allPersons[d.p_id]={};allPersons[d.p_id].bezeichnung=d.name+", "+d.vorname;if(d.spitzname!="")allPersons[d.p_id].bezeichnung=allPersons[d.p_id].bezeichnung+" ("+d.spitzname+")";allPersons[d.p_id].id=d.p_id});a()}else{alert("Fehler beim Holen der Personen: "+e);allPersons=[]}})}
function editCategory(a,c,b){var e=$.extend({},masterData.category[a]);if(e.sortkey==null)e.sortkey=0;var f=new CC_Form("Kalender editieren",e);if(a==null&&c==0&&b==0){if(masterData.groups==null){_loadAllowedGroups(function(){editCategory(a,c,b)});return false}f.addSelect({label:"f&uuml;r Gruppe",freeoption:true,cssid:"accessgroup",data:masterData.groups});f.addCaption({text:"<p><small>Hier kann eine Gruppen angegeben werden, die automatisch die Berechtigung erh&auml;lt den Kalender zu sehen</small></p>"});
f.addCheckbox({label:"Gruppenteilnehmer erhalten Schreibrechte",cssid:"writeaccess",checked:false})}f.addInput({label:"Bezeichnung",cssid:"bezeichnung",required:true});f.addHtml('<span class="color"></span>');f.addInput({label:"Sortierungsnummer",cssid:"sortkey"});f.addHtml('<p><p><p class="pull-right"><small>#'+a);var d=form_showDialog(a==null?"Kalender erstellen":"Kalender bearbeiten",f.render(false,"horizontal"),500,500,{Speichern:function(){var g=f.getAllValsAsObject();g.color=e.color;if(g.color==
null)g.color="black";g.privat_yn=c;g.oeffentlich_yn=b;if(b==1)g.privat_yn=0;g.func="saveCategory";g.id=a;d.html("<legend>Speichere Daten...</legend>");churchInterface.jsendWrite(g,function(i,h){if(i){g.id=h;g.modified_pid=a==null?masterData.user_pid:masterData.category[h].modified_pid;masterData.category[h]=g;d.dialog("close");editCategories(c,b,true)}else alert("Es ist ein Fehler aufgetreten:"+h)})},Abbruch:function(){d.dialog("close");editCategories(c,b)}});form_renderColorPicker({label:"Farbe",
value:e.color,elem:d.find("span.color"),func:function(){e.color=$(this).val()}});d.find("#accessgroup").change(function(){$(this).val()!=""&&d.find("#bezeichnung").val(masterData.groups[$(this).val()].bezeichnung)})}
function shareCategory(a,c,b){if(masterData.groups==null){_loadAllowedGroups(function(){shareCategory(a,c,b)});return false}if(allPersons==null){_loadAllowedPersons(function(){shareCategory(a,c,b)});return false}var e=form_showCancelDialog("Lade Daten...","");churchInterface.jsendRead({func:"getShares",cat_id:a},function(f,d){e.dialog("close");if(f){current=$.extend({},masterData.category[a]);if(current.sortkey==null)current.sortkey=0;if(d.person!=null){if(d.person[403]!=null)current.personRead=d.person[403].splice(",");
if(d.person[404]!=null)current.personWrite=d.person[404].splice(",")}if(d.gruppe!=null){if(d.gruppe[403]!=null)current.gruppeRead=d.gruppe[403].splice(",");if(d.gruppe[404]!=null)current.gruppeWrite=d.gruppe[404].splice(",")}var g=new CC_Form(null,current);g.addHtml("<legend>Kalender f&uuml;r Personen freigeben</legend>");g.addHtml('<div class="control-group"><label class="control-label">Lesezugriff</label>');g.addHtml('<div class="controls" id="personRead">');g.addHtml("</div></div>");g.addHtml('<div class="control-group"><label class="control-label">Schreibzugriff</label>');
g.addHtml('<div class="controls" id="personWrite">');g.addHtml("</div></div>");g.addHtml("<legend>Kalender f&uuml;r Gruppen freigeben</legend>");g.addHtml('<div class="control-group"><label class="control-label">Lesezugriff</label>');g.addHtml('<div class="controls" id="gruppeRead">');g.addHtml("</div></div>");g.addHtml('<div class="control-group"><label class="control-label">Schreibzugriff</label>');g.addHtml('<div class="controls" id="gruppeWrite">');var i=form_showDialog("Kalender freigeben",g.render(false,
"horizontal"),500,500,{Speichern:function(){var h=g.getAllValsAsObject();h.person={};h.person[403]=current.personRead;h.person[404]=current.personWrite;h.gruppe={};h.gruppe[403]=current.gruppeRead;h.gruppe[404]=current.gruppeWrite;h.cat_id=a;i.html("<legend>Speichere Daten...</legend>");h.func="saveShares";churchInterface.jsendWrite(h,function(j,k){if(j){i.dialog("close");editCategories(c,b)}else alert("Es ist ein Fehler aufgetreten:"+k)})},Abbruch:function(){i.dialog("close");editCategories(c,b)}});
form_renderLabelList(current,"personRead",allPersons);form_renderLabelList(current,"personWrite",allPersons);form_renderLabelList(current,"gruppeRead",masterData.groups);form_renderLabelList(current,"gruppeWrite",masterData.groups)}else alert("Fehler: "+d)})}
function editCategories(a,c,b){var e=[];if(b==null)b=false;if(a==1)e.push("<legend>Pers&ouml;nliche Kalender verwalten</legend>");else c==0?e.push("<legend>Gruppenkalender</legend>"):e.push("<legend>Gemeindekalender verwalten</legend>");e.push('<table class="table table-condensed">');e.push('<tr><th width="20px"><th>Bezeichnung<th width="40px">');e.push('<th width="25px">');e.push('<th width="25px"><th width="25px">');$.each(churchcore_sortData(masterData.category,"privat_yn",true,null,"sortkey"),
function(d,g){if(g.oeffentlich_yn==c&&g.privat_yn==a){e.push("<tr><td>"+form_renderColor(g.color));e.push("<td>"+g.bezeichnung);e.push('<td><a href="#" id="ical" data-id="'+g.id+'"><span class="label">iCal</span></a>');if(categoryEditable(g.id)){e.push("<td>"+form_renderImage({src:"persons.png",width:20,cssid:"share",data:[{name:"id",value:g.id}]}));e.push("<td>"+form_renderImage({src:"options.png",width:20,cssid:"options",data:[{name:"id",value:g.id}]}));e.push("<td>"+form_renderImage({src:"trashbox.png",
width:20,cssid:"delete",data:[{name:"id",value:g.id}]}))}else e.push("<td><td><td>")}});if(a==1&&masterData.auth["personal category"]||a==0&&c==0&&masterData.auth["group category"]||a==0&&c==1&&masterData.auth["church category"])e.push('<tr><td><td><a href="#" id="options"><i>Neuen Kalender erstellen</i></a><td><td><td>'+form_renderImage({cssid:"options",src:"plus.png",width:20})+"<td>");e.push("</table>");var f=form_showDialog("Kalender verwalten",e.join(""),500,500,{Schliessen:function(){f.dialog("close");
b&&window.location.reload()}});f.find("#options").click(function(){f.dialog("close");editCategory($(this).attr("data-id"),a,c);return false});f.find("#share").click(function(){f.dialog("close");shareCategory($(this).attr("data-id"),a,c);return false});f.find("#ical").click(function(){var d=[];d.push("<legend>Kalender abonnieren</legend>Der Kalender kann abonniert werden. Hierzu kann die Adresse anbei in einen beliebigen Kalender importiert werden, der iCal unterst&uuml;tzt.<br><br>");var g=$(this).attr("data-id");
d.push(form_renderInput({label:"iCal-URL",value:masterData.base_url+"?q=churchcal/ical&security="+masterData.category[g].randomurl+"&id="+g,disable:true}));form_showOkDialog("Kalender abonnieren",d.join(""));return false});f.find("#delete").click(function(){var d=$(this).attr("data-id"),g=0;$.each(masterData.category,function(i,h){if(h.id!=d&&h.privat_yn==1)g+=1});if(g==0){alert("Ein privater Kalender muss bestehen bleiben!");return false}confirm("Wirklich den Kalender "+masterData.category[d].bezeichnung+
" und alle seine Daten entfernen?")&&churchInterface.jsendWrite({func:"deleteCategory",id:d},function(i,h){if(i){calCCType.hideData(d);delete masterData.category[d];f.dialog("close");editCategories(a,c,true)}else alert("Es ist ein Fehler aufgetreten: "+h)})})}
function needData(a,c){if(a=="filterRessourcen")calResourceType.needData(c);else if(c>=100){calCCType.needData(c-100);filter.filterGruppenKalender!=null&&churchcore_inArray(5,filter.filterGruppenKalender.selected)&&calAbsentsType.needData(0)}else if(c==1)calMyServicesType.needData(0);else if(c==4)calBirthdayType.needData(0);else if(c==5)calAbsentsType.needData(0);else c==6&&calAllBirthdayType.needData(0)}
function hideData(a,c){if(a=="filterRessourcen")calResourceType.hideData(c);else if(c>=100){calCCType.hideData(c-100);if(filter.filterGruppenKalender!=null&&churchcore_inArray(5,filter.filterGruppenKalender.selected)){calAbsentsType.hideData(0);calAbsentsType.needData(0)}}else if(c==1)calMyServicesType.hideData(0);else if(c==4)calBirthdayType.hideData(0);else if(c==5)calAbsentsType.hideData(0);else c==6&&calAllBirthdayType.hideData(0)}
function renderPersonalCategories(){var a=[],c=new CC_Form("Pers&ouml;nliche Kalender"+form_renderImage({cssid:"edit_personal",src:"options.png",top:8,width:24,htmlclass:"pull-right"}));c.setHelp("ChurchCal-Filter");var b=-1,e={};churchcore_countObjectElements(masterData.category)>0&&$.each(churchcore_sortMasterData(masterData.category),function(f,d){if(d.modified_pid==masterData.user_pid&&d.privat_yn==1&&d.oeffentlich_yn==0){form_addEntryToSelectArray(e,d.id*1+100,d.bezeichnung,b);b++}});if(masterData.auth["view churchservice"]){form_addEntryToSelectArray(e,
1,"Meine Dienste",b);b++}if(b>-1){form_addEntryToSelectArray(e,2,"-",b);b++}viewName!="yearView"&&churchcore_countObjectElements(masterData.category)>0&&$.each(churchcore_sortMasterData(masterData.category),function(f,d){if(d.modified_pid!=masterData.user_pid&&d.oeffentlich_yn==0&&d.privat_yn==1){form_addEntryToSelectArray(e,d.id*1+100,d.bezeichnung,b);b++}});if(b>=0){createMultiselect("filterMeineKalender",e);c.addHtml('<div id="filterMeineKalender"></div>');a.push(c.render(true))}return a.join("")}
function renderGroupCategories(){form=new CC_Form("Gruppenkalender"+form_renderImage({cssid:"edit_group",src:"options.png",top:8,width:24,htmlclass:"pull-right"}));var a=-1,c={},b=[];if(masterData.auth["group category"]||churchcore_countObjectElements(masterData.category)>0){$.each(churchcore_sortMasterData(masterData.category),function(e,f){if(f.oeffentlich_yn==0&&f.privat_yn==0){e=f.bezeichnung;categoryEditable(f.id)||(e+=" (nur lesbar)");form_addEntryToSelectArray(c,f.id*1+100,e,a);a++}});if(a>=
0){form_addEntryToSelectArray(c,3,"-",a);a++;form_addEntryToSelectArray(c,5,"Abwesenheiten pro Kalender",a);a++;createMultiselect("filterGruppenKalender",c);form.addHtml('<div id="filterGruppenKalender"></div>');b.push(form.render(true))}else if(masterData.auth["group category"]){form.addHtml("<i>Kein Kalender vorhanden</i>");b.push(form.render(true))}}return b.join("")}
function renderChurchCategories(){var a=[];if(viewName!="yearView"){var c=0,b=new CC_Form;if(!embedded){b=new CC_Form("Gemeindekalender"+form_renderImage({cssid:"edit_church",src:"options.png",top:8,width:24,htmlclass:"pull-right"}));b.setHelp("ChurchCal-Filter")}oeff_cals={};churchcore_countObjectElements(masterData.category)>0&&$.each(churchcore_sortMasterData(masterData.category),function(f,d){if(d.oeffentlich_yn==1&&(filterCategoryIds==null||churchcore_inArray(d.id,filterCategoryIds))){form_addEntryToSelectArray(oeff_cals,
d.id*1+100,d.bezeichnung,c);c++}});if(masterData.auth["view churchdb"]){if(c>=0){form_addEntryToSelectArray(oeff_cals,3,"-",c);c++}if(masterData.auth["view alldata"]){form_addEntryToSelectArray(oeff_cals,4,"Geburtstage (Gruppen)",c);c++;form_addEntryToSelectArray(oeff_cals,6,"Geburtstage (Alle)",c)}else form_addEntryToSelectArray(oeff_cals,6,"Geburtstage",c);c++}createMultiselect("filterGemeindekalendar",oeff_cals);if(embedded&&!minical){b.addHtml('<table width="100%"><tr>');if(filterCategoryIds==
null||filterCategoryIds.length>1)b.addHtml('<td width="190px"><div style="width:180px" id="filterGemeindekalendar"></div>');if(viewName=="eventView"){b.addHtml('<td width="110px">');b.addInput({controlgroup:false,cssid:"searchEntry",placeholder:"Suche",htmlclass:"input-small search-query"});b.addHtml('<td width="50px"> &nbsp;');b.addImage({src:"cal.png",cssid:"showminical",size:24});b.addHtml('<div id="minicalendar" style="display:none; position:absolute;background:#e7eef4;z-index:8001; height:240px; max-width:350px"></div>')}var e=
"Kalender";if($("#embeddedtitle").val()!=null)e=$("#embeddedtitle").val();b.addHtml('<td><font class="pull-right" style="font-size:180%">'+e+"</font> &nbsp; ");b.addHtml("</table>")}else embedded||b.addHtml('<div id="filterGemeindekalendar"></div>');if(masterData.auth["view churchresource"]){createMultiselect("filterRessourcen",masterData.resourcen);b.addHtml('<div id="filterRessourcen"></div>');$.each(masterData.resourceTypes,function(f,d){filter.filterRessourcen.addFunction(d.bezeichnung+" w&auml;hlen",
function(g){return g.resourcetype_id==d.id})})}a.push(b.render(true))}return a.join("")}
$(document).ready(function(){churchInterface.setModulename("churchcal");if($("#filtercategory_id").val()!=null)filterCategoryIds=$("#filtercategory_id").val().split(",");if($("#isembedded").length!=0)embedded=true;if($("#isminical").length!=0)minical=true;if($("#entries").length!=0)max_entries=$("#entries").val();churchInterface.setStatus("Lade Kennzeichen...");churchInterface.jsonRead({func:"getMasterData"},function(a){churchInterface.clearStatus();masterData=a;if($("#viewname").val()!=null)viewName=
$("#viewname").val();initCalendarView();a=[];viewName=="eventView"&&!embedded&&a.push('<div id="minicalendar" style="height:240px; max-width:350px"></div><br/><br/><br/>');a.push(renderPersonalCategories());a.push(renderGroupCategories());a.push(renderChurchCategories());$("#cdb_filter").html(a.join(""));filterMultiselect("filterMeineKalender","Meine Kalender");filterMultiselect("filterGruppenKalender","Gruppenkalender");filterMultiselect("filterGemeindekalendar",!embedded?"Gemeindekalender":"Kalender");
filterMultiselect("filterRessourcen","Ressourcen");if(embedded){$("#searchEntry").keyup(function(){filterName=$(this).val();send2Calendar("render")});$("#searchEntry").keydown(function(c){if(c.keyCode==13)return false});$("#searchEntry").focus()}$("#edit_personal").click(function(){editCategories(1,0)});$("#edit_group").click(function(){editCategories(0,0)});$("#edit_church").click(function(){editCategories(0,1)});$("#showminical").click(function(){$("#minicalendar").toggle()});$.each(filter,function(c,
b){b.data!=null&&$.each(b.data,function(e,f){churchcore_inArray(e,b.selected)?needData(c,f.id):hideData(c,f.id)})})})});
