function cdb_loadMasterData(c){timers.startMasterdata=new Date;churchInterface.setStatus("Lade Kennzeichen...");jQuery.getJSON("index.php?q=churchservice/ajax",{func:"getMasterData"},function(b){timers.endMasterdata=new Date;masterData=b;masterData.service_sorted=churchcore_sortData_numeric(masterData.service,"sortkey");b.version!=churchservice_js_version&&alert("Achtung, Versionen unterscheiden sich, bitte Cache loeschen! php:"+b.version+"/js:"+churchservice_js_version);churchInterface.clearStatus();
c!=null&&c()})}function cs_loadEventData(c,b,d){timers.startAllPersons=new Date;if(d==null)d=true;churchInterface.setStatus("Lade Eventdaten...");d={};d.func="getAllEventData";if(c!=null)d.id=c;churchInterface.jsonRead(d,function(a){timers.endAllPersons=new Date;a.events!=null&&jQuery.each(a.events,function(f,e){allEvents[e.id]=e});churchInterface.clearStatus();b!=null&&b()})}
function cs_loadNewEventData(c,b){churchInterface.setStatus("Lade Eventdaten...");var d={};d.func="getNewEventData";d.last_id=c;var a=[];churchInterface.jsonRead(d,function(f){f.events!=null&&jQuery.each(f.events,function(e,g){a.push(g.id);allEvents[g.id]=g});churchInterface.clearStatus();b!=null&&b(a)})}
function cs_loadPersonDataFromCdb(c){churchInterface.setStatus("Lade Personendaten...");var b={};jQuery.each(masterData.service,function(a,f){f.cdb_gruppen_ids!=null&&masterData.auth.viewgroup[f.servicegroup_id]&&jQuery.each(f.cdb_gruppen_ids.split(","),function(e,g){b[g]=true})});var d="";jQuery.each(b,function(a,f){if(a!="")d=d+a+","});d+="-1";churchInterface.jsonRead({func:"getPersonByGroupIds",ids:d},function(a){if(groups==null)groups=[];jQuery.each(a,function(f,e){groups[f]=e});churchInterface.clearStatus();
c!=null&&c()})}
function cs_loadAbsent(c){churchInterface.setStatus("Lade Abwesenheiten...");churchInterface.jsonRead({func:"getAbsent"},function(b){b!=null&&jQuery.each(b,function(d,a){if(allPersons[a.person_id]==null)allPersons[a.person_id]={};if(allPersons[a.person_id].absent==null)allPersons[a.person_id].absent=[];a.startdate=a.startdate.toDateEn(true);a.enddate=a.enddate.toDateEn(true);allPersons[a.person_id].absent.push(a);allPersons[a.person_id].name="moin"});listView.renderCalendar();churchInterface.clearStatus();c!=
null&&c()})}function cs_loadSongs(c){churchInterface.setStatus("Lade Songs...");churchInterface.jsonRead({func:"getAllSongs"},function(b){allSongs={};b!=null&&b.songs!=null&&jQuery.each(b.songs,function(d,a){allSongs[a.id]=a});churchInterface.clearStatus();c!=null&&c()})}
function cs_loadFacts(c){churchInterface.setStatus("Lade Fakten...");churchInterface.jsonRead({func:"getAllFacts"},function(b){b!=null&&jQuery.each(b,function(d,a){jQuery.each(a,function(f,e){if(allEvents[e.id]!=null){if(allEvents[e.id].facts==null)allEvents[e.id].facts={};allEvents[e.id].facts[e.fact_id]=e}})});churchInterface.clearStatus();c!=null&&c()})}
function cs_loadFiles(c){churchInterface.setStatus("Lade Dateien...");churchInterface.jsonRead({func:"getFiles"},function(b){if(b!=null){jQuery.each(allEvents,function(d,a){a.files=null});jQuery.each(b,function(d,a){if(allEvents[a.domain_id]!=null){if(allEvents[a.domain_id].files==null)allEvents[a.domain_id].files={};allEvents[a.domain_id].files[a.id]=a}})}listView.renderFiles();churchInterface.clearStatus();c!=null&&c()})};
