var a;function ListView(){StandardTableView.call(this);this.name="ListView";this.sortVariable="startdate";this.currentDate=(new Date).withoutTime();this.allDataLoaded=false;this.serviceGroupPersonWeight=this.renderTimer=null}Temp.prototype=StandardTableView.prototype;ListView.prototype=new Temp;listView=new ListView;a=ListView.prototype;a.getData=function(b){if(allEvents==null)return null;return b?churchcore_sortData(allEvents,this.sortVariable):allEvents};
a.renderMenu=function(){this_object=this;menu=new CC_Menu("Men&uuml;");masterData.auth.write&&menu.addEntry("Neues Event anlegen","anewentry","star");masterData.auth.admin&&menu.addEntry("Auslastung","aauslastung","fire");menu.addEntry("Einstellungen","asettingsview","wrench");masterData.auth.admin&&menu.addEntry("Stammdatenpflege","amaintainview","cog");menu.addEntry("Hilfe","ahelp","question-sign");menu.renderDiv("cdb_menu",churchcore_handyformat())?$("#cdb_menu a").click(function(){if($(this).attr("id")==
"anewentry")this_object.renderAddEntry();else if($(this).attr("id")=="avorlage")this_object.editTemplates();else if($(this).attr("id")=="aauslastung")this_object.showAuslastung();else if($(this).attr("id")=="aaddfilter"){this_object.furtherFilterVisible=this_object.furtherFilterVisible?false:true;this_object.renderFurtherFilter()}else if($(this).attr("id")=="aadmin"){menuDepth=$(this).attr("id");this_object.renderMenu()}else if($(this).attr("id")=="asettingsview"){menuDepth="amain";churchInterface.setCurrentView(settingsView)}else if($(this).attr("id")==
"amaintainview"){menuDepth="amain";churchInterface.setCurrentView(maintainView)}else if($(this).attr("id")=="amain"){menuDepth="amain";this_object.renderMenu()}else $(this).attr("id")=="ahelp"&&churchcore_openNewWindow("http://intern.churchtools.de/?q=help&doc=ChurchService");return false}):$("#cdb_menu").hide()};
a.renderListMenu=function(){var b=new CC_Navi;b.addEntry(churchInterface.isCurrentView("ListView"),"alistview","Listenansicht");masterData.auth.manageabsent&&b.addEntry(churchInterface.isCurrentView("CalView"),"acalview","Abwesenheiten");masterData.auth.editfacts&&b.addEntry(churchInterface.isCurrentView("FactView"),"afactview","Fakten");masterData.auth.viewsong&&b.addEntry(churchInterface.isCurrentView("SongView"),"asongview","Songs");b.addSearch(this.getFilter("searchEntry"));b.renderDiv("cdb_search",
churchcore_handyformat());this.implantStandardFilterCallbacks(this,"cdb_search");$("#cdb_search a").click(function(){if($(this).attr("id")=="alistview"){listView.furtherFilterVisible=this_object.furtherFilterVisible;churchInterface.setCurrentView(listView)}else if($(this).attr("id")=="acalview"){calView.furtherFilterVisible=this_object.furtherFilterVisible;churchInterface.setCurrentView(calView)}else if($(this).attr("id")=="afactview"){factView.furtherFilterVisible=this_object.furtherFilterVisible;
factView.currentDate=this_object.currentDate;churchInterface.setCurrentView(factView)}else $(this).attr("id")=="asongview"&&churchInterface.setCurrentView(songView);return false})};a.addSecondMenu=function(){return'<p>Weitere Optionen: <a id="extern" href="?q=ical&id='+masterData.user_pid+'">Abonniere meinen Dienstplan per iCal</a>'};
a.showLastChanges=function(){var b=this,c=new Date;churchInterface.jsonWrite({func:"saveSetting",sub:"lastVisited",val:c.toStringEn(true)});var e=masterData.settings.lastVisited!=null?masterData.settings.lastVisited.toDateEn():c.toStringEn(true),g="",f=0;$.each(this.getData(true),function(h,d){_first=true;d.services!=null&&d.startdate.toDateEn()>c&&$.each(d.services,function(j,i){if(i.valid_yn==1&&i.user_id!=masterData.user_pid&&masterData.auth.leaderservice[i.service_id]){j=b.renderEntryHistory(d.id,
i.service_id,i.counter,e,true);if(j!=""){if(_first){_first=false;f+=1;g=g+"<tr><td>"+d.startdate.toDateEn(true).toStringDe(true)+"<br><b>"+d.bezeichnung+"</b><td>"}g+=masterData.service[i.service_id].bezeichnung;g+=j}}})});g!=""&&this.showDialog("Neuigkeiten innerhalb Deiner Gruppe",'<table class="table table-condensed">'+g+"</table>",600,600,{"Sp\u00e4ter nochmal zeigen":function(){churchInterface.jsonWrite({func:"saveSetting",sub:"lastVisited",val:e.toStringEn(true)});$(this).dialog("close")},Schliessen:function(){$(this).dialog("close")}})};
a.messageReceiver=function(b){var c=this;if(this==churchInterface.getCurrentView())if(b=="allDataLoaded"){$("#id").val()!=null&&$("#eventservice_id").val()!=null&&c.renderEditEventService($("#event_id").val(),$("#eventservice_id").val());$(window).width()>600&&c.showLastChanges();c.allDataLoaded=true}else b=="pollForNews"&&cs_loadNewEventData(churchInterface.getLastLogId(),function(e){$.each(e,function(g,f){c.renderList(allEvents[f])})})};
function _getEditEventFromForm(){obj={};if($("#EventId").val()!=null)obj.id=$("#EventId").val();obj.category_id=$("#Inputcategory").val();obj.bezeichnung=$("#InputBezeichnung").val();obj.stunde=$("#InputDatumStunde").val();obj.minute=$("#InputDatumMinute").val();var b=new Date;b=$("#InputDatumTag").val().toDateDe();b.setHours(obj.stunde);b.setMinutes(obj.minute);obj.startdate=b.toStringEn(true);if($("#InputDatumTagEnde").val()!=null){b=new Date;b=$("#InputDatumTagEnde").val().toDateDe();b.setHours($("#InputDatumStundeEnde").val());
b.setMinutes($("#InputDatumMinuteEnde").val());obj.enddate=b.toStringEn(true)}obj.special=$("#InputSpecial").val();obj.admin=$("#InputAdmin").val();var c={};$("#in_edit input").each(function(){if($(this).attr("id").indexOf("cb_")==0)if($(this).attr("checked"))c[$(this).attr("id").substr(3,99)]=1;else if($(this).val()>0)c[$(this).attr("id").substr(3,99)]=$(this).val()});obj.services=c;return obj}
function _getTemplateIdFromName(b){var c=null;$.each(masterData.eventtemplate,function(e,g){if(g.bezeichnung.toUpperCase()==b.toUpperCase()){c=g.id;return false}});return c}a=ListView.prototype;a.saveEventAsTemplate=function(b,c,e){b.func="saveTemplate";b.event_bezeichnung=b.bezeichnung;b.bezeichnung=c;b.template_id=_getTemplateIdFromName(c);b.dauer_sec=(b.enddate.toDateEn(true).getTime()-b.startdate.toDateEn(true).getTime())/1E3;churchInterface.jsonWriteSyncron(obj);cdb_loadMasterData(function(){e(_getTemplateIdFromName(c))})};
a.saveEditEvent=function(b){function c(){if(_array[d]!=null){churchInterface.jsendWrite(_array[d],c);b.html("<b>Daten werden gespeichert f&uuml;r Woche "+d+"...</b><br/><br/>")}else{b.html("<b>Lade nun Eventliste neu...</b>");cs_loadEventData(null,function(){b.dialog("close");e.renderList()})}d+=1}var e=this,g=_getEditEventFromForm();g.func="saveEvent";if($("#EventId").val()!=null&&g.startdate.toDateEn(true).getTime()!=allEvents[$("#EventId").val()].startdate.toDateEn(true).getTime()&&!confirm("Durch die Anpassung des Datum verschiebt sich auch der Kalendereintrag und ggfl. weitere Ressourcenanfragen. Soll wirklich gespeichert werden?"))return null;
var f=$("#InputRepeats").val();if(f==null)f=1;f=$("#InputDatumTagWiederholungEnde").val();f=f==null?new Date(g.startdate.toDateEn()):f.toDateDe(true);f.addDays(1);b.html("<p>");_array=[];for(var h=g.startdate.toDateEn(true);h<f;){_array.push(jQuery.extend({},g));h.addDays(7);g.startdate=h.toStringEn(true)}var d=0;c()};
a.renderEditEvent=function(b){var c=[],e=null;b.bookings&&c.push('<div class="alert alert-error">Achtung: Das Event enth&auml;lt auch Ressourcen-Buchungen, deshalb Datum & Uhrzeit in <a href="?q=churchcal&date='+b.startdate.toDateEn(false).toStringEn(false)+'">'+masterData.churchcal_name+"</a> bearbeiten. </div>");c.push('<div id="in_edit">');c.push('<div style="float:left;wid_th:50%">');c.push("<table>");if(b.id==null){if(masterData.settings.aktuelleEventvorlage==null)masterData.settings.aktuelleEventvorlage=
0;e=masterData.eventtemplate[masterData.settings.aktuelleEventvorlage];if(e!=null){if(e.category_id!=null)b.category_id=e.category_id;b.bezeichnung=e.event_bezeichnung;b.special=e.special;var g=b.startdate.toDateEn();e.stunde!=null&&g.setHours(e.stunde);e.minute!=null&&g.setMinutes(e.minute);b.startdate=g.toStringEn(true);g=b.startdate.toDateEn(true);e.dauer_sec!=null?g.setSeconds(g.getSeconds()+e.dauer_sec):g.setHours(g.getHours()+1);b.enddate=g.toStringEn(true);b.special=e.special;b.admin=e.admin}c.push("<tr><td>Vorlage<td>");
c.push(form_renderSelect({data:masterData.eventtemplate,cssid:"Inputeventtemplate",selected:masterData.settings.aktuelleEventvorlage,htmlclass:"input-medium",controlgroup:false}));if(masterData.auth.admin){c.push('&nbsp; <a href="#" id="saveTemplate" title="Vorlage speichern">'+this.renderImage("save",20)+"</a>");e.id!=0&&c.push('&nbsp;<a href="#" id="deleteTemplate" title="Vorlage entfernen">'+this.renderImage("delete_2",20)+"</a>")}}var f=[];form_addEntryToSelectArray(f,0,"0");form_addEntryToSelectArray(f,
15,"15");form_addEntryToSelectArray(f,30,"30");form_addEntryToSelectArray(f,45,"45");var h=[];for(g=0;g<24;g++)form_addEntryToSelectArray(h,g,g,g);b.id!=null&&c.push('<input type=hidden id="EventId" value="'+b.id+'"/>');c.push("<tr><td>"+form_renderInput({cssid:"InputDatumTag",label:"Datum",controlgroup:false,separator:"<td><nobr>",value:b.startdate.toDateEn().toStringDe(),type:"small",disabled:b.bookings})+"&nbsp;");c.push(form_renderSelect({data:h,cssid:"InputDatumStunde",selected:b.startdate.toDateEn().getHours(),
htmlclass:"input-mini",disabled:b.bookings,controlgroup:false})+" : ");c.push(form_renderSelect({data:f,cssid:"InputDatumMinute",selected:b.startdate.toDateEn().getMinutes(),type:"mini",disabled:b.bookings,controlgroup:false}));c.push("</nobr>");c.push('<div id="dp_inputdatumtag" style="position:absolute;background:#e7eef4;z-index:8001;"/>');c.push("<tr><td>"+form_renderInput({cssid:"InputDatumTagEnde",label:"Bis",controlgroup:false,separator:"<td><nobr>",value:b.enddate.toDateEn().toStringDe(),disabled:b.bookings,
type:"small"})+"&nbsp;");c.push(form_renderSelect({data:h,cssid:"InputDatumStundeEnde",selected:b.enddate.toDateEn().getHours(),htmlclass:"input-mini",disabled:b.bookings,controlgroup:false})+" : ");c.push(form_renderSelect({data:f,cssid:"InputDatumMinuteEnde",selected:b.enddate.toDateEn().getMinutes(),type:"mini",disabled:b.bookings,controlgroup:false}));c.push("</nobr>");c.push('<div id="dp_inputdatumtagende" style="position:absolute;background:#e7eef4;z-index:8001;"/>');c.push("<tr><td>Kalender<td>"+
this.renderSelect(b.category_id,"category",masterData.category));c.push("<tr><td>"+this.renderInput("InputBezeichnung","Bezeichnung",b.bezeichnung,20));c.push("<tr><td>"+this.renderTextarea("InputSpecial","Weitere Infos",b.special,20,3));c.push("<tr><td>"+this.renderInput("InputAdmin","Event-Admin",b.admin,20,!masterData.auth.admin));c.push('<p><small><span id="adminName">Kommaseparierte Person-Ids, dazu Name eintippen.</span></small></p>');b.admin!=null&&b.admin!=""&&churchInterface.jsonRead({func:"getPersonById",
id:b.admin},function(i){var k="";$.each(i.data,function(l,m){if(k!="")k+="<br/>";k=k+m.vorname+" "+m.name});$("#adminName").html(k)},"churchdb");if(b.id==null){f=[];for(g=1;g<10;g++){h=[];h.id=g;h.bezeichnung=g+"";f[g]=h}c.push("<tr><td>Wiederholung bis<td>"+form_renderInput({cssid:"InputDatumTagWiederholungEnde",controlgroup:false,value:b.startdate.toDateEn().toStringDe(),type:"small"}));c.push('<div id="dp_inputdatumtagwiederholung" style="position:absolute;background:#e7eef4;z-index:8001;"/>');
c.push("<p><small>W&ouml;chentlich Wiederholung des Events</small>")}b.id!=null&&c.push('<p align="right"><small>Id:'+b.id+"</small>");c.push("</table><br/>");c.push("</div>");c.push('<div style="wid_th:40%;float:right;padding-right:20px;">');c.push("<table>");b.id==null&&$.each(churchcore_sortData(masterData.servicegroup,"sortkey"),function(i,k){c.push("<tr><th colspan=2>"+k.bezeichnung+"<td>");$.each(masterData.service_sorted,function(l,m){if(m.servicegroup_id==k.id){c.push("<tr><td>"+m.bezeichnung+
"&nbsp;");m.notiz!=null&&m.notiz!=""&&c.push("<small>("+m.notiz.trim(10)+")</small>");l=0;if(masterData.eventtemplate_services!=null&&masterData.eventtemplate_services[e.id]!=null){if(masterData.eventtemplate_services[e.id][m.id]!=null)l=masterData.eventtemplate_services[e.id][m.id]}else if(b.services!=null){var n=0;$.each(b.services,function(p,q){if(q.service_id==m.id)n+=1});if(n>0)l=n}c.push('<td width=10px><input type="checkbox" id="cb_'+m.id+'" class="cdb-checkbox"');l>0&&c.push("checked");c.push("/>")}})});
c.push("</table>");c.push("</div>");c.push("<br/>");c.push("</div>");c.push('<div style="clear:both">');var d=this,j=this.showDialog("Ver&auml;nderung des Events",c.join(""),b.id==null?680:450,b.id==null?600:500,{Speichern:function(){d.saveEditEvent(j);if(b.id==null)d.currentDate=b.startdate.toDateEn(false)}});this.autocompletePersonSelect("#InputAdmin",false,function(i,k){$("#adminName").html(k.item.label)});$("#saveTemplate").click(function(){var i=prompt("Bitte den Namen der Vorlage angeben:",
e.bezeichnung);i!=null&&d.saveEventAsTemplate(_getEditEventFromForm(),i,function(k){masterData.settings.aktuelleEventvorlage=k;j.dialog("close");d.renderEditEvent(b)})});$("#deleteTemplate").click(function(){if(confirm("Soll die Vorlage "+e.bezeichnung+" wirklich entfernt werden?")){churchInterface.jsonWriteSyncron({func:"deleteTemplate",id:e.id});delete masterData.eventtemplate[e.id];j.dialog("close");masterData.settings.aktuelleEventvorlage=0;d.renderEditEvent(b)}});$("#InputDatumTag").click(function(){d.implantDatePicker("inputdatumtag",
b.startdate.toDateEn().toStringDe(),function(i){b.startdate=i.toDateDe().toStringEn();$("#InputDatumTag").val(i);$("#InputDatumTagEnde").val(i);$("#InputDatumTagWiederholungEnde").val(i)})});$("#InputDatumTagEnde").click(function(){d.implantDatePicker("inputdatumtagende",$("#InputDatumTagEnde").val(),function(i){if(i.toDateDe(false)<b.startdate.toDateEn(false))alert("Enddatum kann nicht vor dem Anfangsdatum liegen!");else{b.enddate=i.toDateDe().toStringEn();$("#InputDatumTagEnde").val(i);$("#InputDatumTagWiederholungEnde").val(i)}})});
$("#InputDatumTagWiederholungEnde").click(function(){d.implantDatePicker("inputdatumtagwiederholung",$("#InputDatumTagWiederholungEnde").val(),function(i){if(i.toDateDe(false)<b.startdate.toDateEn(false))alert("Wiederholungsdatum kann nicht vor dem Startdatum liegen!");else{b.widerholungende=i.toDateDe().toStringEn();$("#InputDatumTagWiederholungEnde").val(i)}})});$("#InputDatumStunde").change(function(){$("#InputDatumStundeEnde").val($(this).val()*1+1)});$("#in_edit select").change(function(){if($(this).attr("id")==
"Inputeventtemplate"){masterData.settings.aktuelleEventvorlage=$(this).val();b.category_id=$("#Inputcategory").val();j.dialog("close");d.renderEditEvent(b)}});$("#in_edit input").click(function(){if($(this).attr("id").indexOf("cb_")==0&&!$(this).attr("checked")){var i=$(this).attr("id").substr(3,99),k=false;b.services!=null&&$.each(b.services,function(l,m){if(m.service_id==i&&m.valid_yn==1&&m.name!=null){k=true;return false}});if(k){alert("Solange hier ein Dienst vorgeschlagen oder zugesagt ist, ist das Entfernen nicht erlaubt!");
$(this).attr("checked",true)}}});b.id!=null&&j.dialog("addbutton","Entfernen",function(){if(confirm("Soll das gesamte Event wirklich entfernt werden?")){obj={};obj.func="deleteEvent";obj.id=b.id;$.getJSON("index.php?q=churchservice/ajax",obj,function(i){if(i!="ok")alert("Fehler beim Speichern: "+i);else{delete allEvents[b.id];j.dialog("close");d.renderList()}})}});j.dialog("addbutton","Abbruch",function(){$(this).dialog("close")})};
a.renderAddEntry=function(){var b={},c=new Date(this.currentDate);c.setHours(12);b.startdate=c.toStringEn(true);this.renderEditEvent(b)};a.isLeaderOfServiceGroup=function(b){if(b==null)return false;isleader=false;$.each(masterData.service,function(c,e){if(e.servicegroup_id==b&&masterData.auth.leaderservice[e.id]==true){isleader=true;return false}});return isleader};
a.getMemberOfOneGroup=function(b,c){if(b==null||c==null||groups==null)return false;b=b.split(",");var e=false;$.each(b,function(g,f){groups[f]!=null&&$.each(groups[f],function(h,d){if(d.p_id==c&&d.leiter!=-1)e=d})});return e};
a.renderEventServiceEntry=function(b,c,e){if(c.valid_yn==1&&masterData.service[c.service_id]!=null){var g=[];g.push('<p style="line-height:1.0;margin-bottom:4px;">');var f=false,h=masterData.auth.memberservice[c.service_id]==true,d=masterData.auth.leaderservice[c.service_id]==true;if(masterData.auth.editservice[c.service_id]||c.cdb_person_id!=null&&c.cdb_person_id==masterData.user_pid||c.name==null&&h||d||e)f=true;e='tooltip="'+b+"_"+c.id+'" '+(d||masterData.auth.editservice[c.service_id]||e?"history=true":
"")+" "+(h?"member=true":" ");g.push("<small>");f?g.push('<a href="#" '+e+' id="edit_es_'+b+'" eventservice_id="'+c.id+'" style="text-decoration:none">'):g.push("<span "+e+">");_class="";if(c.cdb_person_id!=null&&c.cdb_person_id==masterData.user_pid)_class=c.zugesagt_yn==1?"zugesagt":"angefragt";if(this.filter.filterDienstgruppen==null||masterData.settings.listViewTableHeight!=null&&masterData.settings.listViewTableHeight==0){g.push('<font class="'+_class+'"><b>'+masterData.service[c.service_id].bezeichnung);
c.counter!=null&&g.push(" "+c.counter);g.push(": </b></font>")}style=_class="";if(c.zugesagt_yn==0)style+="color:red;";if(c.cdb_person_id!=null&&c.cdb_person_id==masterData.user_pid)_class=c.zugesagt_yn==1?"zugesagt":"angefragt";g.push('<font class="'+_class+'" style="'+style+'">');b=c.name;if(masterData.service[c.service_id].cdb_gruppen_ids!=null&&c.name==null)b=c.cdb_person_id;b!=null&&g.push(b.trim(18));if(b==null||c.zugesagt_yn==0)g.push("?");g.push("</font>");f?g.push("</a>"):g.push("</span>");
g.push("</small>");return g.join("")}return""};a.groupingFunction=function(b){return b.startdate.toDateEn(false).getDayInText()+", "+b.startdate.toDateEn(false).toStringDe()};
a.getCountCols=function(){var b=this,c=0;b=this;if(this.filter.filterDienstgruppen==null){$.each(masterData.servicegroup,function(e,g){if(masterData.auth.viewgroup[g.id]||b.filter["filterMeine Filter"]==2)if(masterData.settings["viewgroup"+g.id]==null||masterData.settings["viewgroup"+g.id]==1)c++});c++}else $.each(masterData.service,function(e,g){g.servicegroup_id==b.filter.filterDienstgruppen&&c++});return c+2};
a.getAdditionalServicesToServicegroup=function(b,c,e){this_object=this;var g=[];$.each(masterData.service_sorted,function(f,h){if(h.servicegroup_id==c&&(masterData.auth.write||masterData.auth.leaderservice[h.id]||e))if(masterData.auth.editgroup[c]||this_object.isLeaderOfServiceGroup(c)||e){var d=0,j=true;b.services!=null&&$.each(b.services,function(i,k){if(k.service_id==h.id&&k.valid_yn==1){d++;if(k.name!=null)j=false}});f=[];f.id=h.id;f.count=d;if(d>0)f.checked="checked";g.push(f)}});return g};
function bin_ich_admin(b){if(b==null)return false;var c=false;$.each(b.split(","),function(e,g){if($.trim(g)==masterData.user_pid){c=true;return false}});return c}
ListView.prototype.renderListEntry=function(b){this_object=this;var c=bin_ich_admin(b.admin),e=c;rows=[];var g=100/(this.getCountCols()-1);masterData.category[b.category_id].color!=null&&rows.push('<div title="Kalender: '+masterData.category[b.category_id].bezeichnung+'" style="background-color:'+masterData.category[b.category_id].color+'; margin-top:5px; margin-left:3px; width:4px; height:15px"></div>');rows.push("<td>");masterData.auth.write?rows.push('<b><a href="#" id="editEvent'+b.id+'">'+b.startdate.toDateEn(true).toStringDeTime()+
" "+b.bezeichnung+"</a></b><br/>"):rows.push("<b>"+b.startdate.toDateEn(true).toStringDeTime(true)+" "+b.bezeichnung+"</b><br/>");b.special!=null&&b.special!=""&&rows.push('<div class="event_info"><p><small>'+b.special.str_replace("\n","<br/>")+"</small></div>");var f=masterData.auth.write||c;f||$.each(masterData.service,function(h,d){if(masterData.auth.leaderservice[d.id]){f=true;return false}});f&&rows.push('<a href="#" id="editNote'+b.id+'" title="Editiere \'Weitere Infos\'">'+this.renderImage("info")+
"</a>&nbsp;");!f&&b.services!=null&&$.each(b.services,function(h,d){if(d.valid_yn==1&&masterData.user_pid==d.cdb_person_id){f=true;return false}});f&&rows.push('<a href="#" id="attachFile'+b.id+'" title="Datei zum Event anh&auml;ngen">'+this.renderImage("paperclip")+"</a>&nbsp;");rows.push('<a href="#" id="mailEvent'+b.id+'" title="Erstelle E-Mail an Personen des Events">'+this.renderImage("email")+"</a>&nbsp;");if(b.admin!=null)c?rows.push('<a href="#" id="filterMyAdmin'+b.id+'" title="Du bist Admin!">'+
this.renderImage("person")+"</a>&nbsp;"):rows.push(this.renderImage("person_sw",null,"Das Event hat einen Admin."));rows.push('<div class="filelist" data-id="'+b.id+'"></div>');if(this.filter.filterDienstgruppen==null){$.each(this.sortMasterData(masterData.servicegroup,"sortkey"),function(h,d){var j=false;if(masterData.settings["viewgroup"+d.id]==null||masterData.settings["viewgroup"+d.id]==1)if(masterData.auth.viewgroup[d.id]||this_object.filter["filterMeine Filter"]==2){rows.push('<td valign="top" class="service" data-servicegroup-id="'+
d.id+'" style="position:relative" width="'+g+'%">');$.each(masterData.service_sorted,function(i,k){if(d.id==k.servicegroup_id){if(masterData.auth.leaderservice[k.id]==true)j=true;b.services!=null&&$.each(churchcore_sortData(b.services,"counter",false,false),function(l,m){if(m.service_id==k.id){rows.push(this_object.renderEventServiceEntry(b.id,m,c));e=true}})}});if(masterData.auth.write||c||j){rows.push('<p><a href="#" id="addService" event_id="'+b.id+'" servicegroup_id="'+d.id+'">+</a>');e=true}}});
rows.push('<td width="16px">')}else $.each(masterData.service_sorted,function(h,d){if(b.services!=null&&d.servicegroup_id==this_object.filter.filterDienstgruppen){rows.push("<td>");$.each(b.services,function(j,i){if(i.service_id==d.id&&i.valid_yn==1){rows.push(this_object.renderEventServiceEntry(b.id,i,c));e=true}})}});return e?rows.join(""):null};
ListView.prototype.makeFilterCategories=function(b){var c=this;c.filter.filterKategorien=new CC_MultiSelect(masterData.category,function(){masterData.settings.filterCategory=this.getSelectedAsArrayString();churchInterface.jsonWrite({func:"saveSetting",sub:"filterCategory",val:masterData.settings.filterCategory});c.renderList()});c.filter.filterKategorien.setSelectedAsArrayString(b)};
ListView.prototype.getListHeader=function(){var b=this;if(masterData.settings.filterCategory==""||masterData.settings.filterCategory==null||$("#externevent_id").val()!=null)delete masterData.settings.filterCategory;if(this.filter.filterKategorien==null){b.makeFilterCategories(masterData.settings.filterCategory);this.filter.filterKategorien.setSelectedAsArrayString(masterData.settings.filterCategory)}this.filter.filterKategorien.render2Div("filterKategorien",{label:"Kalender"});this.currentRenderDate=
null;tableHeader='<th><a href="#" id="sortdatum">Events</a>';if(this.filter.filterDienstgruppen==null){$.each(this.sortMasterData(masterData.servicegroup),function(c,e){if(masterData.settings["viewgroup"+e.id]==null||masterData.settings["viewgroup"+e.id]==1)if(masterData.auth.viewgroup[e.id]||b.filter["filterMeine Filter"]==2){tableHeader=tableHeader+'<th class="hover" id="header'+e.id+'">'+e.bezeichnung;tableHeader=tableHeader+'<span id="headerspan'+e.id+'" style="display:none;float:right"><a href="#" id="delCol'+
e.id+'">'+b.renderImage("minus",16)+"</a></span>"}});tableHeader=tableHeader+'<th width="16px"><a href="#" id="addMoreCols">'+this.renderImage("plus",16)+"</a>"}else $.each(masterData.service_sorted,function(c,e){if(e.servicegroup_id==b.filter.filterDienstgruppen){tableHeader=tableHeader+"<th>"+e.bezeichnung;if(e.notiz!="")tableHeader=tableHeader+" ("+e.notiz+")"}});return tableHeader};
function _checkVorschlagen(b,c,e){var g=false;if(c)g=true;else{c=$("#InputNameSelect").val();if(c>0){if(e&&c!=b.cdb_person_id)g=true;if(!e&&c!=masterData.user_pid)g=true}}g?$("#divvorschlagen").show():$("#divvorschlagen").hide()}function _checkZusagen(b,c,e){var g=false;if(c){if(e)g=true}else{c=$("#InputNameSelect").val();if(c>0)if(e&&(b.zugesagt_yn==0||c!=b.cdb_person_id)||c==masterData.user_pid&&b.zugesagt_yn==0)g=true}g?$("#divzusagen").show():$("#divzusagen").hide()}
function _checkAbsagen(b,c,e){var g=false;if(c){if(e&&b.name!=null)g=true}else{c=$("#InputNameSelect").val();if(c>0){if(e&&b.cdb_person_id==c)g=true;if(b.cdb_person_id==masterData.user_pid&&c==b.cdb_person_id)g=true}}g?$("#divabsagen").show():$("#divabsagen").hide()}
ListView.prototype._renderAuslastung=function(b,c){if($("#InputNameSelect").val()>0){if(masterData.auth.admin||masterData.auth.leaderservice[c]){$("#divauslastung").html("Auslastung: "+this_object.renderPersonAuslastung($("#InputNameSelect").val(),b,c,true));$("#divauslastung a").click(function(){if($(this).attr("id")=="personHistory"){var e=[],g=$("#InputNameSelect").val();e.push('<table class="table table-condensed"><tr><th>Datum<th>Event<th>Service<th>Zugesagt<th>Notiz');$.each(churchcore_sortData(allEvents,
"startdate",true),function(f,h){h.services!=null&&$.each(h.services,function(d,j){if(j.user_id==g&&(j.valid_yn==0&&j.cdb_person_id==null||j.valid_yn==1&&j.cdb_person_id!=null)){e.push("<tr><td>"+h.startdate.toDateEn(true).toStringDe(true));e.push("<td>"+h.bezeichnung);e.push("<td>"+masterData.service[j.service_id].bezeichnung);e.push("<td>"+(j.zugesagt_yn==1?"<font>ja":"<font style=color:red>nein")+"</font>");e.push("<td>"+(j.reason!=null?j.reason:""))}})});e.push("</table>");form_showOkDialog("Anzeige der Auslastung",
e.join(""),600,600)}})}}else $("#divauslastung").html("")};function personIsAbsent(b,c){var e=null;allPersons[b]!=null&&allPersons[b].absent!=null&&$.each(allPersons[b].absent,function(g,f){g=new Date(f.enddate);f.startdate.getHours()==0&&f.enddate.getHours()==0&&g.addDays(1);if(f!=null&&f.startdate<=c&&g>=c){e=f;return false}});return e}function _checkPersonTag(b,c){var e=false;if(b==null||b=="")e=true;else $.each(b,function(g,f){if(c!=null)if(churchcore_inObject(f,c))e=true});return e}
function _checkWarSchonMal(b,c,e,g){var f=false;$.each(c,function(h,d){if(d.cdb_person_id==b)f=d.valid_yn==0||d.service_id!=e||d.counter!=g?true:false});return f}
ListView.prototype.getAllPersonsForService=function(b){var c=masterData.service[b].cdb_gruppen_ids,e=masterData.service[b].cdb_tag_ids==null?null:masterData.service[b].cdb_tag_ids.split(","),g={};$.each(c.split(","),function(f,h){groups[h]!=null&&$.each(groups[h],function(d,j){if(_checkPersonTag(e,j.tags))if(g[j.p_id]==null){d={};d.id=j.p_id;d.bezeichnung=j.vorname+" "+j.name;g[d.id]=d}})});return g};
ListView.prototype.selectPossiblePersonForService=function(b,c,e,g,f){var h=this;if(b!=null){var d=-100000;lowestId=null;$.each(b,function(j,i){if(f==null||f[i.id]==null){j=allEvents[c].startdate.toDateEn();var k=masterData.service[e].servicegroup_id;if(i.bewertet==null){i.bewertet=true;wert=i.wert;if(wert==null)wert=0;if(personIsAbsent(i.id,j)!=null){wert-=1E3;i.reason="Abwesend"}else if(_checkWarSchonMal(i.id,allEvents[c].services,e,g)){wert-=500;i.reason="War schon mal"}else{var l=h.getPersonAuslastung(i.id,
e,j);if(h.serviceGroupPersonWeight[i.id]!=null&&h.serviceGroupPersonWeight[i.id][k]!=null){var m=h.serviceGroupPersonWeight[i.id][k];if(l.monate[0]!=null&&m.max_per_month!=null&&m.max_per_month*1<=l.monate[0].person*1){wert-=100;i.reason="Maximaler gew&uuml;nschter Einsatz erreicht"}if(j.getHours()>=13)if(m.morning_weight==1)wert+=10;else{if(m.morning_weight>=2){wert-=100;i.reason="Einsatz nur morgens"}}else if(m.morning_weight==-1)wert+=10;else if(m.morning_weight<=-2){wert-=100;i.reason="Einsatz nur abends"}m.relation_weight!=
0&&$.each(b,function(n,p){if(p.id==m.relation_id)if(m.relation_weight==-1&&p.bewertet!=null){if(p.wert>-100){wert-=100;i.reason="Nicht mit Partner"}}else if(m.relation_weight==1&&p.bewertet!=null)p.wert+=10})}if(l.monate[0]!=null)wert-=l.monate[0].person*3;if(l.monate[-1]!=null)wert-=l.monate[-1].person*2;if(l.monate[-2]!=null)wert-=l.monate[-2].person*1;if(l.monate[1]!=null)wert-=l.monate[1].person*2;if(l.letzter_einsatz_davor!=null)if(l.letzter_einsatz_davor.dayDiff(j)<7){wert-=50;i.reason="letzter Einsatz <7 Tage"}else if(l.letzter_einsatz_davor.dayDiff(j)<
14)wert-=10;if(l.naechster_einsatz_danach!=null)if(l.naechster_einsatz_danach.dayDiff(j)>-7){i.reason="n&auml;chster Einsatz <7 Tage";wert-=50}else if(l.naechster_einsatz_danach.dayDiff(j)>-14)wert-=10}i.wert=wert;i.bezeichnung=i.bezeichnung+" "+wert;if(i.reason!=null)i.bezeichnung="("+i.bezeichnung+") - "+i.reason}if(i.wert!=null&&i.wert>d){d=i.wert;lowestId=i.id}}});return d>-100?lowestId:null}};
ListView.prototype._renderInputName=function(b,c,e,g){var f=Array(),h=c.service_id;if(b)if(c.cdb_person_id==null){f.push('<input type="text" id="InputName" class="cdb-textfield" size="30" value="');f.push(c.name);f.push('"/>');f.push('<p style="color:gray"><small><i>Person kann nicht automatisch benachrichtigt werden!</i></small><br/>')}else{f.push('<select id="InputNameSelect" class="cdb-input"><option value="'+c.cdb_person_id+'">'+c.name+"</option></select>");b=false}else{var d=false;f.push("<p>Person ausw&auml;hlen");
f.push('<p><select id="InputNameSelect" class="cdb-input">');var j=masterData.service[h].cdb_gruppen_ids,i=masterData.service[h].cdb_tag_ids==null?null:masterData.service[h].cdb_tag_ids.split(",");if(j==null)j="-1";var k=false,l=true;$.each(j.split(","),function(m,n){var p=true;if(j.indexOf(",")>0)p=false;groups[n]!=null&&$.each(churchcore_sortData(groups[n],"vorname"),function(q,o){if(_checkPersonTag(i,o.tags)){l=false;if(!p){p=true;f.push('<option value="-2"> == '+o.bezeichnung.trim(26)+" == ")}q=
personIsAbsent(o.p_id,allEvents[e].startdate.toDateEn())!=null;if(_checkWarSchonMal(o.p_id,allEvents[e].services,h,c.counter))d=q=true;f.push('<option value="'+o.p_id+'"');if(c.cdb_person_id==o.p_id){f.push(" selected");k=true}f.push(">"+(q?"(":"")+(o.vorname+" "+o.name).trim(26)+(q?")":""))}})});if(!k&&c.cdb_person_id!=null){f.push('<option selected value="'+c.cdb_person_id+'">'+c.name+"</option>");l=false}l&&f.push('<option value="-2">-- keine Person in der Liste --</option>');g&&c.name==null&&
f.push('<option value="-1">... andere Person hinzuf&uuml;gen</option>');f.push("</Select>");f.push("<p><small>");d&&f.push("() = Personen in Klammern wurden bereits f&uuml;r dieses Event angefragt. Eine weitere Anfrage ist hier u.U. nicht sinnvoll.<br/>");f.push("</small></p>")}f.push('<input type="hidden" id="nameofadditionperson" name="UserBrowser" value="'+c.name+'"/>');return f.join("")};function _checkEMail(){$("#InputNameSelect").val()>0?$("#divemail").show():$("#divemail").hide()}
function _completePersonInfo(b){$("#divkontakt").html("");b!=null&&masterData.auth.viewchurchdb&&churchInterface.jsonRead({func:"getPersonById",id:b},function(c){if(c.data!=null&&c.data[b]!=null){c=c.data[b];txt="";if(c.email!=null&&c.email!="")txt=txt+'E-Mail: <a href="mailto:'+c.email+'">'+c.email+"</a><br/>";if(c.telefonhandy!=null&&c.telefonhandy!="")txt=txt+'Handy: <a href="tel:'+c.telefonhandy+'">'+c.telefonhandy+"</a><br/>";else if(c.telefonprivat!=null&&c.telefonprivat!="")txt=txt+'Tel.: <a href="tel:'+
c.telefonprivat+'">'+c.telefonprivat+"</a><br/>";txt!=""&&$("#divkontakt").html("<p><small>"+txt+"</small>")}},"churchdb")}
ListView.prototype.renderEditEventService=function(b,c,e){var g=this,f=[];if(e==null)e=false;var h=this.getEventService(b,c),d=h.service_id,j=masterData.service[d].cdb_gruppen_ids==null&&h.cdb_person_id==null||e||h.cdb_person_id==null&&h.name!=null,i=masterData.auth.editservice[d]||masterData.auth.leaderservice[d]==true||bin_ich_admin(allEvents[b].admin);f.push("<legend>Dienst <i>");masterData.auth.editservice[d]&&f.push('<a href="#" id="editService"><font style="text-decoration:underline">');f.push(masterData.service[d].bezeichnung);
masterData.service[d].notiz!=""&&f.push(" ("+masterData.service[d].notiz+")");masterData.auth.editservice[d]&&f.push("</font></a>");f.push("</i> besetzen:</legend>");f.push('<div id="in_edit"><div class="row-fluid">');f.push('<div class="span5">');f.push('<div id="divinputname">');f.push(this._renderInputName(j,h,b,i));f.push("</div>");f.push("");f.push('<span style="display:none" id="divvorschlagen"><input type="button" value="Vorschlagen" class="btn btn-warning" />&nbsp;</span>');f.push('<span style="display:none" id="divzusagen"><input type="button" value="Zusagen" class="btn btn-success"/>&nbsp;</span>');
f.push('<span style="display:none" id="divabsagen"><input type="button" value="Absagen" class="btn btn-danger"/>&nbsp; </span>&nbsp;');f.push('</div><div class="span1"></div><div class="span6">');f.push('<div class="well"><h4>Infos zur Person</h4><p><span id="divauslastung"></span>');f.push('<p><span id="divemail"><a href="#" title="Person eine E-Mail senden" id="mailPerson">'+g.renderImage("email")+"</a> <small>Web-EMail an ausgew&auml;hlte Person</small></span>&nbsp;");f.push('<div id="divkontakt"></div>');
f.push("</div></div></div>");if(i){f.push("<p><h4>Historie</h4>");f.push(g.renderEntryHistory(b,h.service_id,h.counter,null,i||masterData.auth.admin))}f.push('<div id="divshowhistory"></div>');f.push("</div>");var k=form_showCancelDialog("Anfrage "+masterData.servicegroup[masterData.service[d].servicegroup_id].bezeichnung+" f&uuml;r den "+allEvents[b].startdate.toDateEn(true).toStringDe(true),f.join(""),550,450);g=this;_checkVorschlagen(h,j,i);_checkZusagen(h,j,i);_checkAbsagen(h,j,i);this._renderAuslastung(b,
d);_checkEMail();_completePersonInfo(h.cdb_person_id);j?$("#InputName").focus():$("#InputNameSelect").blur();j&&this.autocompletePersonSelect("#InputName",false,function(l,m){l='<select id="InputNameSelect" class="cdb-input"><option value="'+m.item.value+'">'+m.item.label+"</option></select>";l=l+'<input type="hidden" id="nameofadditionperson" name="UserBrowser" value="'+m.item.label+'"/>';$("#divinputname").html(l);j=false});$("#InputNameSelect").change(function(){if($("#InputNameSelect").val()==
-1){k.empty().remove();g.renderEditEventService(b,c,true)}else{_checkVorschlagen(h,j,i);_checkZusagen(h,j,i);_checkAbsagen(h,j,i);g._renderAuslastung(b,d);_checkEMail();_completePersonInfo($("#InputNameSelect").val())}});$("#cdb_dialog a").click(function(){if($(this).attr("id")=="showHistory")$("#divshowhistory").html(g.renderEntryHistory(b,h.service_id,h.counter,null,masterData.auth.leaderservice[d]||masterData.auth.admin));else if($(this).attr("id")=="mailPerson")$("#InputNameSelect").val()<=0?
alert("Bitte eine Person nehmen!"):g.mailPerson($("#InputNameSelect").val());else $(this).attr("id")=="editService"&&t.editService(d);return false});$("#in_edit input").click(function(){if($(this).attr("type")=="button")if(j&&$("#InputName").val()==""||!j&&$("#InputNameSelect").val()=="")alert("Bitte erst einen Namen aussuchen");else{obj={};obj.func="updateEventService";obj.id=h.id;h.valid_yn=0;if($(this).val()=="Vorschlagen"||$(this).val()=="Zusagen"){if(j)obj.name=$("#InputName").val();else{obj.cdb_person_id=
$("#InputNameSelect").val();masterData.service[d].cdb_gruppen_ids!=null&&$.each(masterData.service[d].cdb_gruppen_ids.split(","),function(m,n){groups[n]!=null&&$.each(groups[n],function(p,q){if(q.p_id==obj.cdb_person_id){obj.name=q.vorname+" "+q.name;return false}})});if(obj.name==null)obj.name=$("#nameofadditionperson").val()}if($(this).val()=="Zusagen"){obj.zugesagt_yn=1;if($("#InputNameSelect").val()==masterData.user_pid&masterData.service[d].allowtonotebyconfirmation_yn==1){var l=prompt("Hiermit verbindlich zusagen? Hier kannst Du noch eine Info angeben.",
"");if(l==null)return null;obj.reason=l}}else obj.zugesagt_yn=0}else if($(this).val()=="Absagen"){if($("#InputNameSelect").val()==masterData.user_pid||h.mailsenddate!=null){l=prompt("Wirklich absagen? Hier kannst Du noch einen Grund angeben.","");if(l==null)return null;obj.reason=l}obj.name=null;obj.cdb_person_id=null;obj.zugesagt_yn=0}k.html("<p><br/><b>Daten werden gespeichert...</b><br/><br/>");$.getJSON("index.php?q=churchservice/ajax",obj,function(m){k.dialog("close");if(m.result){m.eventservice.id==
obj.id?$.each(allEvents[b].services,function(n,p){if(p.id==obj.id)allEvents[b].services[n]=m.eventservice}):allEvents[b].services.push(m.eventservice);m.eventservice.id*1==churchInterface.lastLogId*1+1&&churchInterface.setLastLogId(m.eventservice.id);k.empty().remove();g.renderList(allEvents[b])}else{alert("Fehler beim Speichern: "+m);window.location.reload()}})}})};
ListView.prototype.showAuslastung=function(){var b=[],c={},e=0;$.each(allEvents,function(g,f){if(f.services!=null){e+=1;$.each(f.services,function(h,d){if(d.cdb_person_id!=null&&d.valid_yn==1)if(c[d.cdb_person_id]==null){h=[];h.counter=1;h.name=d.name;h.cdb_person_id=d.cdb_person_id;h.service_id=d.service_id;c[d.cdb_person_id]=h}else c[d.cdb_person_id].counter+=1})}});b.push("<h2>Dienste pro Event<h2/>");b.push("<table>");$.each(churchcore_sortData(c,"counter",true,false),function(g,f){b.push("<tr><td>"+
f.name+" ("+f.cdb_person_id+")<td>"+Math.round(f.counter/e*100)+"%")});b.push("</table>");form_showOkDialog("Anzeige der Auslastung der Mitarbeiter",b.join(""))};
ListView.prototype.renderEntryHistory=function(b,c,e,g,f,h){var d="";if(f==null)f=false;if(h==null)h=false;var j=false,i=null;$.each(churchcore_sortData(allEvents[b].services,"datum",false),function(k,l){if(l.service_id==c&&l.counter==e)if(g==null||l.datum.toDateEn()>=g){k="<tr><td>";if(l.zugesagt_yn==0)k+='<font style="color:red">';if(l.name!=null&&l.name!="")k+=l.name;else if(i!=null)k=k+'<font style="text-decoration: line-through">'+i+"</font>";else k+="?";if(l.zugesagt_yn==0)k+="</font>";i=l.name;
if(f&&l.reason!=null&&h)k=k+'<br/><div><i>"'+l.reason.trim(15)+'"</i></small>';k=k+"<td>"+l.datum.toDateEn().toStringDe(true)+"<td>";k+=h?l.user.trim(15):l.user;if(f&&l.reason!=null&&!h){k=k+"<td>"+l.reason;j=true}d=k+d}});if(d!=""){b='<div><small><table class="table table-condensed"><tr><th>Name<th>Wann<th>Von wem';if(j)b+="<th>Notiz";d=b+d+"</table></small></div>"}return d};
function tryToGetReason(b,c,e){var g=null;$.each(churchcore_sortArray(b.services,"datum",true),function(f,h){if(h.service_id==c){if(h.id==e)return false;if(h.reason!=null)g=h.reason}});return g}a=ListView.prototype;
a.getPersonAuslastung=function(b,c,e){var g={};g.letzter_einsatz_davor=null;g.naechster_einsatz_danach=null;g.monate={};var f=null;$.each(this.getData(true),function(h,d){if(d.services!=null){_count_person=_service_besetzt=false;$.each(d.services,function(i,k){if(k.valid_yn==1&&k.cdb_person_id!=null){_service_besetzt=true;if((c==null||masterData.service[c].servicegroup_id==masterData.service[k.service_id].servicegroup_id)&&k.cdb_person_id==b)_count_person=true}});h=e.monthDiff(d.startdate.toDateEn(false));
if(g.monate[h]==null){var j=[];j.person=0;j.events=0;g.monate[h]=j}if(_count_person){g.monate[h].person++;if(d.startdate.toDateEn()<e&&(g.letzter_einsatz_davor==null||g.letzter_einsatz_davor<d.startdate.toDateEn()))g.letzter_einsatz_davor=d.startdate.toDateEn();if(d.startdate.toDateEn()>e&&(g.naechster_einsatz_danach==null||g.naechster_einsatz_danach>d.startdate.toDateEn()))g.naechster_einsatz_danach=d.startdate.toDateEn()}if(_service_besetzt){f!=d.startdate.substr(0,10)&&g.monate[h].events++;f=d.startdate.substr(0,
10)}}});return g};
a.renderPersonAuslastung=function(b,c,e,g){if(g==null)g=false;if(b==null)return"";for(var f=allEvents[c].startdate.toDateEn(),h=this.getPersonAuslastung(b,e,f),d="",j="",i=-2,k=0,l=0;i<=1;){if(i==0)d+="|";if(i==0)j+="<";var m="white";if(h.monate[i]!=null&&h.monate[i].events>0){var n=h.monate[i].person/h.monate[i].events;m=n>0.5?"red":n>0.3?"yellow":"green";k+=n;j=j+h.monate[i].person+""}else j+="0";d=d+'<img src="'+masterData.modulespath+"/images/box_"+m+'.png"/>';if(i==0)d+="|";if(i==0)j+=">";j+=
" ";i++;l++}var p="";g&&$.each(this.getData(true),function(q,o){o.services!=null&&o.startdate.toDateEn(false).toStringEn(false)==f.toStringEn(false)&&$.each(churchcore_sortArray(o.services,"datum",true),function(u,r){if(r.cdb_person_id!=null&&r.cdb_person_id==b)if(o.id!=c||r.service_id!=e){if(p!="")p+=" und ";p=p+" "+masterData.service[r.service_id].bezeichnung+" ";if(r.zugesagt_yn==1&&r.valid_yn==1)p+="zugesagt";else if(r.zugesagt_yn==0&&r.valid_yn==1)p+="angefragt";else{p+="abgesagt";u=tryToGetReason(o,
r.service_id,r.id);if(u!=null)p=p+" (<i>"+u+"</i>)"}p=p+" f&uuml;r "+o.startdate.toDateEn(true).toStringDeTime()+" "+o.bezeichnung;return false}})});if(j!=""){j='<a href="#" id="personHistory">'+j+"</a>";g=Math.round(100*k/l);if(g>100)g=100;j=j+"&nbsp; ("+g+"%)";if(h.letzter_einsatz_davor!=null)j=j+"<br/>Letzter Einsatz: "+h.letzter_einsatz_davor.toStringDe(true);if(h.naechster_einsatz_danach!=null)j=j+"<br/>N&auml;chster Einsatz: "+h.naechster_einsatz_danach.toStringDe(true);if(p!="")j=j+"<p><small>Andere Anfragen an diesem Tag:<br>"+
p+"!</small>";h=personIsAbsent(b,f);if(h!=null){j=j+'<p><small style="color:red">Achtung: Person abwesend bis '+(h.enddate.getHours()==0?h.enddate.toStringDe(false):h.enddate.toStringDe(true))+" ("+masterData.absent_reason[h.absent_reason_id].bezeichnung;if(h.bezeichnung!="")j=j+" - "+h.bezeichnung;j+=")</small>"}return'<font title="Auslastung je Monat innerhalb der Dienstgruppe, aktueller Eventmonat ist mit <> markiert">'+j+"</font>"}return""};
a.getEventService=function(b,c){var e=null;$.each(allEvents[b].services,function(g,f){if(f.id==c&&f.valid_yn!=0){e=f;return false}});return e};
a.renderTooltip=function(b){var c=b.attr("tooltip"),e=b.parents("tr").attr("id"),g=bin_ich_admin(allEvents[e].admin);if(b.hasClass("file"))return this.renderTooltipForFiles(b,null,allEvents[e].files[c],masterData.auth.admin||masterData.auth.leaderservice[h.service_id]||g);else{var f=c.substr(c.indexOf("_")+1,99);c="";var h=this.getEventService(e,f);if(h.name!=null)c="<h4>"+h.name+"</h4>";var d=false;if(masterData.service[h.service_id].cdb_gruppen_ids!=null)d=this_object.getMemberOfOneGroup(masterData.service[h.service_id].cdb_gruppen_ids,
[h.cdb_person_id]);if(b.attr("member")!=null){c=h.zugesagt_yn==1?c+'<font style="color:green">Zusage am '+h.datum.toDateEn().toStringDe()+"</font>":h.name!=null?c+'<font style="color:red">Anfrage vom '+h.datum.toDateEn().toStringDe()+"</font>":c+'<font style="color:red">Offen seit '+h.datum.toDateEn().toStringDe()+"</font>";if(h.mailsenddate!=null)c=c+'&nbsp;<span title="Letzte Erinnerung gesendet am '+h.mailsenddate.toDateEn(true).toStringDe(true)+'">'+this_object.renderImage("email",12)+"</span>";
c+="<br/>"}if(d!=false)if(d.imageurl!=null)c='<div style="float:right">&nbsp;<img src="'+masterData.files_url+"/fotos/"+d.imageurl+'" style="max-width:70px" width="70"></div>'+c;f=this.getEventService(e,f).cdb_person_id;if(masterData.auth.admin||masterData.auth.leaderservice[h.service_id]||g){f=this.renderPersonAuslastung(f,e,h.service_id);if(f!="")c=c+"Auslastung: "+f}if(c!=""){c="<div>"+c+"</div>";c+='<div style="clear:both"></div>'}if(b.attr("history")||masterData.auth.viewhistory||g)c=c+"<p>"+
this.renderEntryHistory(e,h.service_id,h.counter,null,masterData.auth.leaderservice[h.service_id]||masterData.auth.admin||g,true);if(c!=""){b=masterData.service[h.service_id].bezeichnung;if(masterData.service[h.service_id].notiz!="")b=b+" <small> ("+masterData.service[h.service_id].notiz+")</small></p>";return[c,b]}}return null};a.tooltipCallback=function(b,c){if(c.find("#file").val()){var e=c.parents("tr.data").attr("id");return this.tooltipCallbackForFiles(b,c,allEvents,e)}};
a.countActiveServices=function(b,c){var e=0;b.services!=null&&$.each(b.services,function(g,f){if(f.service_id==c&&f.valid_yn==1&&f.name!=null)e+=1});return e};
a.editService=function(b,c){var e=$.extend({},masterData.service[b]);if(b==null){e=[];e.sortkey=0}e.gruppen=[];e.tags=[];if(e.cdb_gruppen_ids!=null)e.gruppen=e.cdb_gruppen_ids.split(",");if(e.cdb_tag_ids!=null)e.tags=e.cdb_tag_ids.split(",");if(e.servicegroup_id==null)e.servicegroup_id=c;if(masterData.groups==null){var g=form_showCancelDialog("Gruppendaten werden geladen...","Bitte warten..");churchInterface.jsendRead({func:"getGroupAndTagInfos"},function(h,d){if(h){masterData.groups=d.groups;if(masterData.groups==
null)masterData.groups=[];masterData.tags=d.tags;t.editService(b,c)}else{alert("Fehler: "+d);masterData.groups="null"}g.dialog("close")})}else{var f=new CC_Form(b!=null?"Service editieren":"Service erstellen",e);f.addInput({label:"Bezeichnung",cssid:"bezeichnung",required:true});f.addInput({label:"Notiz",cssid:"notiz",required:false});f.addSelect({label:"Servicegruppe",cssid:"servicegroup_id",data:masterData.servicegroup,func:function(h){return masterData.auth.editgroup!=null&&masterData.auth.editgroup[h.id]!=
null}});f.addHtml('<div class="control-group"><label class="control-label">Gruppenzuordnungen</label>');f.addHtml('<div class="controls" id="gruppen">');f.addHtml("</div></div>");f.addHtml('<div class="control-group"><label class="control-label">Tag-Zuordnungen</label>');f.addHtml('<div class="controls" id="tags">');f.addHtml("</div></div>");f.addCheckbox({controlgroup_start:true,label:"Sende Dienstanfragen per E-Mail",cssid:"sendremindermails_yn"});f.addCheckbox({controlgroup_end:true,label:"Die Dienstanfrage kann auch bei Zusage kommentiert werden",
cssid:"allowtonotebyconfirmation_yn"});f.addInput({label:"Sortierungsnummer (sortkey)",cssid:"sortkey",required:true});f.addHtml('<p class="pull-right"><small>Id: '+b);g=form_showDialog("Service editieren",f.render(false,"horizontal"),600,580);g.dialog("addbutton","Speichern",function(){obj=f.getAllValsAsObject();obj.cdb_gruppen_ids=e.gruppen.join(",");obj.cdb_tag_ids=e.tags.join(",");obj.cdb_gruppen_ids==""&&delete obj.cdb_gruppen_ids;obj.cdb_tag_ids==""&&delete obj.cdb_tag_ids;if(obj.cdb_gruppen_ids==
null&&obj.cdb_tag_ids!=null){alert("Es wurde mindestens ein Tag angegeben ohne eine Gruppe. Tags wirken nur innerhalb von Gruppen. Bitte erst Gruppe auswaehlen!");return false}obj.id=b;if(obj!=null){obj.func="editService";churchInterface.jsendWrite(obj,function(){window.location.reload()})}});b!=null&&masterData.auth.editgroup!=null&&masterData.auth.editgroup[c]&&g.dialog("addbutton","L\u00f6schen",function(){if(confirm("Wirklich '"+masterData.service[b].bezeichnung+"' entfernen? Alle dazu vorhandenen Zuordnungen werden auch unwiderruflich entfernt!")){g.dialog("close");
churchInterface.jsendWrite({func:"deleteService",id:b},function(h,d){h?window.location.reload():alert("Fehler: "+d)})}return false});g.dialog("addbutton","Abbrechen",function(){$(this).dialog("close")});form_renderLabelList(e,"gruppen",masterData.groups);form_renderLabelList(e,"tags",masterData.tags)}};
a.renderAddServiceToServicegroup=function(b,c){var e=[];e.push('<div id="in_edit"><table class="table table-condensed"><tr><th><input type="checkbox" id="cb_enableAll"/><th>Service');masterData.auth.editgroup!=null&&masterData.auth.editgroup[c]&&e.push('<th width="25px">');var g=bin_ich_admin(b.admin);$.each(this.getAdditionalServicesToServicegroup(b,c,g),function(h,d){e.push('<tr><td><input type="checkbox" '+d.checked+' id="on_'+d.id+'"/><td><p>'+masterData.service[d.id].bezeichnung);masterData.service[d.id].notiz!=
""&&e.push("&nbsp; <small>("+masterData.service[d.id].notiz+")</small>");masterData.auth.editgroup!=null&&masterData.auth.editgroup[c]&&e.push("<td>"+form_renderImage({cssid:"editService",data:[{name:"service-id",value:d.id}],src:"options.png",width:20}))});masterData.auth.editgroup!=null&&masterData.auth.editgroup[c]&&e.push('<tr><td><td><i><a href="#" class="newService">Neuen Service erstellen</a></i><td><td>'+form_renderImage({cssid:"addService",src:"plus.png",width:20}));e.push("</table></div>");
var f=this.showDialog("Welcher Service soll ver&auml;ndert werden?",e.join(""),600,580,{Speichern:function(){obj={};auto=[];obj.func="addOrRemoveServiceToEvent";obj.id=b.id;var h=0;$("#in_edit input:checkbox").each(function(){if($(this).attr("id").indexOf("on_")==0){var d=$(this).attr("id").substr(3,99);obj["col"+h]=d;obj["val"+h]=$(this).attr("checked");obj["count"+h]=$("#service_"+d).val();$("#auto_"+d).attr("checked")&&auto.push(d);h++}});f.html("<p><br/><b>Daten werden gespeichert...</b><br/><br/>");
$.getJSON("index.php?q=churchservice/ajax",obj,function(d){d!="ok"?alert("Fehler beim Speichern: "+d):cs_loadEventData(b.id,function(){f.dialog("close");this_object.renderList(allEvents[b.id])})})},Abbruch:function(){$(this).dialog("close")}});f.find("input:checkbox").change(function(){if($(this).attr("id")=="cb_enableAll"){var h=this.checked;f.find("input:checkbox").each(function(){if($(this).attr("id").indexOf("on_")==0){var j=$(this).attr("id").substr(3,99);if(h==true||t.countActiveServices(b,
j)==0)if(this.checked=h){$("#service_"+j).removeAttr("disabled");$("#service_"+j).val()==0&&$("#service_"+j).val(1);$("#auto_"+j).removeAttr("disabled")}else{$("#service_"+j).attr("disabled","disabled");$("#service_"+j).val()>0&&$("#service_"+j).val(0);$("#auto_"+j).attr("disabled","disabled")}}})}else if($(this).attr("id").indexOf("on_")==0){h=this.checked;var d=$(this).attr("id").substr(3,99);if(h){$("#service_"+d).removeAttr("disabled");$("#service_"+d).val()==0&&$("#service_"+d).val(1);$("#auto_"+
d).removeAttr("disabled")}else if(t.countActiveServices(b,d)>0){$(this).attr("checked",true);alert("Service kann nicht entfernt werden, da noch Personen angefragt sind bzw. zugesagt haben.")}else{$("#service_"+d).attr("disabled","disabled");$("#service_"+d).val()>0&&$("#service_"+d).val(0);$("#auto_"+d).attr("disabled","disabled")}}});f.find("input:text").change(function(){if(this.value==0){alert("Es muss mindestens ein Services angegeben werden. Wenn der Dienst nicht notwendig ist, bitte mit der Checkbox ausschalten.");
this.value=1}else{var h=t.countActiveServices(b,$(this).attr("id").substr(8,99));if(h>this.value){this.value=h;alert("Es sind schon "+h+" Personen angefragt! Bitte Anfragen absagen um den Wert hier zu reduzieren.")}}});f.find("#addService").click(function(){t.editService(null,c);return false});f.find("a.newService").click(function(){t.editService(null,c);return false});f.find("#editService").click(function(){t.editService($(this).attr("data-service-id"),c);return false})};
a.sendEMailToEvent=function(b){var c=this,e=[],g=[];$.each(b.services,function(h,d){if(d.valid_yn==1&&d.cdb_person_id!=null)g[masterData.service[d.service_id].servicegroup_id]=true});if(g.length==0)alert("Um eine E-Mail zu senden, muss mindestens eine bekannte Person angefragt sein.");else{e.push('<form class="form-h_orizontal">');e.push("<legend>Schreibe E-Mail an angefragte Mitarbeiter</legend>");$.each(c.sortMasterData(masterData.servicegroup),function(h,d){if(g[d.id]){c.isLeaderOfServiceGroup(d.id);
e.push(form_renderCheckbox({label:d.bezeichnung,cssid:"checkSG"+d.id,controlgroup_class:"",checked:c.isLeaderOfServiceGroup(d.id)}))}});e.push(form_renderInput({label:"Betreff",value:"Infos zum "+b.bezeichnung+" am "+b.startdate.toDateEn(true).toStringDe(true),cssid:"betreff",type:"xlarge"}));var f='<div id="inhalt" class="well" contenteditable="true">';if(masterData.settings.signature!=null)f+=masterData.settings.signature;f+="</div>";e.push(form_renderLabel(f,"Inhalt"));if(masterData.settings.sendBCCMail==
null)masterData.settings.sendBCCMail=1;e.push(form_renderCheckbox({label:"Eine Kopie an mich senden",cssid:"sendBCCMail",checked:masterData.settings.sendBCCMail==1}));e.push("</form");f=c.showDialog("E-Mail an Mitarbeiter",e.join(""),600,600,{Absenden:function(){var h={},d="";$.each(b.services,function(j,i){if(i.valid_yn==1&&i.cdb_person_id!=null&&$("#checkSG"+masterData.service[i.service_id].servicegroup_id).attr("checked"))d=d+i.cdb_person_id+","});if(d=="")alert("Bitte eine Dienstgruppe markieren!");
else{masterData.settings.sendBCCMail=$("#sendBCCMail").attr("checked")?1:0;if(masterData.settings.sendBCCMail==1)d=d+masterData.user_pid+",";churchInterface.jsonWrite({func:"saveSetting",sub:"sendBCCMail",val:masterData.settings.sendBCCMail});d+="-1";h.ids=d;h.betreff=$("#betreff").val();h.inhalt=CKEDITOR.instances.inhalt.getData();h.domain_id=b.id;h.func="sendEMailToPersonIds";churchInterface.jsendWrite(h,function(j,i){j?alert("EMail wurde gesendet. "+(i!="ok"?i:"")):alert("Problem: "+i)},null,false);
$(this).dialog("close")}},Abbrechen:function(){$(this).dialog("close")}});form_implantWysiwygEditor("inhalt",false,false);f.find("#inhalt").focus();f.find("a").click(function(){if($(this).attr("id")=="Vorname"||$(this).attr("id")=="Nachname"){$("#inhalt").insertAtCaret("["+$(this).attr("id")+"]");return false}})}};
a.editNote=function(b){var c=this,e=[];e.push("<br/>"+c.renderTextarea("infos","Weitere Infos zum Event:<br/>",b.special,35,8));c.showDialog("Weitere Infos editieren",e.join(""),400,400,{Speichern:function(){var g={};g.func="saveNote";var f=$("#infos").val();g.text=f;g.event_id=b.id;churchInterface.jsonWrite(g,function(h){if(h){b.special=f;c.renderList(b)}});$(this).dialog("close")},Abbrechen:function(){$(this).dialog("close")}})};
a.attachFile=function(b){var c=this,e=[],g=false,f=[],h=b.startdate.toDateEn(false).toStringEn(false);$.each(allEvents,function(i,k){b.id!=k.id&&k.startdate.toDateEn(false).toStringEn(false)==h&&b.category_id==k.category_id&&f.push(k.id)});e.push("<legend>1. Option zum Hochladen der Datei</legend>");if(f.length>0){g=masterData.settings.file_attachToAllEvents==1;e.push(form_renderCheckbox({cssid:"file_attachToAllEvents",checked:g,label:"Datei automatisch an alle Events des Tages mit gleicher Kategorie anh&auml;ngen"}))}var d=
[];b.services!=null&&$.each(b.services,function(i,k){if(k.valid_yn==1&&k.cdb_person_id!=null)d[masterData.service[k.service_id].servicegroup_id]=true});if(d.length>0){e.push("<p>Folgende Dienstgruppen per E-Mail &uuml;ber die neue Datei informieren:");$.each(c.sortMasterData(masterData.servicegroup),function(i,k){if(d[k.id]){g=masterData.settings["file_informServiceGroup"+k.id]==1;e.push(form_renderCheckbox({label:k.bezeichnung,controlgroup:false,checked:g,cssid:"file_informServiceGroup"+k.id}))}});
e.push('<p>Hier kann ein Kommentar angeben werden:<div class="well" contenteditable="true" id="editor">&nbsp;</div>')}if(e.length==1){e=[];e.push("<legend>Datei ausw&auml;hlen</legend>")}else e.push("<legend>2. Datei ausw&auml;hlen</legend>");e.push('<p><div id="upload_button">Nochmal bitte...</div><p>');var j=c.showDialog("Datei zum Event "+b.bezeichnung+" hochladen",e.join(""),520,500,{Abbrechen:function(){$(this).dialog("close")}});form_implantWysiwygEditor("editor",null,true);j.find("input:checkbox").change(function(){masterData.settings[$(this).attr("id")]=
$(this).attr("checked")=="checked"?1:0;churchInterface.jsonWrite({func:"saveSetting",sub:$(this).attr("id"),val:$(this).attr("checked")=="checked"?1:0})});new qq.FileUploader({element:document.getElementById("upload_button"),action:"?q=churchservice/uploadfile",params:{domain_type:"service",domain_id:b.id},multiple:false,debug:true,onComplete:function(i,k,l){if(l.success){var m=c.showDialog("Bitte warten","Datei wird gespeichert...",300,300),n="";if(CKEDITOR.instances.editor!=null)n=CKEDITOR.instances.editor.getData();
window.setTimeout(function(){masterData.settings.file_attachToAllEvents==1&&f.length>0&&churchInterface.jsendWrite({func:"copyFile",id:l.id,domain_id:f.join(",")},function(q,o){q||alert("Probleme beim Kopieren der Daten auf die anderen Events: "+o)},false);var p=[];$.each(c.sortMasterData(masterData.servicegroup),function(q,o){d[o.id]&&masterData.settings["file_informServiceGroup"+o.id]==1&&p.push(o.id)});if(p.length>0){f.push(b.id);$.each(f,function(q,o){if(masterData.settings.file_attachToAllEvents==
1||o==b.id){q=allEvents[o];o={};var u=[];$.each(q.services,function(r,s){s.valid_yn==1&&s.cdb_person_id!=null&&masterData.service[s.service_id]!=null&&d[masterData.service[s.service_id].servicegroup_id]&&masterData.settings["file_informServiceGroup"+masterData.service[s.service_id].servicegroup_id]==1&&u.push(s.cdb_person_id)});if(u.length>0){o.ids=u.join(",");o.betreff="Neue Datei zum Event "+q.bezeichnung+" "+q.startdate.toDateEn(true).toStringDe(true);o.inhalt="<h3>Hallo [Vorname]!</h3><p>f&uuml;r <i>"+
q.bezeichnung+"</i> wurde eine neue Datei hochgeladen. Du wirst informiert, da Du zum Dienst angefragt bist.";if(n!=null&&n!="")o.inhalt=o.inhalt+"<p><i>"+n+"</i></p>";o.inhalt=o.inhalt+'<ul><li><a href="'+masterData.files_url+"/files/service/"+q.id+"/"+l.filename+'">'+l.bezeichnung+"</a></ul>";o.domain_id=q.id;o.usetemplate="true";o.func="sendEMailToPersonIds";churchInterface.jsendWrite(o,function(r,s){r?alert("E-Mail wurde gesendet. "+(s!="ok"?s:"")):alert("Problem beim Senden: "+s)},null,false)}}})}j.dialog("close");
cs_loadFiles(function(){m.dialog("close")})},100)}else alert("Sorry, es ist ein Fehler beim Hochladen aufgetreten!")}})};
a.renderFiles=function(){var b=this;if(allEvents!=null)masterData.auth.write?b.renderFilelist("Dateien zum Event:",allEvents,null,function(e,g){delete allEvents[g].files[e];b.renderList(allEvents[g])}):b.renderFilelist("Dateien zum Event:",allEvents);var c=false;$("#cdb_content span[tooltip].file").hover(function(){c=true;this_object.prepareTooltip($(this))},function(){c=false;window.setTimeout(function(){c||this_object.clearTooltip()},100)})};
a.addFurtherListCallbacks=function(b){t=this;if(b==null)b="#cdb_content";t.renderFiles();$(".hover").hover(function(){$("#headerspan"+$(this).attr("id").substr(6,99)).fadeIn("fast",function(){})},function(){$("#headerspan"+$(this).attr("id").substr(6,99)).fadeOut("fast")});$(b+" a").click(function(){if($(this).attr("id")==null)return true;else if($(this).attr("id").indexOf("editEvent")==0)t.renderEditEvent(allEvents[$(this).attr("id").substr(9,99)]);else if($(this).attr("id").indexOf("mailEvent")==
0)t.sendEMailToEvent(allEvents[$(this).attr("id").substr(9,99)]);else if($(this).attr("id").indexOf("filterMyAdmin")==0){if(t.filter["filterMeine Filter"]==2)delete t.filter["filterMeine Filter"];else t.setFilter("filterMeine Filter",2);t.renderView()}else if($(this).attr("id").indexOf("editNote")==0)t.editNote(allEvents[$(this).attr("id").substr(8,99)]);else if($(this).attr("id").indexOf("attachFile")==0)t.attachFile(allEvents[$(this).attr("id").substr(10,99)]);else if($(this).attr("id").indexOf("edit_es_")==
0)t.renderEditEventService($(this).attr("id").substr(8,99),$(this).attr("eventservice_id"));else if($(this).attr("id").indexOf("addService")==0)t.renderAddServiceToServicegroup(allEvents[$(this).attr("event_id")],$(this).attr("servicegroup_id"),masterData.user_pid);else if($(this).attr("id").indexOf("addMoreCols")==0)t.addMoreCols();else if($(this).attr("id").indexOf("delCol")==0){var c=$(this).attr("id").substr(6,99);masterData.settings["viewgroup"+c]=0;churchInterface.jsonWrite({func:"saveSetting",
sub:"viewgroup"+c,val:0});t.renderList()}})};
a.addMoreCols=function(){var b=[],c=this;b.push("<legend>Auswahl der Servicegruppen</legend>");$.each(churchcore_sortData(masterData.servicegroup,"sortkey"),function(e,g){if(masterData.auth.viewgroup[g.id]!=null)b.push(form_renderCheckbox({cssid:"viewgroup"+g.id,label:g.bezeichnung,controlgroup:false,checked:masterData.settings["viewgroup"+g.id]==null||masterData.settings["viewgroup"+g.id]==1}))});this.showDialog("Anpassen der Tabelle",b.join(""),400,400,{Schliessen:function(){$(this).dialog("close")}}).find("input:checkbox").click(function(){masterData.settings[$(this).attr("id")]=
$(this).attr("checked")=="checked"?1:0;churchInterface.jsonWrite({func:"saveSetting",sub:$(this).attr("id"),val:masterData.settings[$(this).attr("id")]});c.renderList()})};
a.renderFilter=function(){var b=[];b.push('<div id="divviewmap" class="new-entry"></div>');b.push('<div id="divaddfilter" style="width:100%;" class="new-entry"></div>');var c=new CC_Form;c.setHelp("ChurchService-Filter");c.addHtml('<div id="dp_currentdate" style=""></div>');b.push('<div id="dp_currentdate" style=""></div>');b.push('<p> &nbsp; <small><img src="system/assets/img/red_dot.png"/> Abwesenheit  &nbsp; <img src="system/assets/img/yellow_dot.png"/> Angefragt  &nbsp; <img src="system/assets/img/green_dot.png"/> Zugesagt</small>');var e=
[];form_addEntryToSelectArray(e,1,"Meine Dienste filtern");_drin=false;allEvents!=null&&$.each(allEvents,function(g,f){if(bin_ich_admin(f.admin)){_drin=true;return false}});_drin&&form_addEntryToSelectArray(e,2,"Meine Events filtern");c.addSelect({data:e,label:"Meine Filter",selected:this.filter["filterMeine Filter"],freeoption:true,cssid:"filterMeine Filter",type:"medium"});this.name!="FactView"&&c.addSelect({data:this.sortMasterData(masterData.servicegroup),label:"Dienstgruppen",selected:this.filter.filterDienstgruppen,
freeoption:true,cssid:"filterDienstgruppen",type:"medium",func:function(g){return masterData.auth.viewgroup!=null&&masterData.auth.viewgroup[g.id]}});c.addHtml('<div id="filterKategorien"></div>');c.addCheckbox({cssid:"searchChecked",label:"markierte"});b.push(c.render(true));b.push('<div id="cdb_filtercover"></div>');$("#cdb_filter").html(b.join(""));if(this.filter.filterKategorien!=null){typeof this.filter.filterKategorien=="string"&&this.makeFilterCategories(masterData.settings.filterCategory);
this.filter.filterKategorien.render2Div("filterKategorien",{label:"Kategorien"})}$.each(this.filter,function(g,f){$("#"+g).val(f)});filter=this.filter;this.implantStandardFilterCallbacks(this,"cdb_filter");this.renderCalendar()};
a.renderCalendar=function(){var b=this;$("#dp_currentdate").datepicker({dateFormat:"dd.mm.yy",showButtonPanel:true,dayNamesMin:dayNamesMin,monthNames:monthNames,currentText:"Heute",firstDay:1,beforeShowDay:function(c){var e=(new Date).toStringEn()==c.toStringEn(),g=false,f=false;$.each(allEvents,function(j,i){if(c.sameDay(i.startdate.toDateEn(false))){e=true;i.services!=null&&$.each(i.services,function(k,l){if(l.valid_yn==1&&l.cdb_person_id==masterData.user_pid){if(l.zugesagt_yn==1)f=true;else g=
true;return false}})}});var h="";if(g)h="angefragt";else if(f)h="zugesagt highlight";var d=false;allPersons[masterData.user_pid]!=null&&allPersons[masterData.user_pid].absent!=null&&$.each(allPersons[masterData.user_pid].absent,function(j,i){if(i!=null&&i.startdate.withoutTime()<=c&&i.enddate>=c){d=true;return false}});if(d)h+=" absent";return[e,h]},onSelect:function(c){b.currentDate=c.toDateDe();b.listOffset=0;if(b.filter.searchEntry!=null){b.filter.searchEntry="";b.renderFilter()}b.renderList();
b.addAbsentButton()},onChangeMonthYear:function(c,e){var g=new Date;if(b.allDataLoaded)b.currentDate=g.getFullYear()==c&&g.getMonth()+1==e?g.withoutTime():new Date(c,e-1);b.listOffset=0;b.addAbsentButton();b.renderTimer!=null&&clearTimeout(b.renderTimer);b.renderTimer=window.setTimeout(function(){b.renderTimer=null;b.renderList()},150)}});$("#dp_currentdate").datepicker($.datepicker.regional.de);$("#dp_currentdate").datepicker("setDate",b.currentDate.toStringDe());b.addAbsentButton()};
a.addAbsentButton=function(){var b=this;window.setTimeout(function(){if($("#btn_abwesenheit").length==0){$("#dp_currentdate div.ui-datepicker-buttonpane").append('<button type="button" id="btn_abwesenheit" class="ui-datepicker-current ui-state-default ui-priority-secondary ui-corner-all">Abwesenheit bearbeiten</button>');$("#btn_abwesenheit").hover(function(){$(this).addClass("ui-state-hover")},function(){$(this).removeClass("ui-state-hover")});$("#btn_abwesenheit").click(function(){b.editAbsent()})}},
1)};
a.editAbsent=function(b,c,e){var g=this,f=[],h={};if(e==null)e=true;h.startdate=g.currentDate.toStringDe(false).toDateDe(false);h.enddate=new Date(h.startdate);if(e)h.enddate.addDays(7);else{h.startdate.setHours(10);h.enddate.setHours(20)}if(b==null){b=masterData.user_pid;c=masterData.user_name}if(allPersons[b]==null)allPersons[b]={};var d=masterData.auth.manageabsent?new CC_Form('Neue Abwesenheit f&uuml;r <a href="#" id="changePerson"><font style="text-decoration:underline">'+c+"</font> <small>(&auml;ndern)</small></a>"):new CC_Form("Neue Abwesenheit f&uuml;r "+
c);d.addHtml("<table><tr><td>");d.addInput({cssid:"inputStartdate",label:"Von",c_ontrolgroup:false,separator:"&nbsp;",value:h.startdate.toStringDe(),type:"small"});d.addHtml('<div id="dp_startdate" style="position:absolute;background:#e7eef4;z-index:12001;"/>');if(e!=true){d.addHtml("<td>");var j=_getHoursArray();d.addSelect({data:j,cssid:"inputStarthour",label:"Stunde",selected:h.startdate.getHours(),htmlclass:"input-mini"});d.addHtml("<td>");var i=_getMinutesArray();d.addSelect({data:i,label:"Minute",
cssid:"inputStartminutes",selected:h.startdate.getMinutes(),type:"mini"});d.addHtml("<td>")}d.addHtml("<td>");d.addInput({cssid:"inputEnddate",label:"Bis",c_ontrolgroup:false,separator:"&nbsp;",value:h.enddate.toStringDe(),type:"small"});d.addHtml('<div id="dp_enddate" style="position:absolute;background:#e7eef4;z-index:12001;"/>');d.addHtml("<td>");if(e!=true){d.addSelect({data:j,cssid:"inputEndhour",label:"Stunde",selected:h.enddate.getHours(),htmlclass:"input-mini"});d.addHtml("<td>");d.addSelect({data:i,
label:"Minute",cssid:"inputEndminutes",selected:h.enddate.getMinutes(),type:"mini"});d.addHtml("<tr><td colspan=2>")}d.addSelect({data:churchcore_sortData(masterData.absent_reason,"sortkey"),label:"Grund",cssid:"inputAbsentReason",type:"medium"});d.addHtml("<td colspan=2>");d.addInput({data:masterData.absent_reason,label:"Kommentar",cssid:"inputBezeichnung",type:"medium"});d.addHtml("<td>");d.addHtml("<tr><td>");d.addCheckbox({label:"Ganzt&auml;gig",checked:e,cssid:"wholeday"});d.addHtml("<tr><td colspan=4>");
d.addLink("","addabsent","Abwesenheit eintragen");d.addHtml("</table>");f.push(d.render(false,"inline"));if(allPersons[b].absent!=null){f.push("<legend>Bereits eingetragene Abwesenheiten</legend>");f.push('<div style="max-height:180px; overflow-y:auto; overflow-x:auto">');f.push('<table class="table table-condensed"><tr><th>Datum<th>Grund<th>Kommentar<th>');var k={};$.each(churchcore_sortData(allPersons[b].absent,"startdate",true),function(m,n){n.startdate.getHours()==0&&n.enddate.getHours()==0?f.push("<tr><td>"+
n.startdate.toStringDe(false)+" - "+n.enddate.toStringDe(false)):f.push("<tr><td>"+n.startdate.toStringDe(true)+" - "+n.enddate.toStringDe(true));f.push("<td>"+masterData.absent_reason[n.absent_reason_id].bezeichnung);f.push("<td><small>"+(n.bezeichnung!=null?n.bezeichnung:"")+"</small>");f.push('<td><a href="#" id="delabsent_'+n.id+'">'+g.renderImage("trashbox")+"</a>");if(k[n.startdate.getFullYear()]==null)k[n.startdate.getFullYear()]={};if(k[n.startdate.getFullYear()][n.absent_reason_id]==null)k[n.startdate.getFullYear()][n.absent_reason_id]=
0;k[n.startdate.getFullYear()][n.absent_reason_id]=k[n.startdate.getFullYear()][n.absent_reason_id]+(n.enddate-n.startdate)/1E3/24/60/60+1});f.push("</table>");if(masterData.auth.manageabsent){f.push("<p><small><i>Summe:</i><br/>");$.each(k,function(m,n){f.push(m+": ");$.each(n,function(p,q){f.push(masterData.absent_reason[p].bezeichnung+": "+q+"  ")});f.push("<br/>")});f.push("</small></p>")}f.push("</div>")}var l=this.showDialog("Abwesenheiten bearbeiten",f.join(""),600,580,{Schliessen:function(){$(this).dialog("close")}});
$("#inputStartdate").click(function(){g.implantDatePicker("startdate",h.startdate.toStringDe(),function(m){h.startdate=m.toDateDe();$("#inputStartdate").val(m);h.enddate=new Date(h.startdate);h.enddate.addDays(7);$("#inputEnddate").val(h.enddate.toStringDe())})});$("#inputEnddate").click(function(){g.implantDatePicker("enddate",h.enddate.toStringDe(),function(m){h.enddate=m.toDateDe();$("#inputEnddate").val(m)})});l.find("#inputStarthour").change(function(){console.log($("#inputStarthour").val());
l.find("#inputEndhour").val($(this).val()+1)});l.find("#wholeday").change(function(){l.dialog("close");g.editAbsent(b,c,$(this).attr("checked")=="checked")});l.find("a").click(function(){if($(this).attr("id").indexOf("addabsent")==0){h.func="addAbsent";h.person_id=b;h.absent_reason_id=$("#inputAbsentReason").val();h.bezeichnung=$("#inputBezeichnung").val();if(!e){h.startdate.setHours($("#inputStarthour").val());h.startdate.setMinutes($("#inputStartminutes").val());h.enddate.setHours($("#inputEndhour").val());
h.enddate.setMinutes($("#inputEndminutes").val())}l.html("Speichere Daten...");churchInterface.jsendWrite(h,function(q,o){if(q){if(allPersons[b].absent==null)allPersons[b].absent=[];h.id=o;allPersons[b].absent.push(h);l.dialog("close");g.editAbsent(b,c);g.renderCalendar()}else alert("Fehler beim Speichern: "+o)})}else if($(this).attr("id").indexOf("delabsent")==0){if(confirm("Abwesenheit wirklich entfernen?")){var m=$(this).attr("id").substr(10,99);l.html("Speichere Daten...");churchInterface.jsendWrite({func:"delAbsent",
id:m},function(q,o){if(q){$.each(allPersons[b].absent,function(u,r){r!=null&&r.id==m&&delete allPersons[b].absent[u]});l.dialog("close");g.editAbsent(b,c);g.renderCalendar()}else alert("Fehler beim Entfernen: "+o)})}}else if($(this).attr("id").indexOf("changePerson")==0){var n=[];n.push(form_renderInput({label:"Person angeben",cssid:"inputPerson"}));var p=g.showDialog("Andere Person ausw&auml;hlen",n.join(""),400,400,{Abbruch:function(){$(this).dialog("close")}});g.autocompletePersonSelect("#inputPerson",
false,function(q,o){p.dialog("close");l.dialog("close");g.editAbsent(o.item.value,o.item.label)})}return false})};
a.checkFilter=function(b){var c=this.filter;if(b==null)return false;if(b.bezeichnung==null)return true;if(this.currentDate>b.startdate.toDateEn())return false;if(this.filter.filterKategorien!=null&&this.filter.filterKategorien.filter(b.category_id))return false;if(this.filter["filterMeine Filter"]!=null)if(this.filter["filterMeine Filter"]==1){if(b.services==null)return false;var e=false;$.each(b.services,function(h,d){if(d.valid_yn==1&&d.cdb_person_id==masterData.user_pid){e=true;return false}});
if(!e)return false}else if(this.filter["filterMeine Filter"]==2)if(!bin_ich_admin(b.admin))return false;if(this.filter.searchEntry!=null){searchEntry=this.getFilter("searchEntry").toUpperCase();if(searchEntry.indexOf("#")==0)return searchEntry=="#"+b.id?true:false;var g=searchEntry.split(" "),f=true;$.each(g,function(h,d){dabei=false;if(d!=""){if(b.bezeichnung.toUpperCase().indexOf(searchEntry)>=0||b.id==d)dabei=true;b.services!=null&&$.each(b.services,function(j,i){if(i.name!=null&&i.valid_yn==1&&
i.name.toUpperCase().indexOf(d)>=0)dabei=true})}if(!dabei)return f=false});if(!f)return false}if(c.searchChecked!=null&&b.checked!=true)return false;return true};function _renderDetails(b){$("#detailTD"+b).html("Rendern...")}ListView.prototype.renderEntryDetail=function(){};ListView.prototype.renderEditEntry=function(){};
