(function(c){function o(){PersonView.call(this);this.name="StatisticView"}Temp.prototype=PersonView.prototype;o.prototype=new Temp;statisticView=new o;o.prototype.renderMasterDataStatistic=function(b,h,j){this_object=this;rows=[];desc=masterData.masterDataTables[h];res={};var m=0;c.each(allPersons,function(g,a){if(this_object.checkFilter(a)){if(res[a[j]]==null)res[a[j]]=0;res[a[j]]+=1;m++}});var e=[];rows.push('<small><table cellpadding="2"');var f=churchcore_countObjectElements(masterData[desc.shortname]);
c.each(masterData[desc.shortname],function(g,a){if(res[g]!=null){rows.push("<tr><td width=50%>"+a.bezeichnung+"<td>");rows.push('<a href="#" id="'+b+'" val="'+a.id+'">'+res[g]+"</a><td>"+Math.round(100*res[g]/m)+"%");e.push({label:a.bezeichnung.trim(13),data:res[g]})}else if(f<20){rows.push("<tr><td width=50%>"+a.bezeichnung+"<td>");rows.push("0<td>0%")}});rows.push('<tr bgcolor="#e7eef4"><td><i>Summe</i><td><i>'+m+"</i><td>");rows.push("</table></small>");if(this.filter.showTables==null)rows=[];
rows.unshift("<b>"+desc.bezeichnung+"</b>");this.filter.showCharts==1&&rows.push('<div style="width:250px;height:250px;" id="'+b+'_graph"/><div align="center" id="'+b+'_hover"/>');c("#"+b).html(rows.join(""));c("#"+b+" a").click(function(){if(c(this).attr("id")==b){churchInterface.setCurrentView(personView);personView.clearFilter();personView.filter[b.substr(5,99)]=c(this).attr("val");c.each(this_object.filter,function(g,a){personView.filter[g]=a})}return false});if(this.filter.showCharts==1){c.plot(c("#"+
b+"_graph"),e,{series:{pie:{show:true,label:{show:true,threshold:0.03}}},legend:{show:false},grid:{hoverable:true,clickable:false}});c("#"+b+"_graph").bind("plothover",function(g,a,l){if(l){percent=parseFloat(l.series.percent).toFixed(1);c("#"+b+"_hover").html('<small><span style="align:center;font-weight: bold; color: '+l.series.color+'">'+l.series.label+" ("+percent+"%)</span></small>")}})}};o.prototype.renderYearStatistic=function(b,h){this_object=this;var j=[],m=[],e=(new Date).getFullYear(),
f=false;c.each(allPersons,function(g,a){if(a[b]!=null&&this_object.checkFilter(a)){f=true;d=a[b].toDateEn().getFullYear();if(d<e-6)d=e-6;if(j[d]==null)j[d]=0;j[d]+=1}});if(f){m.push("<b>"+h+"</b>");m.push('<small><table cellpadding="2"');summe=0;c.each(j,function(g,a){if(a!=null){if(g==e-6)g="<="+g;m.push("<tr><td width=60%>"+g+'<td><a href="#" id="datefilter'+b+'" val="'+g+'">'+a+"</a>");summe+=a}});m.push('<tr bgcolor="#e7eef4"><td><i>Summe</i><td><i>'+summe+"</i>");m.push("</table></small>")}return m.join("")};
o.prototype.renderAgeGroups=function(){var b=[];res=[];summealter=summe=0;c.each(allPersons,function(h,j){if(this_object.checkFilter(j))if(j.geburtsdatum!=null){y=j.geburtsdatum.toDateEn().getAgeInYears();summealter+=y;y=Math.floor(y/10);if(res[y]==null)res[y]=0;res[y]+=1;summe+=1}});b.push("<b>Altersgruppen</b>");b.push('<small><table cellpadding="2"');c.each(res,function(h,j){j!=null&&b.push("<tr><td width=50%>"+h+"0-"+h+"9<td>"+j+"<td>"+Math.round(j/summe*1E3)/10+"%")});b.push("<tr><td><i>Summe/Mittel</i><td><i>"+
summe+"</i><td><i>"+Math.round(10*summealter/summe)/10+"J.</i>");b.push("</table></small>");return b.join("")};o.prototype.renderList=function(){this_object=this;this.filter.showTables=1;this.filter.showCharts=1;var b=[];if(this.filter.showTables==null&&this.filter.showCharts==null){this.filter.showTables=true;this.renderFilter()}b.push('<table cellpadding="5"><tr><td style="vertical-align:top;" valign="top" width="30%">');b.push('<div id="statsfilterStatus" name="status_id" arr="1"/>');b.push('<div id="statsfilterStation" name="station_id" arr="2"/>');
b.push('<div id="statsfilterGeschlecht" name="geschlecht_no" arr="4"/>');b.push('<div id="statsfilterFamilienstatus" name="familienstand_no" arr="6"/>');b.push('<div id="statsfilterNationalitaet" name="nationalitaet_id" arr="13"/>');if(this.getFilter("showTables")==1){b.push(this.renderAgeGroups());b.push(this.renderYearStatistic("erstkontakt","Erstkontakt"));b.push(this.renderYearStatistic("zugehoerig","Zugeh&ouml;rig"));b.push(this.renderYearStatistic("eintrittsdatum","Mitglied seit"));b.push(this.renderYearStatistic("austrittsdatum",
"Ausgetreten in"));b.push(this.renderYearStatistic("taufdatum","Getauft"));b.push(this.renderYearStatistic("hochzeitsdatum","Hochzeit"))}b.push('<td valign="top" style="vertical-align:top;" width="70%">');grps={};dataAvailable=false;current_year=(new Date).getFullYear();how_many_years=2;c.each(allPersons,function(e,f){f.gruppe!=null&&this_object.checkFilter(f)&&c.each(f.gruppe,function(g,a){if(masterData.groups[a.id].instatistik_yn==1&&(a.leiter>=0&&a.leiter<=2||a.leiter==4)){dataAvailable=true;if(grps[a.id]==
null)grps[a.id]=[];if(a.d==null)y=current_year-how_many_years;else{y=a.d.toDateEn().getFullYear();if(y<current_year-how_many_years)y=current_year-how_many_years}if(grps[a.id][y]==null)grps[a.id][y]=0;grps[a.id][y]+=1}})});if(dataAvailable){b.push("<b>Gruppen mit Statistik</b>");b.push('<small><table cellpadding="2">');b.push('<tr bgcolor="#e7eef4"><td><i>Gruppe</i><td width=10%><=');for(i=current_year-how_many_years;i<=current_year;i++)b.push("<i>"+i+"</i><td width=10%>");b.push("<i>Summe</i>");c.each(masterData.groups,
function(e,f){if(grps[f.id]!=null){b.push("<tr><td>"+f.bezeichnung+"<td>");summe=0;for(i=current_year-how_many_years;i<=current_year;i++){if(grps[f.id][i]!=null){b.push(grps[f.id][i]);summe+=grps[f.id][i]}b.push("<td>")}b.push(summe)}});b.push("</table></small>")}grps={};sumGruppentyp={};c.each(allPersons,function(e,f){if(f.gruppe!=null&&this_object.checkFilter(f)){var g={};c.each(f.gruppe,function(a,l){if(l.leiter>=0&&l.leiter<=2||l.leiter==4){if(grps[l.id]==null)grps[l.id]=[];if(l.d==null)y=current_year-
how_many_years;else{y=l.d.toDateEn().getFullYear();if(y<current_year-how_many_years)y=current_year-how_many_years}if(grps[l.id][y]==null)grps[l.id][y]=0;grps[l.id][y]+=1;a=masterData.groups[l.id].gruppentyp_id;if(g[y]==null)g[y]={};if(g[y][a]==null)g[y][a]=true}});c.each(g,function(a,l){if(sumGruppentyp[a]==null)sumGruppentyp[a]={};c.each(l,function(p){if(sumGruppentyp[a][p]==null)sumGruppentyp[a][p]=0;sumGruppentyp[a][p]+=1})})}});c.each(masterData.groupTypes,function(e,f){h=null;c.each(masterData.groups,
function(g,a){if(a.gruppentyp_id==f.id&&a.distrikt_id!=null)for(e=current_year-how_many_years;e<=current_year;e++)if(grps[a.id]!=null&&grps[a.id][e]!=null){if(h==null)h={};if(h[a.distrikt_id]==null)h[a.distrikt_id]=[];if(h[a.distrikt_id][e]==null)h[a.distrikt_id][e]=0;h[a.distrikt_id][e]+=grps[a.id][e]}});if(h!=null){b.push("<b>Distrikte des Gruppentyps "+f.bezeichnung+"</b>");b.push('<small><table cellpadding="2"><tr bgcolor="#e7eef4"><td><i>Distrikt</i><td width=10%><=');for(e=current_year-how_many_years;e<=
current_year;e++)b.push("<i>"+e+"</i><td width=10%>");b.push("<i>Summe</i>");c.each(h,function(g,a){summe=0;b.push("<tr><td>"+(masterData.districts[g]!=null?masterData.districts[g].bezeichnung:'<font color="red">DistriktId:'+g+"</font>")+"<td>");for(e=current_year-how_many_years;e<=current_year;e++){if(a[e]!=null){b.push(a[e]);summe+=a[e]}b.push("<td>")}b.push(summe)});b.push('<tr bgcolor="#e7eef4"><td><i>Summe</i><td>');summe=0;for(k=current_year-how_many_years;k<=current_year;k++){if(sumGruppentyp[k]!=
null&&sumGruppentyp[k][f.id]!=null){b.push(sumGruppentyp[k][f.id]);summe+=sumGruppentyp[k][f.id]}b.push("<td>")}b.push(summe);b.push("</table></small>")}});b.push("</table>");b.push('<div id="yearStats" style="width:800px;height:500px;"/><div id="yearStats_hover"/><div id="yearStats_choices"/>');c("#cdb_content").html(b.join(""));c("#cdb_content div").each(function(){c(this).attr("id").indexOf("statsfilter")==0&&this_object.renderMasterDataStatistic(c(this).attr("id"),c(this).attr("arr"),c(this).attr("name"))});
c("#cdb_content a").click(function(){if(c(this).attr("id").indexOf("datefilter")==0){churchInterface.setCurrentView(personView);personView.clearFilter();personView.filter.filterDates=c(this).attr("id").substr(10,99);personView.filter.dateAfter="01.01."+c(this).attr("val");personView.filter.dateBefore="31.12."+c(this).attr("val");c.each(this_object.filter,function(e,f){personView.filter[e]=f})}return false});if(this.getFilter("showCharts")==1){var h={};c.each(allPersons,function(e,f){this_object.checkFilter(f)&&
c.each(masterData.fields.f_church.fields,function(g,a){if(a.type=="date"){n=a.sql;if(f[n]!=null){if(h[n]==null)h[n]=[];if(h[n][f[n].toDateEn().getFullYear()]==null)h[n][f[n].toDateEn().getFullYear()]=0;h[n][f[n].toDateEn().getFullYear()]++}}})});datasets=[];c.each(h,function(e,f){data_=[];c.each(f,function(g,a){a!=null&&a>0&&data_.push([g,a])});datasets.push({label:e,data:data_})});var j=c("#yearStats_choices");c.each(datasets,function(e,f){j.append('<br/><input type="checkbox" name="'+e+'" checked="checked" id="id'+
e+'"><label for="id'+e+'">'+f.label+"</label>")});var m=function(){var e=[];j.find("input:checked").each(function(){var f=c(this).attr("name");f&&datasets[f]&&e.push(datasets[f])});e.length>0&&c.plot(c("#yearStats"),e,{yaxis:{min:0},xaxis:{tickDecimals:0},legend:{show:false},grid:{hoverable:true,clickable:false}})};j.find("input").click(m);c("#yearStats").bind("plothover",function(e,f,g){g&&c("#yearStats_hover").html('<span style="font-weight: bold; color: '+g.series.color+'">'+g.series.label+"</span>")});
m()}}})(jQuery);
