var map=null,geocoder=null;function _cdb_setGeoPoint(b,a,d){if(b!=null)b=new google.maps.Marker({position:d,map:b,title:a+" "+d.lat()+" "+d.lng()})}
function _cdb_addPersonToMap(b,a,d){var g=new google.maps.MarkerImage("https://www.google.com/intl/en_us/mapfiles/ms/micons/blue-dot.png",new google.maps.Size(32,32),new google.maps.Point(0,0),new google.maps.Point(6,12),new google.maps.Size(12,12));jQuery.each(allPersons,function(f,e){if(e.geolat!="")if(a==null||Math.abs(parseFloat(d)-parseFloat(e.geolng))<0.06&&Math.abs(parseFloat(a)-parseFloat(e.geolat))<0.03){f=new google.maps.LatLng(e.geolat,e.geolng);f=new google.maps.Marker({position:f,map:b,
icon:g,title:"Person: "+e.vorname+" "+e.name+" ["+e.id+"]"});google.maps.event.addDomListener(f,"click",function(){churchInterface.setCurrentView(personView);personView.clearFilter();personView.setFilter("searchEntry",e.id);personView.renderView()})}})}
function _cdb_addGroupButton2Maps(b,a){b.style.padding="4px";var d=document.createElement("DIV");d.className="map-control-wrapper";d.title="Klicke, um hier Gruppen anzuzeigen";b.appendChild(d);b=document.createElement("DIV");b.className="map-control-label";b.innerHTML="Gruppen";d.appendChild(b);google.maps.event.addDomListener(d,"click",function(){a.getZoom()<11?alert("Bitte erst weiter reinzoomen!"):cdb_addGroupsToMap(a,a.getCenter().lat(),a.getCenter().lng())})}
function _cdb_addPersonButton2Maps(b,a){b.style.padding="4px";var d=document.createElement("DIV");d.className="map-control-wrapper";d.title="Klicke, um Personen in der N&auml;he anzuzeigen";b.appendChild(d);b=document.createElement("DIV");b.className="map-control-label";b.innerHTML="Personen";d.appendChild(b);google.maps.event.addDomListener(d,"click",function(){a.getZoom()<12?alert("Bitte erst weiter reinzoomen!"):_cdb_addPersonToMap(a,a.getCenter().lat(),a.getCenter().lng())})}
function _cdb_limitZoom(b){google.maps.event.addListener(b,"zoom_changed",function(){if(b.getZoom()>12){alert("Ein weiterer Zoom ist leider nicht erlaubt!");b.setZoom(12)}})}
function cdb_prepareMap(b,a){a={zoom:11,center:a,mapTypeId:google.maps.MapTypeId.ROADMAP};b=document.getElementById(b);if(b==null)return null;b=new google.maps.Map(b,a);a=document.createElement("DIV");var d=new _cdb_addGroupButton2Maps(a,b);a.index=1;b.controls[google.maps.ControlPosition.TOP_RIGHT].push(a);if(masterData.auth.viewalldata){a=document.createElement("DIV");d=new _cdb_addPersonButton2Maps(a,b);a.index=1;b.controls[google.maps.ControlPosition.TOP_RIGHT].push(a)}if(masterData.settings.googleMapLayer==
1)(new google.maps.TrafficLayer).setMap(b);else if(masterData.settings.googleMapLayer==2)(new google.maps.BicyclingLayer).setMap(b);else if(masterData.settings.googleMapLayer==3){a={getTileUrl:function(g,f){return"http://mt1.google.com/vt/lyrs=m@155076273,transit:comp|vm:&hl=en&opts=r&s=Galil&z="+f+"&x="+g.x+"&y="+g.y},tileSize:new google.maps.Size(256,256),isPng:true};a=new google.maps.ImageMapType(a);b.overlayMapTypes.insertAt(0,a)}return b}
function cdb_showGeoPerson(b,a,d){if(geocoder)if(allPersons[a].geolat!=""){var g=new google.maps.LatLng(allPersons[a].geolat,allPersons[a].geolng);map=cdb_prepareMap("map_canvas"+a,g);_cdb_setGeoPoint(map,b,g);d==true&&_cdb_limitZoom(map)}else geocoder.geocode({address:b},function(f,e){if(e==google.maps.GeocoderStatus.OK){map=cdb_prepareMap("map_canvas"+a,f[0].geometry.location);_cdb_setGeoPoint(map,b,f[0].geometry.location);e={};e.id=a;e.func="f_geocode_person";e.lat=f[0].geometry.location.lat();
e.lng=f[0].geometry.location.lng();allPersons[a].geolat=f[0].geometry.location.lat();allPersons[a].geolng=f[0].geometry.location.lng();jQuery.getJSON("index.php?q=churchdb/ajax",e,function(c){c!="ok"&&alert("Fehler beim Speichern der Geocode-Daten: "+c)})}else jQuery("#map_canvas"+a).html("Geocoding war nicht erfolgreich:"+e)})}
function cdb_showGeoGruppe(b,a){if(geocoder)if(masterData.groups[a].geolat!=""){var d=new google.maps.LatLng(masterData.groups[a].geolat,masterData.groups[a].geolng);map=cdb_prepareMap("map_canvasg"+a,d);_cdb_setGeoPoint(map,b,d)}else geocoder.geocode({address:b},function(g,f){if(f==google.maps.GeocoderStatus.OK){map=cdb_prepareMap("map_canvasg"+a,g[0].geometry.location);_cdb_setGeoPoint(map,b,g[0].geometry.location);f={};f.id=a;f.func="f_geocode_gruppe";f.lat=g[0].geometry.location.lat();f.lng=g[0].geometry.location.lng();
masterData.groups[a].geolat=g[0].geometry.location.lat();masterData.groups[a].geolng=g[0].geometry.location.lng();jQuery.getJSON("index.php?q=churchdb/ajax",f,function(e){e!="ok"&&alert("Fehler beim Speichern der Geocode-Daten: "+e)})}else jQuery("#map_canvas"+a).html("Geocoding war nicht erfolgreich:"+f)})}
function cdb_addGroupsToMap(b,a,d,g){var f=new google.maps.MarkerImage(masterData.modulespath+"/images/gruppe_shadow.png",new google.maps.Size(50,50),new google.maps.Point(0,0),new google.maps.Point(10,25),new google.maps.Size(25,25));jQuery.each(masterData.groups,function(e,c){if(c.geolat!=""&&c.valid_yn==1&&c.versteckt_yn==0)if(a==null||Math.abs(parseFloat(d)-parseFloat(c.geolng))<0.2&&Math.abs(parseFloat(a)-parseFloat(c.geolat))<0.1){url="gruppe_standard.png";if(c.distrikt_id!=null&&masterData.districts[c.distrikt_id].imageurl!=
null)url=masterData.districts[c.distrikt_id].imageurl;e=new google.maps.MarkerImage(masterData.modulespath+"/images/"+url,new google.maps.Size(40,50),new google.maps.Point(0,0),new google.maps.Point(10,25),new google.maps.Size(20,25));var i=new google.maps.LatLng(c.geolat,c.geolng),h="Gruppe: "+c.bezeichnung+" ["+c.id+"]";if(c.distrikt_id!=null)h=h+"\n Distrikt: "+masterData.districts[c.distrikt_id].bezeichnung;if(c.treffzeit!="")h=h+"\n "+c.treffzeit;if(c.treffpunkt!=null&&c.treffpunkt!="")h=h+"\n Ort: "+
c.treffpunkt;if(c.treffname!="")h=h+"\n bei: "+c.treffname;if(c.zielgruppe!="")h=h+"\n Zielgruppe: "+c.zielgruppe;e=new google.maps.Marker({position:i,map:b,icon:e,shadow:f,title:h});google.maps.event.addDomListener(e,"click",function(){if(g!=null)g(c.id);else{churchInterface.setCurrentView(groupView);groupView.clearFilter();groupView.setFilter("searchEntry",c.id);groupView.renderView()}})}})}
function cdb_initializeGoogleMaps(){churchInterface.setStatus("Initialisiere GoogleMap...");try{geocoder=new google.maps.Geocoder}catch(b){jQuery("#cdb_info").append('<div class="alert alert-info googlemaps">GoogleMaps steht nicht zur Verf&uuml;gung. ('+b.message+")</div>");window.setTimeout(function(){$("#cdb_info div.googlemaps").hide("slow")},5E3)}};
