(function(b){function c(){StandardTableView.call(this);this.name="SettingsView"}Temp.prototype=StandardTableView.prototype;c.prototype=new Temp;settingsView=new c;c.prototype.getData=function(){return allPersons};c.prototype.renderMenu=function(){this_object=this;menu=new CC_Menu("Men&uuml;");menu.addEntry("Zur&uuml;ck zur Personenliste","apersonview","arrow-left");b("#cdb_precontent").html("");b("#cdb_group").html("");b("#cdb_todos").html("");menu.renderDiv("cdb_menu")?b("#cdb_menu a").click(function(){if(b(this).attr("id")==
"apersonview"){menuDepth="amain";churchInterface.setCurrentView(personView,true)}return false}):b("#cdb_menu").hide()};c.prototype.renderListMenu=function(){var a=new CC_Navi;a.addEntry(true,"id1","Einstellungen");a.renderDiv("cdb_search")};c.prototype.renderFilter=function(){b("#cdb_filter").html("");b.each(this.filter,function(a,e){b("#"+a).val(e)});this.implantStandardFilterCallbacks(this,"cdb_filter")};c.prototype.checkFilter=function(){return true};c.prototype.renderList=function(){this_object=
this;var a=[];a.push("<h2>E-Mailer</h2>");a.push("<table>");a.push('<tr><td width="50%">Welche Mailer-Variante soll verwendet werden: ');a.push('<td><select id="mailerType">');a.push('<option value="0" '+(masterData.settings.mailerType==0?"selected":"")+">Direkter Aufruf des lokalen E-Mail-Programms (Begrenzung bei Windows!)");a.push('<option value="1" '+(masterData.settings.mailerType==1?"selected":"")+">Export der E-Mail-Addressen in ein neues Fenster");a.push('<option value="2" '+(masterData.settings.mailerType==
2?"selected":"")+">E-Mail-Versand direkt &uuml;ber ChurchTools (inkl. Serienbrieffelder!)");a.push("</select>");a.push('<tr><td width="50%">Welches Trennzeichen soll verwendet werden: ');a.push('<td><select id="mailerSeparator">');a.push('<option value="0" '+(masterData.settings.mailerSeparator==0?"selected":"")+">Semikolon (bei Windows-PCs sinnvoll)");a.push('<option value="1" '+(masterData.settings.mailerSeparator==1?"selected":"")+">Komma (bei z.Bsp Mac oder GMail sinnvoll)");a.push("</select>");
if(masterData.user_pid!=null&&allPersons[masterData.user_pid]!=null){a.push('<tr><td width="50%">Welches Feld soll bei Mailer mit direktem Aufruf verwendet werden: ');a.push('<td><select id="mailerBcc">');if(masterData.settings.mailerBcc==null)masterData.settings.mailerBcc=0;a.push('<option value="0" '+(masterData.settings.mailerBcc==0?"selected":"")+">An");a.push('<option value="1" '+(masterData.settings.mailerBcc==1?"selected":"")+">Bcc");a.push("</select>")}a.push("</table>");var e=false;masterData.user_pid!=
null&&allPersons[masterData.user_pid]!=null&&allPersons[masterData.user_pid].gruppe!=null&&b.each(allPersons[masterData.user_pid].gruppe,function(f,d){if(d.leiter>0&&masterData.groups[d.id].followup_typ_id!=null&&masterData.groups[d.id].followup_typ_id!=0)e=true});if(e){a.push("<h2>Follow-Ups</h2><table>");a.push('<tr><td width="50%">Umgang mit &uuml;berf&auml;lligen FollowUps: ');a.push('<td><select id="automaticActivateFollowupOverdue">');if(masterData.settings.automaticActivateFollowupOverdue==
null)masterData.settings.automaticActivateFollowupOverdue=1;a.push('<option value="0" '+(masterData.settings.automaticActivateFollowupOverdue==0?"selected":"")+">Filter nicht automatisch aktivieren");a.push('<option value="1" '+(masterData.settings.automaticActivateFollowupOverdue==1?"selected":"")+">Filter automatisch aktivieren");a.push("</select></table>")}a.push("<h2>Personenliste</h2><table>");a.push('<tr><td width="50%">Zus&auml;tzliche Layer bei der Anzeige von Google Karten: ');a.push('<td><select id="googleMapLayer">');
if(masterData.settings.googleMapLayer==null)masterData.settings.googleMapLayer=0;a.push('<option value="0" '+(masterData.settings.googleMapLayer==0?"selected":"")+">Keine weiteren Layer");a.push('<option value="1" '+(masterData.settings.googleMapLayer==1?"selected":"")+">Verkehrsdichte anzeigen");a.push('<option value="2" '+(masterData.settings.googleMapLayer==2?"selected":"")+">Fahrradwege anzeigen");a.push('<option value="3" '+(masterData.settings.googleMapLayer==3?"selected":"")+">Verkehrsnetzplan (Transit) anzeigen");
a.push("</select>");if(masterData.auth.viewalldata){a.push('<tr><td width="50%">Personen mit folgendem Status sollen ausgeblendet werden: ');a.push('<td><select id="hideStatus">');if(masterData.settings.hideStatus==null)masterData.settings.hideStatus=-1;a.push('<option value="-1">');b.each(masterData.status,function(f,d){a.push('<option value="'+d.id+'" '+(masterData.settings.hideStatus==d.id?"selected":"")+">"+d.bezeichnung)});a.push("</select>")}a.push("</table>");a.push("<h2>Signatur</h2>");a.push('<div id="editor">');
masterData.settings.signature!=null&&a.push(masterData.settings.signature);a.push("</div><br/><p>");a.push(form_renderButton({label:"Signatur speichern",cssid:"savesignature"}));b("#cdb_content").html(a.join(""));form_implantWysiwygEditor("editor",false);b("#savesignature").click(function(){masterData.settings.signature=CKEDITOR.instances.editor.getData();churchInterface.jsonWrite({func:"saveSetting",sub:"signature",val:CKEDITOR.instances.editor.getData()})});b("#cdb_content select").change(function(){masterData.settings[b(this).attr("id")]=
b(this).val();churchInterface.jsonWrite({func:"saveSetting",sub:b(this).attr("id"),val:b(this).val()})})}})(jQuery);
