var gruppe_id=null,person_id=null,event_id=null,last_person_id=null,view_checkin=false,view_easy=false,allPersons=null,allEvents=null,search_person="";function renderDatumsname(){if(event_id==null||allEvents[event_id]==null)$("#datumsname").html("");else{var b=" &nbsp; "+allEvents[event_id].datumvon.toDateEn(true).toStringDe(true);if(allEvents[event_id].bezeichnung!=null)b=b+" - "+allEvents[event_id].bezeichnung;$("#datumsname").html(b)}}
function renderEvent(b){if(b==null)b=true;if(b){var a=[];a.push("<h3>Veranstaltungen &nbsp;"+(view_easy?"":form_renderImage({cssid:"event_config",width:24,src:"options.png"}))+"</h3>");a.push('<span class="veranstaltung">Kein JavaScript?</span>');a.push("<p></p>");view_easy||a.push(form_renderButton({label:"Hinzuf&uuml;gen",cssid:"event_add"}));$("#events").html(a.join(""))}var e=[];$.each(churchcore_sortData(allEvents,"datumvon"),function(d,c){d=c.datumvon.toDateEn(true);var g=d.getMinutes(),f=c.bezeichnung!=
null?" ("+c.bezeichnung+")":"",h="";if(c.person!=null)h=churchcore_countObjectElements(c.person)+" Personen eingecheckt";e.push({id:c.id,bezeichnung:dayNames[d.getDay()]+", "+d.getDate()+"."+(d.getMonth()+1)+". "+d.getHours()+":"+(g<10?"0"+g:g)+" Uhr "+f+"<br><small>"+h+"</small>"});if(event_id==null&&(masterData.settings.event_datum==null||masterData.settings.event_datum.toDateEn(true).getTime()==d.getTime()))event_id=c.id});renderDatumsname();form_renderSelectable($("#events span.veranstaltung"),
{height:290,data:e,selected:event_id,select:function(d){event_id=d;churchInterface.jsendWrite({func:"saveSetting",sub:"event_datum",val:allEvents[d].datumvon},null,null,false);masterData.settings.event_datum=allEvents[d].datumvon;window.setTimeout(function(){gruppe_id=null;renderGroups();renderPersons();renderDatumsname()},20)}});if(b){$("#event_config").click(function(){var d=new CC_Form("Auswahl einer Kategorie aus "+masterData.churchservice_name);d.addHtml("<p><small>Die Anzeige kann automatisch durch Events aus "+
masterData.churchservice_name+" gef&uuml;llt werden, bitte hierzu eine Event-Kategorie w&auml;hlen.</small>");d.addSelect({freeoption:true,data:masterData.cs_category,selected:masterData.settings.category_id,cssid:"category_id"});form_showDialog("Veranstaltungsanzeige",d.render(),400,400,{Speichern:function(){var c=d.getAllValsAsObject();if(c.category_id=="")c.category_id=null;masterData.settings.category_id=c.category_id;churchInterface.jsendWrite({func:"saveSetting",sub:"category_id",val:c.category_id},
null,null,false);loadData();$(this).dialog("close")},Abbruch:function(){$(this).dialog("close")}});return false});$("#event_add").click(function(){if(churchcore_isObjectEmpty(masterData.groups))alert("Bitte erst einen Distrikt mit Gruppen nehmen!");else{var d=new CC_Form("Event hinzuf&uuml;gen");d.addInput({label:"Datum",value:(new Date).toStringDe(false),required:true});d.addInput({label:"Uhrzeit",value:"10:00",required:true});var c=form_showDialog("Veranstaltungsanzeige",d.render(),400,400,{Speichern:function(){var g=
d.getAllValsAsObject(),f=g.Datum.toDateDe(false);f.getFullYear()<2E3&&f.setFullYear(f.getFullYear()+100);if(f.dayDiff(new Date)>6){alert("Event darf nicht vor 6 Tagen liegen!");return false}g.Uhrzeit=g.Uhrzeit.replace(/\./g,":");f=f.toStringDe(false)+" "+g.Uhrzeit;g.datumvon=f.toDateDe(true);g.datumbis=g.datumvon;g.gruppe_id=gruppe_id!=null?gruppe_id:churchcore_getFirstElement(masterData.groups).id;g.func="addEvent";churchInterface.jsendWrite(g,function(){loadData();c.dialog("close")},null,false)},
Abbruch:function(){$(this).dialog("close")}})}return false})}}
function renderGroups(b){if(b==null)b=true;if(b){var a=[];a.push("<h3>Gruppen &nbsp;"+(view_easy?"":form_renderImage({cssid:"gruppen_config",width:24,src:"options.png"}))+"</h3>");a.push('<span class="gruppen"></span>');a.push("<p></p>");view_easy?a.push("<p>&nbsp;"):a.push(form_renderButton({label:"Checkin abschliessen",cssid:"closecheckin"}));$("#groups").html(a.join(""))}var e=[];$.each(churchcore_sortMasterData(masterData.groups),function(d,c){if(view_checkin||!view_checkin&&allEvents[event_id]!=
null&&(allEvents[event_id].gruppen==null||allEvents[event_id].gruppen[c.id]==null||allEvents[event_id].gruppen[c.id].kommentar==null)){var g=0,f=0;$.each(allPersons,function(j,i){if(churchcore_inArray(c.id,i.gruppe)){f+=1;if(allEvents[event_id]!=null&&allEvents[event_id].person!=null&&allEvents[event_id].person[i.id]==c.id)g+=1}});d=c.bezeichnung;var h="";if(allEvents[event_id]!=null&&allEvents[event_id].gruppen!=null&&allEvents[event_id].gruppen[c.id]!=null)if(allEvents[event_id].gruppen[c.id].kommentar!=
null){h="ui-state-checkin";d=allEvents[event_id].gruppen[c.id].kommentar==""?d+'<span class="pull-right">'+form_renderImage({src:"check-64.png",width:24,label:"Checkin abgeschlossen"})+"</span>":d+'<span class="pull-right">'+form_renderImage({src:"comment.png",width:24,label:allEvents[event_id].gruppen[c.id].kommentar})+"</span>"}d=d+"<br><small>"+g+" von "+f+" Personen eingecheckt.";if(allEvents[event_id]!=null&&allEvents[event_id].gruppen!=null&&allEvents[event_id].gruppen[c.id]!=null)if(allEvents[event_id].gruppen[c.id].anzahl_gaeste>
0)d=d+" "+allEvents[event_id].gruppen[c.id].anzahl_gaeste+" G&auml;ste";d+="</small>";e.push({id:c.id,bezeichnung:d,htmlclass:h})}});form_renderSelectable($("#groups span.gruppen"),{height:view_easy?330:290,data:e,deselectable:true,selected:gruppe_id,select:function(d){gruppe_id=d;window.setTimeout(function(){renderPersons()},20)},deselect:function(){gruppe_id=null;window.setTimeout(function(){renderPersons()},20)}});if(b){$("#gruppen_config").click(function(){renderChoseDistrikt();return false});
$("#closecheckin").click(function(){if(gruppe_id==null||event_id==null)alert("Bitte vorher eine Veranstaltung und eine Gruppe markieren!");else{var d=new CC_Form;d.addHtml("<p><small>Es besteht nun noch die M&ouml;glichkeit eine Anzahl der G&auml;ste anzugeben, einen Kommentar sowie eine Gruppenliste zu drucken (wenn ein Drucker ausgew&auml;hlt wurde).</small>");var c=0,g="";if(allEvents[event_id].gruppen!=null&&allEvents[event_id].gruppen[gruppe_id]!=null){if(allEvents[event_id].gruppen[gruppe_id].anzahl_gaeste>
0)c=allEvents[event_id].gruppen[gruppe_id].anzahl_gaeste;if(allEvents[event_id].gruppen[gruppe_id].kommentar!=null)g=allEvents[event_id].gruppen[gruppe_id].kommentar}d.addInput({label:"Anzahl G&auml;ste",value:c,cssid:"anzahl_gaeste"});d.addTextarea({label:"Kommentar",rows:4,data:g,placeholder:"Kommentar",cssid:"kommentar"});masterData.settings.printer_id!=null&&d.addCheckbox({label:"Gruppenliste drucken",cssid:"printgrouplist",checked:masterData.settings.printgrouplist});form_showDialog("Checkin <i>"+
masterData.groups[gruppe_id].bezeichnung+"</i> abschliessen",d.render(null,"vertical"),400,450,{"Checkin abschliessen":function(){var f=d.getAllValsAsObject();f.func="finishCheckin";f.gruppe_id=gruppe_id;f.datumvon=allEvents[event_id].datumvon;f.printer_id=masterData.settings.printer_id;f.gruppentreffen_id=allEvents[event_id].gruppen[gruppe_id].gruppentreffen_id;churchInterface.jsendWrite(f,function(h){h?loadData():alert("data")},null,false);$(this).dialog("close")},Abbruch:function(){$(this).dialog("close")}}).find("#printgrouplist").change(function(){masterData.settings.printgrouplist=
$(this).attr("checked")=="checked"?1:0;churchInterface.jsendWrite({func:"saveSetting",sub:"printgrouplist",val:masterData.settings.printgrouplist},null,null,false)})}return false})}masterData.settings.distrikt_id==null&&renderChoseDistrikt()}
function renderChoseDistrikt(){var b=new CC_Form("Bitte einen Distrikt ausw&auml;hlen");b.addHtml("<p><small>Um die passenden Gruppen anzeigen zu k&ouml;nnen, muss hier ein Distrikt ausgew&auml;hlt werden.</small>");b.addSelect({data:masterData.cdb_distrikt,selected:masterData.settings.distrikt_id,cssid:"distrikt_id"});form_showDialog("Anzeige der Gruppen",b.render(),400,400,{Speichern:function(){var a=b.getAllValsAsObject();masterData.settings.distrikt_id=a.distrikt_id;churchInterface.jsendWrite({func:"saveSetting",
sub:"distrikt_id",val:a.distrikt_id},null,null,false);loadData();$(this).dialog("close")},Abbruch:function(){$(this).dialog("close")}})}
function _renderAddPerson(b,a){a.addHidden({cssid:"func",value:"addGroupRelation"});a.addHtml("<br>");a.addInput({label:"Person",cssid:"person_id"});a.addSelect({label:"Gruppe",cssid:"gruppe_id",data:churchcore_sortMasterData(masterData.groups),selected:gruppe_id});b.find("#form_content").html(a.render(null,"horizontal"));b.find("#person_id").focus();form_autocompletePersonSelect("#person_id")}
function _renderNewPerson(b,a){a.addHidden({cssid:"func",value:"addPerson"});a.addInput({label:"Vorname",cssid:"vorname",required:true});a.addInput({label:"Nachname",cssid:"name",required:true});a.addInput({label:"Geburtsdatum",type:"small",cssid:"geburtsdatum"});a.addSelect({label:"Gruppe",cssid:"gruppe_id",data:churchcore_sortMasterData(masterData.groups),selected:gruppe_id});a.addSelect({label:"Bereich",cssid:"bereich_id",htmlclass:"setting",data:churchcore_sortMasterData(masterData.cdb_bereich),
selected:masterData.settings.bereich_id});a.addSelect({label:"Status",cssid:"status_id",htmlclass:"setting",data:churchcore_sortMasterData(masterData.cdb_status),selected:masterData.settings.status_id});a.addSelect({label:"Station",cssid:"station_id",htmlclass:"setting",data:churchcore_sortMasterData(masterData.cdb_station),selected:masterData.settings.station_id});b.find("#form_content").html(a.render(null,"horizontal"));b.find("#vorame").focus();b.find("select.setting").change(function(){masterData.settings[$(this).attr("id")]=
$(this).val();churchInterface.jsendWrite({func:"saveSetting",sub:$(this).attr("id"),val:$(this).val()},null,null,false)})}
function renderNewPerson(){var b=[],a=new CC_Navi;a.addEntry(true,"view-add","Aus "+masterData.churchdb_name+" suchen");a.addEntry(false,"view-new","Neue Person erstellen");b.push(a.render());b.push('<div id="form_content"></div>');var e=new CC_Form,d=form_showDialog("Gruppenanzeige",b.join(""),500,480,{Hinzufuegen:function(){var c=e.getAllValsAsObject();if(c.func=="addPerson")if(c.vorname==""||c.name=="")alert("Bitte Vorname und Name angeben!");else if(c.geburtsdatum!="")c.geburtsdatum=c.geburtsdatum.toDateDe().toStringEn();
else delete c.geburtsdatum;churchInterface.jsendWrite(c,function(g,f){if(g){person_id=f;loadData();d.dialog("close")}else alert(f)},null,false)},Abbruch:function(){$(this).dialog("close")}});d.dialog({height:290});_renderAddPerson(d,e);d.find("ul.nav a").click(function(){e=new CC_Form;if($(this).attr("id")=="view-add"){_renderAddPerson(d,e);d.dialog({height:290})}else{_renderNewPerson(d,e);d.dialog({height:480})}a.activate($(this).attr("id"));return false})}
function renderPersons(b){if(b==null)b=true;if(b){var a=[];a.push(form_renderInput({htmlclass:"pull-right search-query input-small",cssid:"searchPerson",value:search_person}));a.push("<h3>Personen &nbsp;"+(view_easy?"":form_renderImage({cssid:"personen_config",width:24,src:"options.png"}))+"</h3>");a.push('<span class="personen"></span>');a.push("<p></p>");a.push(form_renderButton({label:"Checkin",htmlclass:"btn-primary",cssid:"btn_checkin",disabled:person_id==null})+"&nbsp;");a.push(form_renderButton({label:"Letzten r&uuml;ckg&auml;ngig",
htmlclass:"pull-right",cssid:"btn_undocheckin",disabled:last_person_id==null}));$("#persons").html(a.join(""))}var e=[];if(allEvents[event_id]!=null){a=null;a=masterData.settings.sortnames==1?churchcore_sortData(allPersons,"vorname",null,null,"name"):churchcore_sortData(allPersons,"name",null,null,"vorname");$.each(a,function(d,c){if(view_checkin||allEvents[event_id].person==null||allEvents[event_id].person[c.id]==null)if(gruppe_id==null||churchcore_inArray(gruppe_id,c.gruppe))if(search_person==""||
c.vorname.toUpperCase().indexOf(search_person.toUpperCase())==0||c.name.toUpperCase().indexOf(search_person.toUpperCase())==0){c.bezeichnung="";if(allEvents[event_id].person!=null&&allEvents[event_id].person[c.id]!=null){c.bezeichnung='<span class="pull-right">'+form_renderImage({src:"check-64.png",width:24,label:"Checkin abgeschlossen"})+"</span>";c.htmlclass="ui-state-checkin"}if(c.imageurl==null)c.imageurl="nobody.gif";c.bezeichnung=c.bezeichnung+'<img height="40px" align="left" style="max-height:44px;margin-right:10px;" src="'+
masterData.files_url+"/fotos/"+c.imageurl+'"/>'+c.vorname+" "+c.name+"<br/><small>";gruppe_id==null&&$.each(c.gruppe,function(g,f){if(masterData.groups[f]!=null)c.bezeichnung=c.bezeichnung+masterData.groups[f].bezeichnung+" &nbsp; "});c.bezeichnung+="</small>";e.push(c)}})}event_id!=null&&e.push({id:-1,bezeichnung:'<img height="40px" align="left" style="max-height:44px;margin-right:10px;" src="'+masterData.files_url+'/fotos/nobody.gif"/><i>Person der Gruppe hinzuf&uuml;gen</i><br/><small></small>'});
if(e.length==2){person_id=e[0].id;$("#btn_checkin").removeAttr("disabled")}a=0;if(person_id==null)a=$("#persons ul").scrollTop();form_renderSelectable($("#persons span.personen"),{height:view_easy?330:290,min_element_height:45,data:e,selected:person_id,select:function(d){d==-1&&renderNewPerson();person_id=d;masterData.settings.autocheckin==1?doCheckin():$("#btn_checkin").removeAttr("disabled")}});a!=0&&$("#persons ul").scrollTop(a);if(b){$("#btn_checkin").click(function(){doCheckin()});$("#btn_undocheckin").click(function(){undoCheckin()});
$("#searchPerson").keyup(function(){search_person=$(this).val();renderPersons(false)});$("#personen_config").click(function(){renderPersonenConfig();return false})}}
function renderPersonenConfig(){var b=new CC_Form("Bitte Personenliste konfigurieren");b.addCheckbox({label:"<p>Nach Vorname sortieren<br><small>Legt die Sortierung der Personen fest</small>",checked:masterData.settings.sortnames==1,cssid:"sortnames"});b.addCheckbox({label:"<p>Auto-Checkin<br><small>Beim Klick auf eine Person wird diese sofort eingecheckt!</small>",checked:masterData.settings.autocheckin==1,cssid:"autocheckin"});form_showDialog("Anzeige der Personen",b.render(null,"vertical"),400,
400,{Speichern:function(){var a=b.getAllValsAsObject();masterData.settings.sortnames=a.sortnames;masterData.settings.autocheckin=a.autocheckin;churchInterface.jsendWrite({func:"saveSetting",sub:"sortnames",val:a.sortnames},null,null,false);churchInterface.jsendWrite({func:"saveSetting",sub:"autocheckin",val:a.autocheckin},null,null,false);loadData();$(this).dialog("close")},Abbruch:function(){$(this).dialog("close")}})}
function doCheckin(){if(allEvents[event_id]==null)alert("Kein Event geladen!?");else if(allEvents[event_id].person!=null&&allEvents[event_id].person[person_id]!=null)alert("Person ist schon in Gruppe "+masterData.groups[allEvents[event_id].person[person_id]].bezeichnung+" eingecheckt!");else{if(allEvents[event_id].person==null)allEvents[event_id].person={};var b=gruppe_id;if(b==null)if(churchcore_countObjectElements(allPersons[person_id].gruppe)>1)alert("Person ist in mehreren Gruppen. Bitte vorher Gruppe anklicken.");
else b=allPersons[person_id].gruppe[0];if(b!=null){var a={};a.func="checkin";a.event_id=event_id;a.cs_event=allEvents[event_id].cs_event;a.datumvon=allEvents[event_id].datumvon;a.person_id=person_id;a.gruppe_id=b;a.printer_id=$("#printer_id").val();allEvents[event_id].person[person_id]=b;last_person_id=person_id;if($("#searchPerson").val()!=""){search_person="";renderPersons()}else{if(view_checkin){$("#persons a[data-id="+person_id+"]").removeClass("ui-state-hover");$("#persons a[data-id="+person_id+
"]").addClass("ui-state-checkin");$("#persons a[data-id="+person_id+"]").prepend('<span class="pull-right">'+form_renderImage({src:"check-64.png",width:24,label:"Checkin abgeschlossen"})+"</span>")}else $("#persons li[data-id="+person_id+"]").remove();$("#btn_undocheckin").removeAttr("disabled");$("#btn_checkin").attr("disabled","true")}person_id=null;search_person="";churchInterface.jsendWrite(a,function(e,d){if(!e){alert("Fehler: "+d+" aufgetreten. Nehme letzten nicht mehr.");undoCheckin()}},null,
false);window.setTimeout(function(){renderGroups();renderEvent(false)},20)}}}
function undoCheckin(){if(last_person_id!=null&&allEvents[event_id].person!=null&&allEvents[event_id].person[last_person_id]!=null){var b={};b.func="undocheckin";b.event_id=event_id;b.cs_event=allEvents[event_id].cs_event;b.datumvon=allEvents[event_id].datumvon;b.person_id=last_person_id;b.gruppe_id=allEvents[event_id].person[last_person_id];delete allEvents[event_id].person[last_person_id];person_id=last_person_id;last_person_id=null;renderPersons();churchInterface.jsendWrite(b,function(a,e){if(!a){alert("Fehler: "+
e+" aufgetreten. Nehme letzten nicht mehr.");undoCheckin()}},null,false);window.setTimeout(function(){renderGroups(false);renderEvent(false)},20)}else alert("Letztes Checkin ist leider nicht mehr vorhanden!")}
function renderView(b){if(b){var a=[];if(view_easy){a.push('<div class="well">');a.push('<span class="pull-right" id="printer"></span>');a.push("<h1>"+masterData.churchcheckin_name+'<small><span id="datumsname"></span></small></h1>');a.push("</div>");a.push('<div class="row-fluid">');a.push('<div id="groups" class="span5 well"></div>');a.push('<div id="persons" class="span7 well"></div>')}else{a.push('<div class="well">');a.push('<span class="pull-right" id="printer"></span>');a.push("<h1>"+masterData.churchcheckin_name+
'<small><span id="datumsname"></span></small></h1>');a.push('<p>Bitte Veranstaltung, Gruppe und Person ausw&auml;hlen und dann auf Checkin klicken. <a href="http://intern.churchtools.de/?q=churchwiki#WikiView/filterWikicategory_id:0/doc:ChurchCheckin/" target="_clean"><i class="icon-question-sign"></i></a></p>');a.push("</div>");a.push('<div class="row-fluid">');a.push('<div id="events" class="span4 well"></div>');a.push('<div id="groups" class="span4 well"></div>');a.push('<div id="persons" class="span4 well"></div>')}a.push("</div>");
$("#cdb_content").html(a.join(""))}renderEvent(b);renderGroups(b);renderPersons(b);b&&renderPrinter()}function loadData(b){if(b==null)b=true;churchInterface.jsendRead({func:"getData",category_id:masterData.settings.category_id,distrikt_id:masterData.settings.distrikt_id},function(a,e){event_id=null;masterData.groups=e.groups;allPersons=e.allPersons;allEvents=e.events;renderView(b)},null,false)}
function renderPrinter(){var b=[];if(!view_easy)if(masterData.cc_printer!=null){var a=[];a.push({id:"",bezeichnung:"<i>Keinen Drucker ausgew&auml;hlt</i>"});$.each(churchcore_sortMasterData(masterData.cc_printer),function(e,d){a.push({id:d.id,bezeichnung:d.bezeichnung+" ("+d.ort+")"})});b.push(form_renderSelect({data:a,cssid:"printer_id",selected:masterData.settings.printer_id,controlgroup:false})+"</i>")}else b.push('<p><small><i>Keinen Drucker gefunden</i> <a target="_clean" href="http://intern.churchtools.de/?q=churchwiki#WikiView/filterWikicategory_id:0/doc:Keinen%20Drucker%20gefunden/"><i class="icon-question-sign icon-white"></i></a></small>');
b.push(form_renderCheckbox({cssid:"togglecheckin",label:"Eingecheckte auch anzeigen",controlgroup:false}));b.push(form_renderCheckbox({cssid:"easyview",checked:view_easy,label:"Vereinfachte Ansicht",controlgroup:false}));$("#printer").html(b.join(""));$("#printer_id").change(function(){masterData.settings.printer_id=$(this).val();churchInterface.jsendWrite({func:"saveSetting",sub:"printer_id",val:$(this).val()},null,null,false)});$("#togglecheckin").change(function(){view_checkin=$(this).attr("checked")==
"checked";renderGroups();renderPersons()});$("#easyview").change(function(){view_easy=$(this).attr("checked")=="checked";renderView(true)})}$(document).ready(function(){churchInterface.setModulename("churchcheckin");churchInterface.setStatus("Lade Kennzeichen...");churchInterface.jsendRead({func:"getMasterData"},function(b,a){masterData=a;if(churchcore_countObjectElements(masterData.settings)==0)masterData.settings={};loadData()},null,false)});
