var a;function WikiView(){StandardTableView.call(this);this.name="WikiView";this.allDataLoaded=false;this.listViewTableHeight=646;this.printview=this.init=false}Temp.prototype=StandardTableView.prototype;WikiView.prototype=new Temp;wikiView=new WikiView;var edit=false,currentPage=null,masterData=null;a=WikiView.prototype;
a.renderSidebar=function(){var b=[],c=$("#editor").html();b.push('<ul id="navlist" class="nav nav-list bs-docs-sidenav affix-top">');b.push('<li><a href="#start">Nach oben</a>');reg=new RegExp("<h(1|2)>(.*)</h(1|2)>","gi");for(var d;(d=reg.exec(c))!==null;)b.push('<li><a href="#'+d[2]+'">'+d[2]+"</a>");$("#sidebar").html(b.join(""));churchcore_handyformat()||$("#navlist").affix({offset:{top:15}})};
a.cancelEditMode=function(){if(edit==true){CKEDITOR.instances.editor.destroy();$("#editor").removeAttr("contenteditable");editor=false}};
a.editMode=function(b){var c=this;if(edit==false&&b){edit=true;$("a.editwiki").html("&Auml;nderungen speichern");$("#editor").attr("contenteditable","true");$("#editor").html(currentPage.text);CKEDITOR.inline("editor",{toolbar:[{name:"clipboard",groups:["clipboard","undo"],items:["Cut","Copy","Paste","PasteText","PasteFromWord","-","Undo","Redo"]},{name:"editing",groups:["find","spellchecker"],items:["Find","Replace","-","Scayt"]},{name:"links",items:["Link","Unlink"]},{name:"insert",items:["Image",
"Table","HorizontalRule","Smiley","SpecialChar","PageBreak","Iframe","MediaEmbed"]},{name:"tools",items:["Maximize","ShowBlocks","filebrowser"]},{name:"others",items:["-"]},"/",{name:"styles",items:["Format","Font","FontSize"]},{name:"basicstyles",groups:["basicstyles","cleanup"],items:["Bold","Italic","Underline","Strike","-","RemoveFormat"]},{name:"colors",items:["TextColor","BGColor"]},{name:"paragraph",groups:["list","indent","align"],items:["NumberedList","BulletedList","-","Outdent","Indent",
"-","JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock"]}]});$("#editor").focus()}else if(edit||!b){edit=false;$("a.editwiki").html("Text editieren");var d=CKEDITOR.instances.editor.getData();if(d==currentPage.text){alert("Keine neue Version, da nichts angepasst wurde.");c.renderPage(currentPage)}else churchInterface.jsendWrite({func:"save",doc_id:currentPage.doc_id,wikicategory_id:currentPage.wikicategory_id,val:CKEDITOR.instances.editor.getData()},function(e){if(e)currentPage.text=d;c.renderPage(currentPage)},
null,false);CKEDITOR.instances.editor.destroy();$("#editor").removeAttr("contenteditable")}};a.loadHistory=function(b,c){var d=this;edit=false;churchInterface.jsendWrite({func:"loadHistory",doc_id:b,wikicategory_id:c},function(e,g){if(e){currentPage.history=churchcore_sortData(g,"id",true,false);d.renderPage(currentPage)}})};
a.renderFiles=function(){var b=this;masterData.auth.edit[currentPage.wikicategory_id]?b.renderFilelist("",currentPage.file,null,function(c){delete currentPage.file[0].files[c];b.renderFiles()},50):b.renderFilelist("",currentPage.file,null,null,50);b.addTableContentCallbacks("#cdb_content")};
a.renderPage=function(b){var c=this,d=[];currentPage.doc_id!="main"&&d.push('<a class="btn wiki-link pull-right" data-doc-id="main" href="#">Hauptseite</a>');d.push('<anchor id="start"><h1>'+masterData.wikicategory[currentPage.wikicategory_id].bezeichnung+" - "+(currentPage.doc_id=="main"?"Hauptseite":currentPage.doc_id)+"</h1></section><br/>");d.push('<div class="well editable" id="editor">');if(b.text==null)b.text="";b=b.text.replace(/<h(1|2)>(.*)<\/h(1|2)>/gi,'<anchor id="$2"/><h$1>$2</h$1>');
b=b.replace(/\[\[([ ()a-zA-Z0-9&;-]*)\]\]/gi,'<a href="#" class="wiki-link" data-doc-id="$1">$1</a>');b=b.replace(/\img:(.*)/gi,'<a href="#" data-doc-id="$1">$1</a>');d.push(b);d.push("</div>");if(!c.printview)if(masterData.auth.edit[currentPage.wikicategory_id]||currentPage.file!=null){d.push('<div class="well">');d.push('<div id="filelist" class="filelist" data-id="0"></div>');masterData.auth.edit[currentPage.wikicategory_id]&&d.push('<p><div id="upload_button">Nochmal bitte...</div>');d.push("</div>")}d.push('<form class="form-inline">');
if(!c.printview){d.push('<a class="btn wiki-link" data-doc-id="main" href="#">Hauptseite</a>&nbsp;');if(masterData.auth.edit[currentPage.wikicategory_id]){d.push('<a class="btn editwiki" href="#">Text editieren</a> &nbsp; &nbsp; ');currentPage.modified_date!=null&&d.push(form_renderCheckbox({controlgroup:false,cssid:"showonstartpage",checked:currentPage.auf_startseite_yn==1,label:"Auf Startseite anzeigen"}))}}d.push("<p class='pull-right' style='text-align:right'><small>");if(currentPage.modified_date!=
null)currentPage.history==null?d.push('<a href="#" class="viewversion">Version '+currentPage.version_no+" vom "+currentPage.modified_date.toDateEn(true).toStringDe(true)+" - "+currentPage.vorname+" "+currentPage.name+"</a>"):d.push(form_renderSelect({data:currentPage.history,sort:false,selected:currentPage.version_no,controlgroup:false,cssid:"selectHistory"}));else d.push("Neu");masterData.encrypted==false?d.push('<br><a href="http://intern.churchtools.de/?q=help&doc=Verschluesselung" target="_clean">unverschl&uuml;sselt</a>'):
d.push("<br>verschl&uuml;sselt");c.printview||d.push(' - <a href="?q=churchwiki/printview#WikiView/filterWikicategory_id:'+currentPage.wikicategory_id+"/doc:"+currentPage.doc_id+'" target="_clean">Druckansicht</a>');d.push("</small>");d.push("</form>");$("#cdb_content").html(d.join(""));c.renderFiles();if(masterData.auth.edit[currentPage.wikicategory_id]&&!c.printview)uploader=new qq.FileUploader({element:document.getElementById("upload_button"),action:"?q=churchwiki/uploadfile",params:{domain_type:"wiki_"+
currentPage.wikicategory_id,domain_id:currentPage.doc_id},multiple:true,debug:true,onSubmit:function(){},onComplete:function(e,g,f){if(f.success){if(currentPage.file==null)currentPage.file=[];if(currentPage.file[0]==null)currentPage.file[0]={};e=currentPage.file[0].files;if(e==null)e=[];e[f.id]={filename:f.filename,bezeichnung:f.bezeichnung,id:f.id,domain_type:"wiki_"+currentPage.wikicategory_id,domain_id:currentPage.doc_id};currentPage.file[0].files=e;c.renderFiles()}else alert("Sorry, Fehler beim Hochladen aufgetreten! Datei zu gross oder Dateiname schon vergeben?")}});
$.extend($.tablesorter.themes.bootstrap,{table:"table table-bordered",header:"bootstrap-header",footerRow:"",footerCells:"",icons:"",sortNone:"bootstrap-icon-unsorted",sortAsc:"icon-chevron-up",sortDesc:"icon-chevron-down",active:"",hover:"",filterRow:"",even:"",odd:""});$("#cdb_content table:not(.table-nosort)").tablesorter({theme:"bootstrap",widthFixed:true,headerTemplate:"{content} {icon}",widgets:["uitheme","zebra"],widgetOptions:{zebra:["even","odd"],filter_reset:".reset"}});$("html, body").animate({scrollTop:0},
500);$("a.wiki-link").click(function(){var e=$(this).attr("data-doc-id");if(e=="Hauptseite")e="main";c.filter.doc=e;c.historyCreateStep();return false});$("a.editwiki").click(function(){c.editMode(true);return false});$("a.viewversion").click(function(){c.cancelEditMode();c.loadHistory(currentPage.doc_id,currentPage.wikicategory_id);return false});$("#selectHistory").change(function(){c.cancelEditMode();c.loadDoc(currentPage.doc_id,currentPage.wikicategory_id,$(this).val());return false});$("#showonstartpage").change(function(){currentPage.auf_startseite_yn=
$(this).attr("checked")=="checked"?1:0;churchInterface.jsendWrite({func:"showonstartpage",doc_id:currentPage.doc_id,version_no:currentPage.version_no,wikicategory_id:currentPage.wikicategory_id,auf_startseite_yn:currentPage.auf_startseite_yn},null,true,false);return false});c.renderNavi();c.renderSidebar();currentPage.text=="Neue Seite"&&c.editMode(true)};
a.renderNavi=function(){var b=this;if(masterData.auth.view!=false||masterData.auth.admin){var c=new CC_Navi;$.each(churchcore_sortMasterData(masterData.wikicategory),function(d,e){masterData.auth.view[e.id]&&c.addEntry(currentPage.wikicategory_id==e.id,"alistview"+e.id,masterData.wikicategory[e.id].bezeichnung)});masterData.auth.admin&&c.addEntry(false,"editCategory","Kategorien anpassen");c.renderDiv("cdb_navi",churchcore_handyformat());$("#cdb_navi a").click(function(){var d=$(this).attr("id");
$.each(masterData.auth.view,function(e,g){if(d=="alistview"+g){b.filter.filterWikicategory_id=g;b.filter.doc="main";b.historyCreateStep()}});d=="editCategory"&&churchInterface.setCurrentView(maintainView);return false})}};
a.loadDoc=function(b,c,d){var e=this;edit=false;churchInterface.jsendWrite({func:"load",doc_id:b,wikicategory_id:c,version_no:d},function(g,f){if(g){if(f==null){currentPage={};currentPage.text="Neue Seite";currentPage.wikicategory_id=c;currentPage.doc_id=b}else if(currentPage==null||currentPage.doc_id!=b||currentPage.wikicategory_id!=c){currentPage=f;if(f.files!=null&&!churchcore_isObjectEmpty(f.files)&&!e.printview){currentPage.file=[];g={};g.files=f.files[currentPage.doc_id];currentPage.file.push(g)}}else{currentPage.text=
f.text;currentPage.version_no=f.version_no}e.renderPage(currentPage)}})};function churchwiki_loadMasterData(){churchInterface.jsendWrite({func:"masterData"},function(b,c){if(b)masterData=c},false)}function cdb_loadMasterData(b){churchwiki_loadMasterData();b!=null&&b()}a=WikiView.prototype;a.renderList=function(){};
a.renderView=function(){var b=this;if(b.init==false){b.init=true;if(b.initView())return}$("#cdb_menu").html("");if(b.filter.doc!=null&&b.filter.filterWikicategory_id!=null){edit&&b.cancelEditMode();b.loadDoc(b.filter.doc,b.filter.filterWikicategory_id);shortcut.add("Ctrl+s",function(){if(edit){b.editMode(false);return false}});shortcut.add("Ctrl+e",function(){if(!edit){b.editMode(true);return false}});shortcut.add("esc",function(){if(edit)if(CKEDITOR.instances.editor.getData()==currentPage.text||
confirm("Wirklich die Anpassungen verwerfen?")){b.renderPage(currentPage);CKEDITOR.instances.editor.destroy();$("#editor").removeAttr("contenteditable");edit=false}return false})}};a.renderTooltip=function(b,c){var d=b.attr("tooltip");return this.renderTooltipForFiles(b,c,currentPage.file[0].files[d],masterData.auth.edit[currentPage.wikicategory_id])};a.tooltipCallback=function(b,c){return this.tooltipCallbackForFiles(b,c,currentPage.file,0)};
a.initView=function(){if($("#printview").val()=="true")this.printview=true;if(this.filter.filterWikicategory_id==null){this.filter.filterWikicategory_id=0;if(masterData.auth.view!=null){var b=99999;$.each(masterData.auth.view,function(d,e){if(e<b)b=e});this.filter.filterWikicategory_id=b}}var c=false;if($("#doc_id").val()!=null){this.filter.doc=$("#doc_id").val();c=true}else if(this.filter.doc==null){this.filter.doc="main";c=true}if(c){this.historyCreateStep();return true}return false};
$(document).ready(function(){churchInterface.setModulename("churchwiki");churchInterface.registerView("WikiView",wikiView);churchInterface.registerView("MaintainView",maintainView);churchwiki_loadMasterData();churchInterface.activateHistory("WikiView")});
