function AuthView(){StandardTableView.call(this);this.name="AuthView";this.allDataLoaded=false;this.renderTimer=null;this.currentDomain="person"}Temp.prototype=StandardTableView.prototype;AuthView.prototype=new Temp;authView=new AuthView;var masterData=null;AuthView.prototype.getData=function(a){return a?churchcore_sortData(masterData[this.currentDomain],"bezeichnung"):masterData[this.currentDomain]};
AuthView.prototype.checkFilter=function(a){if(this.filter==null)return true;if(this.filter.filterAuth!=null)return a.auth!=null&&a.auth[this.filter.filterAuth]!=null;if(this.filter.searchAuth!=null&&a.auth==null)return false;if(this.filter.searchEntry!=null){if(a.bezeichnung.toUpperCase().indexOf(this.filter.searchEntry.toUpperCase())>=0)return true;return false}return true};
AuthView.prototype.renderEntryDetail=function(a){var b=this,d=[];d.push('<div class="entrydetail" id="entrydetail_'+a+'">');d.push('<div class="well">');d.push("<legend>Berechtigung</legend>");d.push('<div id="tree"></div>');d.push("<br> <p>"+form_renderButton({label:"&Auml;nderungen speichern",disabled:true,htmlclass:"save"})+"&nbsp;");d.push(form_renderButton({label:"Urspr&uuml;nglichen Zustand wiederherstellen",disabled:true,htmlclass:"undo"}));d.push("</div>");var h=$("tr[id="+a+"]").after('<tr id="detail'+
a+'"><td colspan="7" id="detailTD'+a+'">'+d.join("")+"</td></tr>").next();f=[];var e={};$.each(masterData.auth_table,function(g,c){if(e[c.modulename]==null)e[c.modulename]=[];e[c.modulename].push(c)});var f=[];$.each(e,function(g,c){var k=[],l=false;$.each(c,function(r,i){if(i.datenfeld!=null){var o={},q=[];if(masterData[masterData.auth_table[i.id].datenfeld]!=null){var p={};$.each(masterData[masterData.auth_table[i.id].datenfeld],function(m,j){m=false;if(masterData[b.currentDomain][a]!=null&&masterData[b.currentDomain][a].auth!=
null&&masterData[b.currentDomain][a].auth[i.id]!=null&&(masterData[b.currentDomain][a].auth[i.id][-1]!=null||masterData[b.currentDomain][a].auth[i.id][j.id]!=null)){l=m=true;o.general=true}if(masterData.auth_table[i.id].datenfeld=="cc_calcategory"){var n="Gemeindekalender";if(masterData.category[j.id].privat_yn==1)n="Pers\u00f6nlich";else if(masterData.category[j.id].oeffentlich_yn==0)n="Gruppenkalender";if(p[n]==null)p[n]=[];if(m)o[n]=true;p[n].push({title:j.bezeichnung,select:m,key:i.id+"_"+j.id})}else q.push({title:j.bezeichnung,
select:m,key:i.id+"_"+j.id})});$.each(p,function(m,j){q.push({title:m,isFolder:true,children:j,expand:o[m]!=null})})}k.push({title:i.bezeichnung+" ("+i.auth+")",isFolder:true,children:q,expand:!churchcore_isObjectEmpty(o)})}else{select=false;if(masterData[b.currentDomain]!=null&&masterData[b.currentDomain][a]!=null&&masterData[b.currentDomain][a].auth!=null&&masterData[b.currentDomain][a].auth[i.id]!=null)l=select=true;k.push({title:i.bezeichnung+" ("+i.auth+")",select:select,key:i.id})}});f.push({title:masterData.names[g]!=
null?masterData.names[g]:g,isFolder:true,expand:l,children:k})});$("#tree").dynatree({onActivate:function(){},checkbox:true,selectMode:3,onSelect:function(){h.find("input").removeAttr("disabled")},onDblClick:function(g){g.toggleSelect()},fx:{height:"toggle",duration:200},children:f});h.find("input.save").click(function(){h.find("input").attr("disabled",true);var g=$("#tree").dynatree("getTree").getSelectedNodes(false);g=$.map(g,function(c){return c.data.key.indexOf("_")==0?null:c.data.key.indexOf("_")>
0?{auth_id:c.data.key.substr(0,c.data.key.indexOf("_")),daten_id:c.data.key.substr(c.data.key.indexOf("_")+1,99)}:{auth_id:c.data.key}});churchInterface.jsendWrite({func:"saveAuth",domain_type:b.currentDomain,domain_id:a,data:g},function(c,k){if(c)loadMasterData(function(){masterData.person[a].open=true;b.renderList()});else{alert("Fehler: "+k);h.remove()}},true,false)});h.find("input.undo").click(function(){h.remove();b.renderEntryDetail(a)})};AuthView.prototype.getListHeader=function(){return"<th>Nr.<th width=200px>Bezeichnung<th>Rechte"};
AuthView.prototype.addFurtherListCallbacks=function(){var a=this;$("#cdb_content #simulate").click(function(){window.location.href="?q=simulate&id="+$(this).parents("tr").attr("id")+"&location=home&back=auth"});$("#cdb_content .hoveractor").hover(function(){$(this).children("span.hoverreactor").fadeIn("fast",function(){})},function(){$(this).children("span.hoverreactor").fadeOut("fast")});$("#searchEntry").keyup(function(){if($(this).val()!=""){$("#searchAuth").removeAttr("checked");delete a.filter.searchAuth}})};
AuthView.prototype.renderListEntry=function(a){var b=[];if(a.auth!=null){var d={};$.each(a.auth,function(e,f){var g=masterData.auth_table[e].auth;if(typeof f=="object"){var c=[];$.each(f,function(k,l){if(l==-1)c.push("<i>alle</i>");else if(masterData[masterData.auth_table[e].datenfeld]==null)c.push('<font color="red">'+masterData.auth_table[e].datenfeld+" nicht vorhanden!</font>");else masterData[masterData.auth_table[e].datenfeld][l]==null?c.push('<font color="red">'+masterData.auth_table[e].datenfeld+
" mit Id:"+l+" nicht vorhanden!</font>"):c.push(masterData[masterData.auth_table[e].datenfeld][l].bezeichnung)});g=g+" ("+c.join(", ")+")"}if(d[masterData.auth_table[e].modulename]==null)d[masterData.auth_table[e].modulename]=[];d[masterData.auth_table[e].modulename].push(g)});$.each(d,function(e,f){var g=[];$.each(f,function(c,k){g.push(k)});b.push("<b>"+e+": </b>"+g.join(", ").trim(500))})}var h=[];h.push('<td class="hoveractor"><a href="#" id="detail'+a.id+'">'+a.bezeichnung+"</a>");if(t.currentDomain==
"person"&&churchcore_inArray(a.id,masterData.admins))h.push('&nbsp; <span class="label label-important">Administrator</span>');else t.currentDomain=="person"&&a.id>0&&h.push('&nbsp; <span class="hoverreactor" data-id="'+a.id+'" style="display:none">'+form_renderImage({src:"person_simulate.png",width:18,cssid:"simulate"})+"</span>");h.push("<td>"+b.join("<br>"));return h.join("")};
function loadMasterData(a){churchInterface.jsendRead({func:"getMasterData"},function(b,d){if(b){masterData=d;a!=null&&a()}else alert("Fehler: "+d)})}AuthView.prototype.renderMenu=function(){var a=this;menu=new CC_Menu("Men&uuml;");menu.addEntry("Hilfe","ahelp","question-sign");menu.renderDiv("cdb_menu",churchcore_handyformat())?$("#cdb_menu a").click(function(){if($(this).attr("id")=="anewentry")a.renderAddEntry();else $(this).attr("id")=="aexporter"&&a.exportData()}):$("#cdb_menu").hide()};
AuthView.prototype.renderFilter=function(){var a=this,b=new CC_Form;b.setHelp("ChurchAuth-Filter");var d=[],h="";$.each(churchcore_sortData(masterData.auth_table,"modulename"),function(e,f){if(h!=f.modulename){h=f.modulename;d.push({id:-1,bezeichnung:"-- "+f.modulename+" --"})}d.push({id:f.id,bezeichnung:f.auth+" - "+f.bezeichnung.trim(50)})});b.addSelect({cssid:"filterAuth",label:"Autorisierung",sort:false,freeoption:true,selected:a.filter.filterAuth,data:d});b.addCheckbox({cssid:"searchAuth",label:"nur autorisierte zeigen",
checked:true});this.filter.searchAuth=true;$("#cdb_filter").html(b.render(true,"inline"));if(this.filter.filterStatus!=null){typeof this.filter.filterStatus=="string"&&a.makeFilterStatus(masterData.settings.filterStatus);this.filter.filterStatus.render2Div("filterStatus",{label:"Status"})}$.each(this.filter,function(e,f){$("#"+e).val(f)});this.implantStandardFilterCallbacks(this,"cdb_filter");a=this;$("#cdb_filter a").click(function(){})};
AuthView.prototype.renderListMenu=function(){var a=this;searchEntry=$("searchEntry").val()!=null?$("searchEntry").val():this.getFilter("searchEntry");var b=new CC_Navi;b.addEntry(a.currentDomain=="person","apersonview","Personen");b.addEntry(a.currentDomain=="gruppe","agroupview","Gruppen");b.addEntry(a.currentDomain=="status","astatusview","Status");b.addSearch(searchEntry);b.renderDiv("cdb_search",churchcore_handyformat());churchcore_handyformat()||$("#searchEntry").focus();this.implantStandardFilterCallbacks(this,
"cdb_search");$("#cdb_search a").click(function(){if($(this).attr("id")=="apersonview"){a.currentDomain="person";a.renderView()}else if($(this).attr("id")=="agroupview"){a.currentDomain="gruppe";a.renderView()}else if($(this).attr("id")=="astatusview"){a.currentDomain="status";a.renderView()}return false})};$(document).ready(function(){churchInterface.registerView("AuthView",authView);churchInterface.setModulename("auth");loadMasterData(function(){churchInterface.activateHistory("AuthView");churchInterface.sendMessageToAllViews("allDataLoaded")})});
