var a;function ChurchInterface(){this.modulename="churchcore";this.standardviewname="main";this.views={};this.currentView=this.currentHistoryArray=null;this.allDataLoaded=false;this.errorWindow=this.hideStatusTimer=this.lastLogId=null;this.fatalErrorOccured=false}var churchInterface=new ChurchInterface;a=ChurchInterface.prototype;a.setModulename=function(b){this.modulename=b};a.setLastLogId=function(b){this.lastLogId=b};a.getLastLogId=function(){return this.lastLogId};
a.sendMessageToAllViews=function(b,c){b=="allDataLoaded"&&this.setAllDataLoaded(true);jQuery.each(this.getViews(),function(f,e){e.messageReceiver(b,c)})};a._pollForNews=function(){var b=this;this.pollForNews=window.setTimeout(function(){b.jsonRead({func:"pollForNews",last_id:b.lastLogId},function(c){if(c.lastLogId>b.lastLogId){b.sendMessageToAllViews("pollForNews",c.logs);b.lastLogId=c.lastLogId}b._pollForNews()})},1E4)};
a.setAllDataLoaded=function(b){if(this.allDataLoaded=b){this.lastLogId!=null&&this._pollForNews();this.implantCallbacks()}};a.isAllDataLoaded=function(){return this.allDataLoaded};a.historyCreateStep=function(b){jQuery.history.load(b)};
a.history=function(b){var c=this;if(b==null)b="";b=b.split("/");if(this.views[b[0]]==null){b[0]=this.standardviewname+"/";jQuery.history.load(b.join("/"))}else{this.currentView=this.views[b[0]];var f=false;jQuery.each(b,function(e,d){if(d.indexOf("searchEntry:")==0)c.currentView.filter.searchEntry=d.substr(12,99);else if(d.indexOf("filter")==0&&d.indexOf(":")>1)c.currentView.filter[d.substr(0,d.indexOf(":"))]=d.substr(d.indexOf(":")+1,99);else if(d.indexOf("doc")==0&&d.indexOf(":")>1){var g=d.substr(d.indexOf(":")+
1,99),h=true;c.currentHistoryArray!=null&&$.each(c.currentHistoryArray,function(j,l){if(l==g)h=false});if(h){c.currentView.filter[d.substr(0,d.indexOf(":"))]=g;f=true}}});if(this.currentHistoryArray==null||this.currentHistoryArray[0]!=b[0]||f)this.currentView.renderView();this.currentHistoryArray=b}};function history(b){churchInterface.history(b)}a=ChurchInterface.prototype;a.activateHistory=function(b){this.standardviewname=b;jQuery.history.init(history,{unescape:",:/"})};
a.registerView=function(b,c){this.views[b]=c};a.getViews=function(){return this.views};a.throwFatalError=function(b){var c=this.errorWindow==null?jQuery(document.createElement("div")).append(jQuery("#content")):this.errorWindow;c.html(b);c.dialog({autoOpen:true,modal:true,height:400,width:500,title:"Fehler beim Laden",buttons:{"Neu laden":function(){c.dialog("close")}},close:function(){location.reload(true)}});this.errorWindow=c};
a.jsonReadSyncron=function(b,c,f){var e=this,d=this.modulename;if(f!=null)d=f;jQuery.ajax({url:"index.php?q="+d+"/ajax",dataType:"json",data:b,async:false,success:function(g){c(g);if(e.errorWindow!=null){e.errorWindow.remove();e.errorWindow=null}}})};
a.jsonRead=function(b,c,f){var e=this;if(!e.fatalErrorOccured){var d=this.modulename;if(f!=null)d=f;debug&&console.log(b);jQuery.ajax({url:"index.php?q="+d+"/ajax",dataType:"json",data:b,success:function(g){debug&&console.log(g);c(g);if(e.errorWindow!=null){e.errorWindow.remove();e.errorWindow=null}},error:function(g,h,j){if(debug){console.log("error reading! Status:"+h+" Error:"+j);g!=null&&console.log(g)}if(e.errorWindow==null&&g.status!=0)e.throwFatalError("<b>Fehlermeldung: "+g.status+" - "+h+
(j!=null?" Fehler: "+j:"")+"</b><br/><br/>"+g.responseText);window.setTimeout(function(){e.jsonRead(b,c,f)},1E4)}})}};
a.jsonWrite=function(b,c){var f=this;if(!f.fatalErrorOccured){this.setStatus("Speichere Daten...");jQuery.ajax({url:"index.php?q="+this.modulename+"/ajax",dataType:"json",data:b,success:function(e){f.clearStatus();e!="ok"&&alert("Fehler beim Speichern in "+f.modulename+": "+e);c!=null&&c(e=="ok")},error:function(e,d,g){f.fatalErrorOccured=true;f.throwFatalError("<b>Fehlermeldung: "+e.status+" "+d+(g!=null?" Fehler: "+g:"")+"</b><br/><br/>"+e.responseText)}})}};
a.jsendWrite=function(b,c,f,e,d){return this.jsend("Speichere",b,c,f,e,d)};a.jsendRead=function(b,c,f,e,d){return this.jsend("Lade",b,c,f,e,d)};
a.jsend=function(b,c,f,e,d,g){var h=this,j=this.modulename;if(g!=null)j=g;if(e==null)e=true;if(d==null)d=true;if(!h.fatalErrorOccured){this.setStatus(b+" Daten...");var l={};$.each(c,function(i,k){l[i]=k instanceof Date?k.toStringEn(true):k});jQuery.ajax({url:"index.php?q="+j+"/ajax",dataType:"json",data:l,async:e,type:d?"GET":"POST",success:function(i){h.clearStatus();if(i.status=="error")alert("Fehler beim "+b+" in "+j+": "+i.message);else f!=null&&f(i.status=="success",i.data)},error:function(i,
k,m){h.fatalErrorOccured=true;h.throwFatalError("<b>Fehlermeldung: "+i.status+" "+k+(m!=null?" Fehler: "+m:"")+"</b><br/><br/>"+i.responseText)}})}};a.jsonWriteSyncron=function(b,c){this.setStatus("Speichere Daten...");jQuery.ajax({url:"index.php?q="+this.modulename+"/ajax",dataType:"json",data:b,async:false,success:c});this.clearStatus()};a.sendEmail=function(b,c,f){this.jsonWrite({func:"send_email",subject:c,body:f,to:b})};
a.setStatus=function(b,c){var f=this;if(this.hideStatusTimer!=null){window.clearTimeout(this.hideStatusTimer);this.hideStatusTimer=null}jQuery("#cdb_status").html(b);if(c)this.hideStatusTimer=window.setTimeout(function(){f.clearStatus();this.hideStatusTimer=null},1E4)};a.clearStatus=function(){var b=this;dt=new Date;jQuery("#cdb_status").html("<i>"+dt.toStringDe(true)+"</i>");window.setTimeout(function(){b.clearStatus()},1E4)};
a.setCurrentView=function(b,c){this.currentView=b;if(c==null||c)this.currentView.clearFilter();this.currentView.historyCreateStep()};a.getCurrentView=function(){return this.currentView};a.isCurrentView=function(b){return this.currentView.name==b};a.implantCallbacks=function(){};
