function MaintainStandardView(){StandardTableView.call(this);this.name="MaintainStandardView";this.sortKey="id";this.sortAsc=false}Temp.prototype=StandardTableView.prototype;MaintainStandardView.prototype=new Temp;maintainStandardView=new MaintainStandardView;MaintainStandardView.prototype.getData=function(){return masterData.masterDataTables};MaintainStandardView.prototype.renderMenu=function(){alert("Please Overwrite and add Div divcover!")};
(function(b){MaintainStandardView.prototype.renderListMenu=function(){searchEntry=this.getFilter("searchEntry");var c=new CC_Navi;c.addEntry(true,null,"Stammdatenpflege");c.addSearch(searchEntry);c.renderDiv("cdb_search");this.implantStandardFilterCallbacks(this,"cdb_search")};MaintainStandardView.prototype.renderFilter=function(){var c=[],m=new CC_Form;m.setLabel("Filterfunktionen");m.addCheckbox({cssid:"searchChecked",label:"markierte"});c.push(m.render(true));b("#cdb_filter").html(c.join(""));
this.implantStandardFilterCallbacks(this,"cdb_filter")};MaintainStandardView.prototype.checkFilter=function(c){if(c==null)return false;searchEntry=this.getFilter("searchEntry").toUpperCase();if(searchEntry!=""&&c.bezeichnung.toUpperCase().indexOf(searchEntry)<0&&c.id!=searchEntry)return false;if(this.filter.searchChecked!=null&&c.checked!=true)return false;return true};MaintainStandardView.prototype.getListHeader=function(){return str="<th>Nr.<th>Stammtabelle<th>Anzahl Zeilen"};MaintainStandardView.prototype.renderListEntry=
function(c){rows=[];rows.push("<td>"+c.bezeichnung);i=0;masterData[c.shortname]!=null&&b.each(masterData[c.shortname],function(){i++});rows.push("<td>"+i);return rows.join("")};MaintainStandardView.prototype.renderEntryDetail=function(c,m){var h=this;if(m==null)m=c;table=this.getData()[c];var d=[];b("tr[id=detail"+c+"]").remove();b("tr[id="+c+"]").after('<tr id="detail'+c+'"><td colspan="10" id="groupinfosTD'+c+'">Lade Daten..</td></tr>');d[d.length]='<div id="detail" class="detail-view-admin">';
var l=[];b.each(table.desc,function(f){if(f.indexOf("_id")>0&&f.indexOf("_ids")==-1&&masterData[table.shortname]!=null){f=f.substr(0,f.indexOf("_id"));l.push(form_renderSelect({fields:{"data-table-name":f},data:masterData[f],type:"medium",selected:table.filter!=null&&table.filter[f]!=null?table.filter[f]:"",freeoption:true,htmlclass:"filter",controlgroup:false}))}});l.length>0&&d.push('<p><form class="form-inline">&nbsp;Filter: '+l.join("&nbsp;")+"</form>");d[d.length]="<p style='line-height:100%'><small><table><tr>";
b.each(table.desc,function(f,e){d.push('<td><b><i><a href="#" id="'+e.field+'">'+e.field);if(h.sortKey==e.field)h.sortAsc?d.push(" &and;"):d.push(" &or;");d.push("</a></b></i>")});table.special_func!=null&&d.push("<td><b><i>Funktionen</i></b>");d.push("<td><b><i>del.</b></i><tr>");masterData[table.shortname]!=null&&b.each(churchcore_sortData(masterData[table.shortname],this.sortKey,this.sortAsc,this.sortKey!="id"&&this.sortKey!="sortkey"),function(f,e){var j=false,a=[];b.each(table.desc,function(g,
n){a.push("<td>");if(n.type.indexOf("int")==0&&g.indexOf("_yn")>0){a.push('<a href="#" id="change_yn_'+e.id+'" val="'+e[g]+'" col="'+g+'">');a.push(h.renderYesNo(e[g]));a.push("</a>")}else if(g.indexOf("_id")>0&&g.indexOf("_ids")==-1&&e[g]!=null&&e[g]!=""){var o=g.substr(0,g.indexOf("_id"));if(table.filter!=null&&table.filter[o]!=null&&table.filter[o]!=e[g])j=true;var p=[];masterData[o]!=null&&masterData[o][e[g]]!=null&&masterData[o][e[g]].bezeichnung!=null?p.push(form_renderSelect({fields:{table:table.tablename,
shorttablename:table.shortname,row:e.id,col:g},htmlclass:"datafield",data:masterData[o],selected:e[g],type:"small",freeoption:n.Null=="YES",controlgroup:false})):p.push(e[g]);a.push(p.join(""))}else{a.push('<a href="#" id="edit_'+e.id+'">');a.push(e[g]);a.push("</a>")}});if(table.special_func!=null){a.push('<td><a href="#" id="special_func_'+e.id+'" func="'+table.special_func.func+'">');table.special_func.image!=null?a.push(h.renderImage(table.special_func.image,16,table.special_func.name)):a.push(table.special_func.name);
a.push("</a>")}a.push("<td>"+form_renderImage({label:"Datensatz l&ouml;schen",cssid:"delete_"+e.id,src:masterData.modulespath+"/images/trashbox.png",htmlclass:"small"})+"</a>");a.push("<tr>");j||d.push(a.join(""))});d[d.length]="</table></small>";d[d.length]="<p>"+form_renderImage({label:"Neuen Eintrag erstellen",cssid:"create",src:masterData.modulespath+"/images/plus.png",htmlclass:"small"});d[d.length]="</div>";b("#groupinfosTD"+c).html(d.join(""));b("#groupinfosTD"+c+" a").click(function(){table=
h.getData()[c];if(b(this).attr("id").indexOf("grp_close")==0){b("#groupinfosTD"+c).remove();return false}else if(b(this).attr("id").indexOf("edit_")==0)h.renderEditEntry(b(this).attr("id").substr(5,99),table.id);else if(b(this).attr("id").indexOf("special_func_")==0)h[b(this).attr("func")].apply(h,[b(this).attr("id").substr(13,99),table.id]);else if(b(this).attr("id").indexOf("change_yn_")==0){obj={};obj.func="saveMasterData";obj.table=table.tablename;obj.id=b(this).attr("id").substr(10,99);obj.col0=
b(this).attr("col");obj.value0=b(this).attr("val")==0?1:0;churchInterface.jsendWrite(obj,function(f,e){if(f){masterData[table.shortname][obj.id][obj.col0]=obj.value0;h.renderList(masterData.masterDataTables[table.id])}else alert("Fehler beim Speichern: "+e)});return false}else if(b(this).attr("id").indexOf("delete_")==0)confirm("Wirklich den Datensatz "+b(this).attr("id").substr(7,99)+" entfernen? Bitte sicherstellen, dass keine Daten mehr auf diesen Datensatz referenziert, sonst kann es zu Problemen kommen!")&&
churchInterface.jsendWrite({func:"deleteMasterData",table:table.tablename,id:b(this).attr("id").substr(7,99)},function(f,e){if(f){var j=table.id,a=table.filter;cdb_loadMasterData(function(){masterData.masterDataTables[j].open=true;masterData.masterDataTables[j].filter=a;h.renderList(masterData.masterDataTables[j])})}else alert("Fehler beim Speichern: "+e)});else if(b(this).attr("id")=="create")h.renderEditEntry(null,table.id);else if(table.desc[b(this).attr("id")]!=null){if(h.sortKey==b(this).attr("id"))h.sortAsc=
!h.sortAsc;h.sortKey=b(this).attr("id");h.renderList(masterData.masterDataTables[table.id])}return false});b("#cdb_content select.filter").change(function(){if(table.filter==null)table.filter={};if(b(this).val()!="")table.filter[b(this).attr("data-table-name")]=b(this).val();else delete table.filter[b(this).attr("data-table-name")];h.renderList(masterData.masterDataTables[table.id])});b("#cdb_content select.datafield").change(function(){obj.func="saveMasterData";obj.table=b(this).attr("table");obj.id=
b(this).attr("row");obj.col0=b(this).attr("col");obj.value0=b(this).val();obj.shorttablename=b(this).attr("shorttablename");churchInterface.jsendWrite(obj,function(f,e){if(f)masterData[obj.shorttablename][obj.id][obj.col0]=obj.value0;else alert("Fehler beim Speichern: "+e)});return false})};MaintainStandardView.prototype.renderEditEntry=function(c,m){var h=this,d=masterData.masterDataTables[m],l={};if(c!=null)l=masterData[d.shortname][c];var f=new CC_Form(null,null,"in_edit");b.each(d.desc,function(j,
a){if(a.field=="id")l[a.field]!=null&&f.addCaption({text:l[a.field],label:"id"});else if(a.type.indexOf("int")==0&&a.field.indexOf("_yn")>0)f.addCheckbox({label:a.field,cssid:"Input"+a.field,checked:l[a.field]==1});else if(a.field.indexOf("_id")>0&&a.field.indexOf("_ids")==-1&&masterData[a.field.substr(0,a.field.length-3)]!=null){if(l[a.field]==null&&d.filter!=null&&d.filter[a.field.substr(0,a.field.length-3)]!=null)l[a.field]=d.filter[a.field.substr(0,a.field.length-3)];f.addSelect({label:a.field,
cssid:"Input"+a.field,selected:l[a.field],data:masterData[a.field.substr(0,a.field.length-3)]})}else{j="-";j=l[a.field]==null&&a.type=="int(11)"&&a.Null=="YES"?"null":l[a.field];var g=a.type.match(/\((.*)\)/),n=null;if(g!=null)n=g[1];if(a.type=="blob"||n!=null&&n>100)f.addTextarea({label:a.field,cssid:"Input"+a.field,data:j,rows:5,htmlclass:a.Null=="YES"?"nullable":""});else{if(a.field=="sortkey"&&j==null)j="0";f.addInput({label:a.field,cssid:"Input"+a.field,value:j,htmlclass:a.Null=="YES"?"nullable":
""})}}});var e=this.showDialog("Ver&auml;nderung des Datensatzes "+d.bezeichnung,f.render(null,"horizontal"),500,450,{Speichern:function(){b(this).attr("id");obj={};obj.func="saveMasterData";obj.table=d.tablename;obj.id=c;k=0;b("#in_edit input, #in_edit select,  #in_edit textarea").each(function(){obj["col"+k]=b(this).attr("id").substr(5,99);obj["value"+k]=b(this).val()==""&&b(this).hasClass("nullable")?null:b(this).attr("type")=="checkbox"?b(this).attr("checked")=="checked"?1:0:b(this).val();k++});
b("#cbn_editor").html("<p><br/><b>Daten werden gespeichert...</b><br/><br/>");churchInterface.jsendWrite(obj,function(j,a){e.dialog("close");if(j){var g=masterData.masterDataTables[m].filter;cdb_loadMasterData(function(){if(masterData.masterDataTables[m]!=null){masterData.masterDataTables[m].filter=g;masterData.masterDataTables[m].open=true}h.renderList()})}else alert("Fehler beim Speichern: "+a)})},Abbruch:function(){b(this).dialog("close")}})}})(jQuery);
