var a;function StandardTableView(){AbstractView.call(this);this.name="StandardTableView";this.init=false;this.filter={};this.furtherFilterVisible=false;this.listOffset=0;this.sortVariable="id";this.tooltipTimer=null;this.tooltip_hold=false;this.renderListTimer=this.testTimer=this.tooltip_elem=null;this.listViewAggregate=false;this.listViewTableHeight=null}Temp.prototype=AbstractView.prototype;StandardTableView.prototype=new Temp;a=StandardTableView.prototype;a.initView=function(){};
a.historyCreateStep=function(){var d="";jQuery.each(this.filter,function(o,p){d=d+"/"+o+":"+p});churchInterface.historyCreateStep(this.name+d+"/")};
a.renderView=function(d){var o=this;if(o.init==false){o.initView();o.init=true}if(churchcore_handyformat()){this.renderMenu();this.renderListMenu();$("#cdb_menu").append("&nbsp; "+form_renderButton({label:"Filter &raquo;",htmlclass:"togglefilter"})+"<br/><br/>");$("#cdb_menu input.togglefilter").click(function(){if($("#cdb_filter").html()==""){o.renderFilter();$(this).val("Filter "+String.fromCharCode(171))}else{$("#cdb_filter").html("");$(this).val("Filter "+String.fromCharCode(187))}})}else{if(d==
null||d)this.renderMenu();this.renderListMenu();this.renderFilter();$("#searchEntry").focus()}this.furtherFilterVisible&&this.renderFurtherFilter();this.renderList()};a.groupingFunction=function(){return null};a.getCountCols=function(){return 1};a.getFilter=function(d){return this.filter[d]!=null?this.filter[d]:""};a.deleteFilter=function(d){if(this.filter[d]!=null){delete this.filter[d];return true}else return false};a.renderFurtherFilter=function(){};a.messageReceiver=function(){};_aktiv=false;
(function(d){function o(){var c=d("#cdb_content thead th");d("#AddressTableChild tr").next(".data").first().children().each(function(){c.first().width(d(this).width());c=c.next()})}function p(c,e){var b=c.attr("data-datenfeld"),f=c.attr("id").substr(9,99),g=false;if(masterData[b]!=null){if(masterData[b][-1]==null)masterData[b][-1]={id:-1,sortkey:-999,htmlclass:"super",bezeichnung:"<i>Alle</i>"};var h=[];d.each(churchcore_sortData(masterData[b],"sortkey",false,true,"bezeichnung"),function(k,m){k=false;
if(e!=null&&e[f]!=null&&e[f][m.id]!=null)g=k=true;var l="";if(m.htmlclass!=null)l=m.htmlclass;h.push({id:f+"_"+m.id,checked:k,htmlclass:l,bezeichnung:m.bezeichnung})});g&&c.show();txt="";if(h.length<10)d.each(h,function(k,m){txt=txt+'<input type="checkbox" id="'+m.id+'" '+(m.checked?"checked":"")+' class="'+m.htmlclass+'"></input>&nbsp;'+m.bezeichnung+"&nbsp; &nbsp;"});else{d.each(h,function(k,m){if(m.checked){txt=txt+"<p>"+m.bezeichnung+'<a href="#" class="delAuth" data-id="'+m.id+'"> '+form_renderImage({src:"trashbox.png",
width:16})+"</a>";txt+=form_renderHidden({value:"checked",cssid:m.id})}});txt+="<p>Weitere hinzuf&uuml;gen:<br/>";txt+=form_renderSelect({data:h,cssid:"selectAuth"+f,controlgroup:true,func:function(k){return!k.checked}});txt+=form_renderButton({label:"Hinzuf&uuml;gen",cssid:"add"+f,htmlclass:"addAuth"})}c.html(txt);c.find("input:checkbox").click(function(){if(d(this).hasClass("super"))d(this).attr("checked")=="checked"&&d(this).parents("span").find("input:checkbox").each(function(){d(this).hasClass("super")||
d(this).removeAttr("checked")});else d(this).parents("span").find("input:checkbox.super").each(function(){d(this).removeAttr("checked")})});c.find("input.addAuth").click(function(){var k=d("#selectAuth"+f).val();k=k.substr(k.indexOf("_")+1,99);if(e==null)e={};if(e[f]==null)e[f]=[];e[f][k]=k;p(c,e);return false});c.find("a.delAuth").click(function(){var k=d(this).attr("data-id");k=k.substr(k.indexOf("_")+1,99);delete e[f][k];p(c,e);return false})}}StandardTableView.prototype.implantStandardFilterCallbacks=
function(c,e){var b=this,f=b.filter;d("#"+e+" select").change(function(){var g=f[d(this).attr("id")];if(d(this).val()=="")delete f[d(this).attr("id")];else f[d(this).attr("id")]=d(this).val();churchInterface.sendMessageToAllViews("filterChanged",new Array(d(this).attr("id"),g));b.listOffset=0;b.renderList(null,false)});d("#"+e+" input:checkbox").click(function(){var g=f[d(this).attr("id")];if(d(this).attr("checked"))f[d(this).attr("id")]=true;else delete f[d(this).attr("id")];churchInterface.sendMessageToAllViews("filterChanged",
new Array(d(this).attr("id"),g));b.listOffset=0;b.renderList(null,false)});d("#"+e+" input:text").keyup(function(){if(f[d(this).attr("id")]!=d(this).val()&&(d(this).val().length>0||d(this).val()=="")){var g=f[d(this).attr("id")],h=d(this).attr("id");if(d(this).val()=="")delete f[d(this).attr("id")];else f[d(this).attr("id")]=d(this).val();b.listOffset=0;if(_aktiv!=null)_aktiv=window.clearTimeout(_aktiv);_aktiv=window.setTimeout(function(){churchInterface.sendMessageToAllViews("filterChanged",new Array(h,
g));b.renderList(null,false);_aktiv=false},300)}})};StandardTableView.prototype.setFilter=function(c,e){this.filter[c]=e};StandardTableView.prototype.clearFilter=function(){this.filter={};this.listOffset=0};StandardTableView.prototype.getSelectFilter=function(c,e,b,f,g){if(c==null)return"";if(g==null)g=true;_text=e!=""?'<font style="font-size:8pt;">'+e+': </font><select id="filter'+e+'" style="">':'<select id="filterVoid" style="">';if(g)_text+='<option value=""></option>';jQuery.each(c,function(h,
k){if(typeof f!="function"||f(k)){_text=_text+'<option value="'+k.id+'"';if(b==k.id)_text+=" selected ";_text=_text+">"+k.bezeichnung.trim(25)+"</option>"}});_text+="</select>&nbsp;&nbsp;";return _text};StandardTableView.prototype.addSecondMenu=function(){return""};StandardTableView.prototype.addFurtherListCallbacks=function(){};StandardTableView.prototype.renderOneListEntry=function(){};StandardTableView.prototype.renderList=function(c,e){t=this;if(t.renderListTimer==null)t.renderListTimer=window.setTimeout(function(){var b=
[];debug&&t.startTimer();if(c!=null)if(t.checkFilter(c)){b[b.length]=c.checked==true?'<td><input type="checkbox" id="check'+c.id+'" checked="checked" class="checked">':'<td><input type="checkbox" id="check'+c.id+'" class="checked">';t.groupingFunction(c)==null&&b.push('<td><a href="" id="detail'+c.id+'">'+d("tr[id="+c.id+"]").find("td").next().first().text()+"</a>");var f=t.renderListEntry(c);if(f!=null){b.push(f);d("#cdb_content tr[id="+c.id+"]").html(b.join(""));t.addTableContentCallbacks("#cdb_content tr[id="+
c.id+"]");c.open&&t.renderEntryDetail(c.id)}}else d("#cdb_content tr[id="+c.id+"]").html("");else{var g=0;listObject=t.getData(true,e);d("#cdb_content").html("Tabellenaufbau...");t.listViewTableHeight=masterData.settings==null||masterData.settings.listViewTableHeight==null||masterData.settings.listViewTableHeight==0?null:646;if(masterData.settings==null)masterData.settings={};if(masterData.settings["listMaxRows"+t.name]==null)masterData.settings["listMaxRows"+t.name]=25;else masterData.settings["listMaxRows"+
t.name]*=1;if(churchcore_handyformat()&&churchInterface.getCurrentView().name!="WeekView")masterData.settings["listMaxRows"+t.name]=10;if(listObject==null)b[b.length]="Keinen Eintrag gefunden.";else{b[b.length]='<div style="" id="DivAddressTable"><table class="view table table-bordered table-condensed table-striped" style="tab_le-layout:fixed;margin-bottom:0px;" id="AddressTable">';b[b.length]='<thead><tr><th width="12px"><input type="checkbox" class="checked" id="markAll">';b.push(t.getListHeader());
b.push("</thead>");if(t.listViewTableHeight!=null){b.push("</table></div>");b.push('<div style="max-height:'+t.listViewTableHeight+'px; overflow-y:auto; overflow-x:auto">');b.push('<table class="view table table-bordered table-condensed ta_ble-striped" style="margin-bottom:0px" id="AddressTableChild">')}b.push("<tbody>");var h=0,k=null;d.each(listObject,function(m,l){if(l!=null&&t.checkFilter(l)){h++;if(h>=t.listOffset&&h<=masterData.settings["listMaxRows"+t.name]+t.listOffset){entry_txt=t.renderListEntry(l);
if(entry_txt==null)h--;else{m=t.groupingFunction(l);if(m!=k){k=m;b.push('<tr class="grouping"><td class="grouping" align="center" colspan="'+t.getCountCols()+'">'+m)}b.push('<tr class="data" id="'+l.id+'">');b.push('<td><input type="checkbox" class="checked" id="check'+l.id+'"');l.checked&&b.push(" checked=checked");b.push(">");k==null&&b.push('<td><a href="" id="detail'+l.id+'">'+h+"</a>");b.push(entry_txt);g=l.id}}}});b.push("<tbody>");b.push("</table>");b.push("</div>");b.push('<table class="table table-bordered table-condensed">');
if(h>=masterData.settings["listMaxRows"+t.name]){b[b.length]="<tr><td>Zeige "+masterData.settings["listMaxRows"+t.name]+" von "+h+" gefundenen Eintr&auml;gen";b.push('&nbsp; &nbsp; &nbsp;Bl&auml;ttern: <a id="offset0" href="#"><<</a>&nbsp;|&nbsp;<a id="offsetMinus" href="#"><</a>&nbsp;|&nbsp;<a id="offsetPlus" href="#">></a>')}else b[b.length]="<tr><td>Zeige "+h+" gefundene Eintr&auml;ge";if(!churchcore_handyformat()){b.push("&nbsp; &nbsp; &nbsp; &nbsp;(Zeilenanzahl: ");b.push('<a href="#" class="changemaxrow" data-id="10">10</a>&nbsp;|&nbsp;');
b.push('<a href="#" class="changemaxrow" data-id="25">25</a>&nbsp;|&nbsp;');b.push('<a href="#" class="changemaxrow" data-id="50">50</a>&nbsp;|&nbsp;');b.push('<a href="#" class="changemaxrow" data-id="200">200</a>)')}b.push("&nbsp; &nbsp; &nbsp; ");if(masterData.settings["listMaxRows"+t.name]<=20||h<=20)b.push('&nbsp;<a href="#" id="showAll">alle &ouml;ffnen</a>');b.push('&nbsp; &nbsp; <a href="#" id="hideAll">alle schlie&szlig;en</a>');b.push("</table>");t.listViewTableHeight!=null&&b.push("<p></p>");
b.push(t.addSecondMenu())}d("#cdb_content").html(b.join(""));debug&&t.endTimer("renderTableView");o(g);d("#cdb_content input.checked").click(function(){if(d(this).attr("id")=="markAll"){if(h>=masterData.settings["listMaxRows"+t.name]&&confirm("Es sind mehr Eintraege vorhanden, als momentan angezeigt. Sollen alle Eintraege markiert werden?")){bol=d(this).is(":checked");d.each(listObject,function(m,l){if(l!=null&&t.checkFilter(l))l.checked=bol})}d(this).is(":checked")?d("#cdb_content input.checked").not("#markAll").each(function(){d(this).attr("checked",
"true");t.getData(false)[d(this).attr("id").substr(5,99)].checked=true}):d("#cdb_content input.checked").not("#markAll").each(function(){d(this).removeAttr("checked");t.getData(false)[d(this).attr("id").substr(5,99)].checked=false})}else t.getData(false)[d(this).attr("id").substr(5,99)].checked=d(this).is(":checked")});d("#cdb_content a").click(function(){if(d(this).attr("id")=="orderby")loadList("","",d(this).attr("href"));else if(d(this).attr("id")=="offset0"){t.listOffset=0;t.renderList()}else if(d(this).attr("id")==
"offsetMinus"){t.listOffset-=masterData.settings["listMaxRows"+t.name];if(t.listOffset<0)t.listOffset=0;t.renderList()}else if(d(this).attr("id")=="offsetPlus"){t.listOffset+=masterData.settings["listMaxRows"+t.name];t.renderList()}else if(d(this).attr("id")=="showAll"){j=n=0;d.each(listObject,function(m,l){n++;if(t.checkFilter(l)){j++;n>=t.listOffset&&j<=masterData.settings["listMaxRows"+t.name]&&t.renderEntryDetail(l.id)}})}else if(d(this).attr("id")=="hideAll"){d.each(listObject,function(m,l){l.open=
false});t.renderList()}});d("#cdb_content a.changemaxrow").click(function(){masterData.settings["listMaxRows"+t.name]=d(this).attr("data-id");t.renderList();churchInterface.jsendWrite({func:"saveSetting",sub:"listMaxRows"+t.name,val:d(this).attr("data-id")})});t.addTableContentCallbacks("#cdb_content");d(window).resize(function(){o()});listObject!=null&&d.each(listObject,function(m,l){if(l!=null&&t.checkFilter(l))if(l.open||h==1)t.renderEntryDetail(l.id)});debug&&t.endTimer("renderTablecallback")}t.renderListTimer=
null},10)};StandardTableView.prototype.startTimer=function(){this.testTimer=new Date};StandardTableView.prototype.endTimer=function(c){console.log(c+": "+churchcore_getTimeDiff(this.testTimer));d("#cdb_content").prepend("<small><br>"+c+": "+churchcore_getTimeDiff(this.testTimer)+"</small>");this.startTimer()};StandardTableView.prototype.addTableContentCallbacks=function(c){var e=this;d(c+" a").click(function(){if(d(this).attr("id")==null)return true;else if(d(this).attr("id").indexOf("detail")==0){var f=
d(this).attr("id").substr(6,99),g=e.getData();if(d("tr[id="+d(this).attr("id")+"]").text()!=""){d("tr[id="+d(this).attr("id")+"]").remove();g[f].open=false}else{g[f].open=true;e.renderEntryDetail(d(this).attr("id").substr(6,99))}}else if(d(this).attr("id")=="mailto")return true;else if(d(this).attr("id")=="extern")return true;else if(d(this).attr("id").indexOf("sort")==0){e.sortVariable=d(this).attr("id").substr(4,99);e.renderList()}return false});var b=false;d(c+" span[tooltip],a[tooltip]").hover(function(){b=
true;e.prepareTooltip(d(this),null,d(this).attr("data-tooltiptype"))},function(){b=false;window.setTimeout(function(){b||e.clearTooltip()},100)});d(c+" span[tooltip],a[tooltip]").click(function(){e.tooltip_hold=false;e.clearTooltip(true)});this.addFurtherListCallbacks(c)};StandardTableView.prototype.renderTooltip2Div=function(c,e){c=this.renderTooltip(c,e);if(c instanceof Array){d("#"+e).html(c[0]);d("#"+e+"_title").html(c[1])}else d("#"+e).html(c)};StandardTableView.prototype.tooltipCallback=function(){};
StandardTableView.prototype.prepareTooltip=function(c,e,b){var f=this;if(e==null)e=200;if(b==null)b=this.name;var g='<div id="tooltip_inner" class="'+b+'"></div>';f.clearTooltip();f.tooltip_elem=c;f.tooltipTimer=window.setTimeout(function(){f.tooltip_elem.popover({content:g,html:true,title:'<span id="tooltip_inner_title"/>',placement:"bottom",trigger:"manual",animation:true}).popover("show");f.renderTooltip2Div(f.tooltip_elem,"tooltip_inner");f.tooltipCallback(c.attr("tooltip"),f.tooltip_elem.next(".popover"));
d(".popover").hover(function(){if(f.tooltip_elem!=null)f.tooltip_hold=true},function(){if(f.tooltip_hold){f.tooltip_hold=false;f.clearTooltip()}});f.tooltipTimer=null},e)};StandardTableView.prototype.renderTooltip=function(){return"noch nicht implementiert!"};StandardTableView.prototype.clearTooltip=function(c){if(c||!this.tooltip_hold){this.tooltip_hold=false;if(this.tooltip_elem!=null&&this.tooltip_elem.data("popover")!=null){this.tooltip_elem.popover("hide");this.tooltip_elem.data("popover",null);
this.tooltip_elem=null}if(this.tooltipTimer!=null){window.clearTimeout(this.tooltipTimer);this.tooltipTimer=null}}};StandardTableView.prototype.mailPerson=function(c,e,b){var f=[];f.push(form_renderInput({cssid:"betreff",label:"Betreff",type:"xlarge",text:b!=null?b:""}));f.push('<p>Inhalt<div id="inhalt" class="well">');masterData.settings.signature!=null&&f.push(masterData.settings.signature);f.push("</div>");if(masterData.settings.sendBCCMail==null)masterData.settings.sendBCCMail=1;f.push("<p>"+
form_renderCheckbox({cssid:"sendBCCMail",checked:masterData.settings.sendBCCMail==1,label:"eine BCC-Kopie an mich senden."}));this.showDialog("E-Mail an "+(e!=null?e:"Person"),f.join(""),600,550,{Senden:function(){var g=c.split(",");if(g.length<5||confirm("Soll wirklich eine E-Mail an "+g.length+" Personen gesendet werden?")){g={};g.ids=c;masterData.settings.sendBCCMail=d("#sendBCCMail").attr("checked")?1:0;if(masterData.settings.sendBCCMail==1)g.ids=typeof masterData.user_pid=="string"?g.ids+","+
masterData.user_pid:g.ids+","+masterData.user_pid[0];churchInterface.jsonWrite({func:"saveSetting",sub:"sendBCCMail",val:masterData.settings.sendBCCMail});g.betreff=d("#betreff").val();g.inhalt=CKEDITOR.instances.inhalt.getData();g.domain_id=null;g.func="sendEMailToPersonIds";churchInterface.jsendWrite(g,function(h){h&&alert("Die EMail wurde gesendet!")},null,false);d(this).dialog("close")}},Abbrechen:function(){d(this).dialog("close")}});form_implantWysiwygEditor("inhalt",false);b!=null&&d("#inhalt").focus();
d("a").click(function(){if(d(this).attr("id")=="Vorname"||d(this).attr("id")=="Nachname")d("#inhalt").insertAtCaret("["+d(this).attr("id")+"]")})};StandardTableView.prototype.renderFile=function(c,e){txt="";if(c!=null){txt=txt+'<span class="file" tooltip="'+c.id+'" data-id="'+c.id+'">';var b=c.bezeichnung.lastIndexOf(".");if(b>0)switch(c.bezeichnung.substr(b,99)){case ".mp3":txt+=this.renderImage("mp3",18);break;case ".m4a":txt+=this.renderImage("mp3",18);break;case ".pdf":txt+=this.renderImage("pdf",
18);break;case ".doc":txt+=this.renderImage("word",18);break;case ".docx":txt+=this.renderImage("word",18);break;case ".rtf":txt+=this.renderImage("word",18);break;default:txt+=this.renderImage("paperclip",18);break}else txt+=this.renderImage("paperclip",18);if(e==null)e=25;var f=c.bezeichnung;if(b>e){b=c.filename.substr(b,99);f=f.substr(0,e)+"[..]"+b}txt=txt+' <a target="_blank" href="?q='+masterData.modulename+"/filedownload&id="+c.id+"&filename="+c.filename+'">'+f+"</a>";txt+="</span><br/>"}return txt};
StandardTableView.prototype.renderTooltipForFiles=function(c,e,b,f){c=[];e=b.bezeichnung.lastIndexOf(".");if(e>0)switch(b.bezeichnung.substr(e,99).toLowerCase()){case ".mp3":c.push('<audio style="width:300px" src="'+masterData.files_url+"/files/"+b.domain_type+"/"+b.domain_id+"/"+b.filename+'"/>');break;case ".wav":c.push('<audio style="width:300px" src="'+masterData.files_url+"/files/"+b.domain_type+"/"+b.domain_id+"/"+b.filename+'"/>');break;case ".m4a":c.push('<video src="'+masterData.files_url+
"/files/"+b.domain_type+"/"+b.domain_id+"/"+b.filename+'"/>');break;case ".mp4":c.push('<video src="'+masterData.files_url+"/files/"+b.domain_type+"/"+b.domain_id+"/"+b.filename+'"/>');break;case ".avi":c.push('<video src="'+masterData.files_url+"/files/"+b.domain_type+"/"+b.domain_id+"/"+b.filename+'"/>');break;case ".mpeg":c.push('<video src="'+masterData.files_url+"/files/"+b.domain_type+"/"+b.domain_id+"/"+b.filename+'"/>');break;case ".jpg":c.push('<img style="max-width:200px;max-height:200px" src="'+
masterData.files_url+"/files/"+b.domain_type+"/"+b.domain_id+"/"+b.filename+'"/>');break;case ".png":c.push('<img style="max-width:200px;max-height:200px" src="'+masterData.files_url+"/files/"+b.domain_type+"/"+b.domain_id+"/"+b.filename+'"/>');break;default:break}b.modified_date!=null&&c.push("<p>vom "+b.modified_date.toDateEn(true).toStringDe(true)+" ("+b.modified_username+")");c.push("<p>");c.push('<a class="btn btn-success btn-small" target="_blank" href="?q='+masterData.modulename+"/filedownload&id="+
b.id+"&filename="+b.filename+'&type=download">Herunterladen</a>&nbsp;');e=b.bezeichnung;if(f){c.push(form_renderButton({label:"Datei l&ouml;schen",cssid:"file_delete",htmlclass:"btn-danger btn-small"})+"&nbsp;");e='<span id="file_name">'+b.bezeichnung+" "+form_renderImage({label:"Datei Umbenennen",src:"options.png",width:20,cssid:"file_rename"})+"</span>"}c.push(form_renderHidden({cssid:"file",value:"true"}));return[c.join(""),e]};StandardTableView.prototype.tooltipCallbackForFiles=function(c,e,b,
f){var g=this;d("video,audio").mediaelementplayer({enablePluginDebug:false,pluginPath:"system/assets/mediaelements/",flashName:"flashmediaelement.swf",silverlightName:"silverlightmediaelement.xap",autoplay:true,success:function(k){k.play()},error:function(){}});var h=b[f].files[c];e.find("#file_download").click(function(){g.clearTooltip(true);return false});e.find("#file_rename").click(function(){e.find("#file_name").html(form_renderInput({cssid:"newfilename",value:h.bezeichnung,controlgroup:false,
type:"medium"}));d("#newfilename").keyup(function(k){var m=d(this).val();if(k.keyCode==13)churchInterface.jsendWrite({func:"renameFile",id:h.id,filename:m},function(l,q){if(l){h.bezeichnung=m;g.renderFiles(b,f)}else alert("Fehler beim Speichern: "+q)});else k.keyCode==27&&g.clearTooltip(true)});return false});e.find("#file_delete").click(function(){if(confirm("Soll wirklich die Datei entfernt werden?")){churchInterface.jsendWrite({func:"delFile",id:h.id},function(k,m){if(k){delete b[f].files[c];g.renderFiles(b,
f)}else alert("Fehler beim Speichern: "+m)});g.clearTooltip(true)}})};StandardTableView.prototype.renderFilelist=function(c,e,b,f,g){var h=this;if(g==null)g=25;f="";if(b!=null)f="[data-id="+b+"]";d("#cdb_content div.filelist"+f).each(function(){d(this).html("");if(e!=null&&e[d(this).attr("data-id")]!=null){var k=e[d(this).attr("data-id")].files;if(k!=null&&churchcore_countObjectElements(k)>0){var m=c;if(m!="")m+="<br/>";d.each(k,function(l,q){m+=h.renderFile(q,g)});d(this).html(m)}}})};StandardTableView.prototype.showDialog=
function(c,e,b,f,g){return form_showDialog(c,e,b,f,g)};StandardTableView.prototype.implantDatePicker=function(c,e,b,f){form_implantDatePicker("dp_"+c,e,b,f)};StandardTableView.prototype.standardFieldCoder=function(c){alert("Keine Code gefunden fuer: "+c);return null};StandardTableView.prototype.renderStandardFieldsAsSelect=function(c,e,b,f){var g=this;c.html(this.getStandardFieldsAsSelect(e,b,f));d("#standardFieldsAsSelect select").change(function(){var h=g.getSaveObjectFromInputFields(null,e,b);
g.renderStandardFieldsAsSelect(c,e,h,f)})};StandardTableView.prototype.getStandardFieldAsSelect=function(c,e,b,f){b=e[b];var g={};g.label=c.text;g.cssid="Input"+c.sql;if(c.auth!=null&&masterData.auth[c.auth]==null&&f!=null&&!churchcore_inArray(c.auth,f))g.disabled=true;switch(c.type){case "select":f=null;f=c.selector.indexOf("code:")==0?this.standardFieldCoder(c.selector.substr(5,99),e):masterData[c.selector];g.selected=b;g.data=f;return form_renderSelect(g);case "date":g.value=b!=null&&b!=""?b.toDateEn(false).toStringDe(false):
"";return form_renderInput(g);case "checkbox":g.checked=b!=null&&b==1;return form_renderCheckbox(g);case "textarea":g.maxlength=c.length;g.data=b;return form_renderTextarea(g);default:g.email=c.sql=="email";g.value=b;g.maxlength=c.length;return form_renderInput(g)}};StandardTableView.prototype.getStandardFieldsAsSelect=function(c,e,b){var f=this,g=new CC_Form(null,e,"standardFieldAsSelect");d.each(masterData.fields[c].fields,function(h,k){g.addHtml(f.getStandardFieldAsSelect(k,e,h,b))});return g.render(null,
"horizontal")};StandardTableView.prototype.getSaveObjectFromInputFields=function(c,e,b){var f={};f.id=c;f.func=e;if(masterData.fields[f.func]!=null)for(var g in masterData.fields[f.func].fields)if(!d("#Input"+g).is(":disabled")){b[g]=masterData.fields[f.func].fields[g].type=="date"?d("#Input"+g).val()!=null&&d("#Input"+g).val().toDateDe()!=null?d("#Input"+g).val().toDateDe().toStringEn():null:masterData.fields[f.func].fields[g].type=="checkbox"?d("#Input"+g).attr("checked")=="checked"?1:0:d("#Input"+
g).val()!=null?d("#Input"+g).val().trim():null;f[g]=b[g]}return f};StandardTableView.prototype.renderImage=function(c,e,b){if(e==null)e=20;if(b==null)b="";return'<img width="'+e+'px" style="max-width:'+e+'px" title="'+b+'" src="'+masterData.modulespath+"/images/"+c+'.png"/>'};StandardTableView.prototype.renderYesNo=function(c,e){return form_renderYesNo(c,e)};StandardTableView.prototype.renderField=function(c,e,b,f,g){debug&&console.log(e);_text="";if(b[c]!=null&&b[c]!=""&&(e.auth==null||masterData.auth[e.auth]||
churchcore_inArray(e.auth,g))){f=e.eol;if(f.indexOf("%")>-1){_text+=f.substr(0,f.indexOf("%"));f=f.substr(f.indexOf("%")+1,99)}if(e.shorttext!="")_text=_text+e.shorttext+": ";_text+='<span class="content">';if(e.type=="date")_text+=b[c].toDateEn().toStringDe();else if(e.type!="select")if(c=="strasse"||c=="ort"||c=="plz")_text=_text+'<a style="color:black" id="extern" target="_blank" href="http://maps.google.de/?q='+b.strasse+", "+b.plz+" "+b.ort+'">'+b[c]+"</a>";else if(c=="telefonprivat"||c=="telefongeschaeftlich"||
c=="telefonhandy")_text=_text+'<a id="extern" style="color:black" href="tel:'+b[c]+'">'+b[c]+"</a>";else if(c=="email")_text=_text+'<a style="color:black" id="extern" href="mailto:'+b.email+'">'+b[c]+"</a>";else _text+=b[c];else if(masterData[e.selector][b[c]]!=null){_text+=masterData[e.selector][b[c]].bezeichnung;if(masterData[e.selector][b[c]].auth!=null)_text=_text+"&nbsp;"+this.renderImage("schluessel",16,"Berechtigungen: "+this.getAuthAsArray(masterData[e.selector][b[c]].auth).join(", "))}else _text=
_text+'<font color="red">Id:'+b[c]+"?</font>";_text=_text+"</span>"+f}return _text};StandardTableView.prototype.renderFields=function(c,e,b,f){var g=this,h="";h=h+'<h4 id="pDetail'+c.arrayname+'">'+c.text+"&nbsp;&nbsp;";if(b)h=h+'<a href="" id="'+c.arrayname+'">'+g.renderImage("options",20)+"</a>";h+="</h4><p style='line-height:100%'><small>";d.each(c.fields,function(k,m){h+=g.renderField(k,m,e,b,f)});h+="</small><br/>";return h};StandardTableView.prototype.renderInput2=function(c){return form_renderInput(c)};
StandardTableView.prototype.renderInput=function(c,e,b,f,g){if(b==null)b="";if(f==null)f=10;disabletxt=g==null||g==false?"":"disabled";return(e!=null?e+"<td>":"")+'<input type="text" size="'+f+'" id="'+c+'" value="'+b+'" '+disabletxt+"/>"};StandardTableView.prototype.renderTextarea=function(c,e,b,f,g,h){if(b==null)b="";disabletxt=h==null||h==false?"":"disabled";return e+'<td> <textarea type="text" cols="'+f+'" rows="'+g+'" id="'+c+'" disabletxt>'+b+"</textarea>"};StandardTableView.prototype.sortMasterData=
function(c){return churchcore_sortMasterData(c)};StandardTableView.prototype.renderSelect=function(c,e,b,f,g){var h="";if(b==null)return"<select><option>-</select>";h=f!=null&&f?h+'<select id="Input'+e+'" disabled="true">':h+'<select id="Input'+e+'">';d.each(this.sortMasterData(b),function(k,m){if(typeof g!="function"||g(m))h=c!=null&&m.id==c?h+'<option selected value="'+m.id+'">'+m.bezeichnung+"</option>":h+'<option value="'+m.id+'">'+m.bezeichnung+"</option>"});h+="</select>";return h};StandardTableView.prototype.renderPersonImage=
function(c,e){return form_renderPersonImage(allPersons[c].imageurl,e)};StandardTableView.prototype.renderPersonSelect=function(c,e,b){var f="";c=[];var g=this;c.push('Suche: <input type="text" size="10" id="searchAddress"/ value="'+f+'">&nbsp;&nbsp;<br/>');c.push('<div id="cdb_personselector"><i>Bitte Namen eingeben...</i></div><br/>');var h=form_showCancelDialog("Auswahl einer Person",c.join(""));e?this.autocompletePersonSelect("#searchAddress",true,function(k,m){b(m.item.value);h.empty().remove();
return false}):d("#searchAddress").keyup(function(){d(this).val()==""&&d("#cdb_personselector").html("");if(f!=d(this).val().toUpperCase()&&d(this).val().length>0){f=d(this).val().toUpperCase();var k=[];i=0;k.push('<table class="table table-condensed">');d.each(allPersons,function(m,l){if(i<20)if(!(masterData.status[l.status_id]==null||masterData.status[l.status_id].infreitextauswahl_yn==0||f!=""&&l.spitzname.toUpperCase().indexOf(f)!=0&&l.name.toUpperCase().indexOf(f)!=0&&l.vorname.toUpperCase().indexOf(f)!=
0&&l.email.toUpperCase().indexOf(f)!=0&&(l.vorname+" "+l.name).toUpperCase().indexOf(f)!=0&&l.id!=f)){k.push('<tr><td><a href="#" id="'+l.id+'">'+g.renderPersonImage(l.id,42)+"</a>");k.push('<td><a href="#" id="'+l.id+'">'+l.name+",  "+l.vorname+" "+(l.spitzname!=""?"("+l.spitzname+")":"")+"</a>");i++}});k.push("</table>");d("#cdb_personselector").html(k.join(""));d("#cdb_personselector a").click(function(){id=d(this).attr("id");b(id);h.empty().remove();return false})}})};StandardTableView.prototype.renderPersonImageUrl=
function(c,e){if(c==null)c="nobody.gif";return'<img style="max-width:'+e+"px;max-height:"+e+'px;" src="'+masterData.files_url+"/fotos/"+c+'"/>'};StandardTableView.prototype.autocompletePersonSelect=function(c,e,b){form_autocompletePersonSelect(c,e,b)};StandardTableView.prototype.getAuthAsArray=function(c){var e=this,b=[];d.each(c,function(f){b.push(e.renderAuth(f))});return b};StandardTableView.prototype.renderEditDomainAuth=function(c){var e=this,b=[];b.push('<p class="pull-right">'+form_renderHelpLink("Berechtigung")+
"</p>");d.each(masterData.auth_table,function(f,g){b.push("<table>");b.push('<tr><td colspan="2"><h3>'+f+"</h3>");d.each(g,function(h,k){h="";if(c!=null&&c[k.id]!=null)h="checked";b.push("<tr><td>");k.datenfeld==null?b.push('<input type="checkbox" id="'+k.id+'" '+h+' class="cdb-checkbox"></input>'):b.push('<a href="" id="edit_'+k.id+'">'+e.renderImage("options")+"</a>");b.push("&nbsp; <td>"+k.auth+"<br><p><small>"+k.bezeichnung+"</small>");k.datenfeld!=null&&b.push('<tr><td><td><span data-datenfeld="'+
k.datenfeld+'" class="datenbereich" id="spanedit_'+k.id+'" style="display:none"><p></span>')});b.push("</table>")});return b.join("")};StandardTableView.prototype.renderAuth=function(c){var e="";d.each(masterData.auth_table,function(b,f){d.each(f,function(g,h){if(h.id==c){e=b+":"+h.auth;return false}})});if(e=="")e="unknown:"+c;return e};StandardTableView.prototype.editDomainAuth=function(c,e,b,f){var g=this;if(masterData.cdb_gruppe==null){var h=this.showDialog("Lade Daten...","Lade Autorisierungsdaten...",
300,300);churchInterface.jsonRead({func:"loadAuthData"},function(k){h.dialog("close");d.each(k,function(m,l){masterData[m]=l});masterData.cdb_gruppe=masterData.groups;if(masterData.cdb_gruppe==null)masterData.cdb_gruppe={};return g.editDomainAuth(c,e,b,f)})}else{h=this.showDialog("Editieren der Rechte",this.renderEditDomainAuth(e),600,600,{Speichern:function(){var k={};h.find("input[type=checkbox]").each(function(m,l){if(l.checked)k["authid"+l.id]=true});h.find("input[type=hidden]").each(function(m,
l){k["authid"+l.id]=true});k.func="saveDomainAuth";k.domain_type=b;k.id=c;churchInterface.jsonWriteSyncron(k);typeof f=="function"&&f(c);d(this).dialog("close")},Abbruch:function(){d(this).dialog("close")}});h.find("span.datenbereich").each(function(){p(d(this),e)});d("a").click(function(){if(this.id.indexOf("edit_")==0){d("#span"+this.id).show();return false}})}}})(jQuery);
