var a,dayNamesMin=["So","Mo","Di","Mi","Do","Fr","Sa"],monthNames=["Januar","Februar","M&auml;rz","April","Mai","Juni","Juli","August","September","Oktober","November","Dezember"];function form_renderYesNo(b,c){if(c==null)c=24;return b==0?form_renderImage({src:"delete_2.png",width:c}):b==1?form_renderImage({src:"check-64.png",width:c}):form_renderImage({src:"attention.png",width:c})}
function form_renderLabelList(b,c,d){if(b[c]==null)b[c]=[];var e=[];$.each(churchcore_sortMasterData(d),function(g,h){if(churchcore_inArray(h.id,b[c])){e.push('<span class="label label-default" title="id:'+h.id+'">');e.push(h.bezeichnung+"&nbsp;");e.push(form_renderImage({cssid:c+"-del",data:[{name:"id",value:h.id}],src:"trashbox.png",width:16}));e.push("</span>&nbsp; ")}});e.push(form_renderImage({src:"plus.png",width:20,cssid:c+"-add"}));var f=$("#"+c);f.html(e.join(""));f.find("#"+c+"-add").click(function(){f.find("#"+
c+"-add").remove();if(churchcore_countObjectElements(d)>99){f.append("<br/><br/>"+form_renderInput({controlgroup:false,type:"medium",cssid:"auto",htmlclass:"autocomplete"}));f.find("input.autocomplete").autocomplete({source:function(g,h){var j=g.term,i=[];$.each(d,function(l,m){!churchcore_inArray(m.id,b[c])&&m.bezeichnung.toUpperCase().indexOf(g.term.toUpperCase())>=0&&i.push({label:m.bezeichnung,value:m.id})});h(i)},select:function(g,h){b[c].push(h.item.value);form_renderLabelList(b,c,d)}}).focus()}else{f.append(form_renderSelect({data:d,
freeoption:true,controlgroup:false,func:function(g){return!churchcore_inArray(g.id,arr)}}));f.find("select").change(function(){b[c].push($(this).val());form_renderLabelList(b,c,d)})}});f.find("#"+c+"-del").click(function(){var g=$(this).attr("data-id");$.each(b[c],function(h,j){if(j==g){b[c].splice(h,1);return false}});form_renderLabelList(b,c,d)})}
function form_renderColorPicker(b){var c=[];c.push('<div class="control-group">');c.push('<label class="control-label">'+b.label+"</i></label>");c.push('<div class="controls">');c.push('<select name="colorpicker"><option value="black">black</option><option value="#ac725e">#ac725e</option><option value="#d06b64">#d06b64</option><option value="#f83a22">#f83a22</option><option value="#fa573c">#fa573c</option><option value="#ff7537">#ff7537</option><option value="#ffad46">#ffad46</option><option value="#fbd75b">#fbd75b</option><option value="#D8F781">#D8F781</option><option value="#16a765">#16a765</option><option value="#7bd148">#7bd148</option><option value="#42d692">#42d692</option><option value="#92e1c0">#92e1c0</option><option value="#9fe1e7">#9fe1e7</option><option value="#9fc6e7">#9fc6e7</option><option value="#4986e7">#4986e7</option><option value="#9a9cff">#9a9cff</option><option value="#b99aff">#b99aff</option><option value="#c2c2c2">#c2c2c2</option><option value="#cabdbf">#cabdbf</option><option value="#cca6ac">#cca6ac</option><option value="#f691b2">#f691b2</option><option value="#cd74e6">#cd74e6</option><option value="#a47ae2">#a47ae2</option></select>');
c.push("</div></div>");test12=b.elem;b.elem.html(c.join(""));b.elem.find('select[name="colorpicker"]').simplecolorpicker({picker:true,delay:200}).on("change",b.func);b.value!=null&&b.elem.find('select[name="colorpicker"]').simplecolorpicker("selectColor",b.value)}function form_renderColor(b){return'<span class="simplecolorpicker icon" title="'+b+'" style="background-color: '+b+'">&nbsp;&nbsp;&nbsp;&nbsp;</span>'}
function form_renderImage(b){var c="",d=b.controlgroup==null?false:b.controlgroup,e=b.controlgroup_class==null?"control-group":b.controlgroup_class,f=b.controlgroup_start!=null&&b.controlgroup_start,g=b.controlgroup_end!=null&&b.controlgroup_end,h="";if(b.width!=null)h=h+"max-width:"+b.width+"px;";if(b.top!=null)h=h+"margin-top:"+b.top+"px;";var j=b.src;if(j.indexOf("/")==-1)j="system/churchcore/images/"+j;if(f||g)d=false;if(d||f)rows.push('<div class="'+e+'">');if(d||f)c+='<div class="controls">';
if(b.label==null)b.label="";if(b.cssid==null)b.cssid="";var i="";b.data!=null&&$.each(b.data,function(l,m){i=i+"data-"+m.name+"="+m.value+" "});e=b.htmlclass!=null?b.htmlclass:"";c=b.cssid!=""?c+'<a href="#" '+i+'title="'+b.label+'" id="'+b.cssid+'"><img style="'+h+'" src="'+j+'" class="'+e+'"></a>':c+'<img style="'+h+'" src="'+j+'" title="'+b.label+'" class="'+e+'">';if(d||g)c+="</div></div>";return c}
function form_renderPersonImage(b,c){if(c==null)c=180;if(b==null)b="nobody.gif";return'<img style="max-width:'+c+"px;max-height:"+c+'px;" src="'+masterData.files_url+"/fotos/"+b+'"/>'}
function form_autocompletePersonSelect(b,c,d){if(c==null)c=false;$(b).addClass("form-autocomplete");d=$(b).autocomplete({search:function(e,f){$(b).addClass("throbbing")},source:function(e,f){var g=e.term,h="";if(g.lastIndexOf(",")>0){g=g.substr(g.lastIndexOf(",")+1,99);h=e.term.substr(0,e.term.lastIndexOf(",")+1)+" "}churchInterface.jsonRead({func:"getPersonByName",searchpattern:$.trim(g),withmydeps:c},function(j){$(b).removeClass("throbbing");if(j.result=="ok")j.data!=null?f($.map(j.data,function(i){return{label:i.name,
value:h+i.id,imageurl:i.imageurl,shortname:i.shortname}})):f(null)},"churchdb")},minLength:2,select:d});if(d.data("autocomplete")!=null)d.data("autocomplete")._renderItem=function(e,f){return $("<li>").data("item.autocomplete",f).append('<a style="height:42px"><span style="width:48px;float:left;"> '+form_renderPersonImage(f.imageurl,42)+"</span>"+f.label+"</a>").appendTo(e)}}
function form_renderSelectable(b,c){var d=[],e=c.height==null?"":"height:"+c.height+"px;",f=c.min_element_height==null?"":"min-height:"+c.min_element_height+"px;";d.push('<div style="'+e+'"><ul class="ui-menu ui-widget ui-widget-content ui-corner-all" style="'+e+' width:99%; overflow-y:auto; -webkit-overflow-scrolling: touch" id="'+c.cssid+'">');c.data!=null&&$.each(c.data,function(g,h){g="ui-corner-all";if(h.htmlclass!=null)g=g+" "+h.htmlclass;d.push('<li class="ui-menu-item" data-id="'+h.id+'"><p style="margin:0 0 5px"><a href="#" data-id="'+
h.id+'" class="'+g+'" style="'+f+'">');d.push(h.bezeichnung+"</a>")});d.push("</ul></div>");b.html(d.join(""));c.selected!=null&&b.find("a[data-id="+c.selected+"]").addClass("ui-state-hover");b.find("a").click(function(g){var h=$(this).attr("data-id");if(c.deselectable==true&&$(this).hasClass("ui-state-hover")){$(this).removeClass("ui-state-hover");c.deselect!=null&&c.deselect()}else{c.select!=null&&c.select(h);b.find("a").each(function(){$(this).attr("data-id")!=h&&$(this).hasClass("ui-state-hover")&&
$(this).removeClass("ui-state-hover")});$(this).addClass("ui-state-hover")}return false});if(c.selected!=null&&b.find("li[data-id="+c.selected+"]").position()!=null)c.animate?b.find("ul").animate({scrollTop:b.find("li[data-id="+c.selected+"]").position().top-b.position().top-3,duration:200}):b.find("ul").scrollTop(b.find("li[data-id="+c.selected+"]").position().top-b.position().top-3)}
function form_renderCheckbox(b){debug&&console.log(b);var c=[],d=b.label!=null?b.label:"",e=b.controlgroup==null||b.controlgroup,f=b.controlgroup_class==null?"control-group":b.controlgroup_class,g=b.controlgroup_start!=null&&b.controlgroup_start,h=b.controlgroup_end!=null&&b.controlgroup_end;if(g||h)e=false;if(e||g)c.push('<div class="'+f+'">');if(e||g)c.push('<div class="controls">');d!=""&&c.push('<label class="checkbox">');c.push('<input type="checkbox" class="checkbox" '+(b.cssid!=null?'id="'+
b.cssid+'"':""));b.checked!=null&&b.checked&&c.push(" checked");b.disabled!=null&&b.disabled==true&&c.push(" disabled=yes");c.push("/> "+d);d!=""&&c.push("</label>");if(e||h)c.push("</div></div>");return c.join("")}
function form_renderButton(b){var c=b.cssid!=null?'id="'+b.cssid+'"':"",d=b.type!=null?" btn-"+b.type:"",e=b.htmlclass!=null?" "+b.htmlclass:"",f=b.disabled!=null&&b.disabled?' disabled="true"':"",g=[];b.controlgroup!=null&&b.controlgroup&&g.push('<div class="control-group"><div class="controls">');g.push('<input type="button" class="btn'+d+e+'" '+c+' value="'+b.label+'"'+f+'"/>');b.controlgroup!=null&&b.controlgroup&&g.push("</div></div>");return g.join("")}
function form_renderInput(b){var c=b.value!=null?b.value:"",d=b.size!=null?d:10,e=b.disabled!=null&&b.disabled?"disabled":"",f=b.separator!=null?b.separator:" ",g=b.controlgroup==null||b.controlgroup;if(b.controlgroup_start!=null)g=false;if(b.controlgroup_end!=null)g=false;var h=b.cssid!=null?'id="'+b.cssid+'"':"";if(b.type!=null){if(b.htmlclass==null)b.htmlclass="";b.htmlclass=b.htmlclass+" input-"+b.type}var j=b.placeholder!=null?b.placeholder:"",i=[];if(g||b.controlgroup_start!=null)i.push('<div class="control-group">');
if(b.label!=null){i.push('<label class="control-label" '+(h!=""?'for="'+b.cssid+'"':"")+">"+b.label);b.required&&i.push(' <span class="required">*</span>');i.push("</label>")}if(g||b.controlgroup_start!=null)i.push('<div class="controls">');else b.label!=null&&i.push(f);if(j==null)j="";i.push('<input type="');f="text";if(b.password!=null&&b.password)f="password";else if(b.email!=null&&b.email)f="email";i.push(f);i.push('" size="'+d+'" '+h+' placeholder="'+j+'" ');b.htmlclass!=null&&i.push('class="'+
b.htmlclass+'" ');b.maxlength!=null&&i.push('maxlength="'+b.maxlength+'" ');i.push(e+' value="'+c+'"/>');if(g||b.controlgroup_end!=null)i.push("</div></div>");return i.join("")}
function form_renderTextarea(b){var c="",d="",e="",f=[];if(b.placeholder!=null)e=b.placeholder;if(b.data!=null)d=b.data;if(b.label!=null)c=b.label;var g=b.controlgroup==null||b.controlgroup;if(b.type!=null){if(b.htmlclass==null)b.htmlclass="";b.htmlclass=b.htmlclass+" input-"+b.type}var h=b.htmlclass!=null?"class="+b.htmlclass:"";if(b.disabled!=null&&b.disabled)disabletxt="disabled";g&&f.push('<div class="control-group">');f.push('<label class="control-label" for="'+b.cssid+'">'+c+"</i></label>");
if(g)f.push('<div class="controls">');else if(b.label!=null)b.separator!=null?f.push(separator):f.push("<td>");f.push("<textarea "+h+' type="text" placeholder="'+e+'" ');b.maxlength!=null&&f.push('maxlength="'+b.maxlength+'" ');f.push('cols="'+b.cols+'" rows="'+b.rows+'" id="'+b.cssid+'" disabletxt>'+d+"</textarea>");g&&f.push("</div></div>");return f.join("")}function form_renderHidden(b){return'<input type="hidden" name="'+b.name+'" id="'+b.cssid+'" value="'+b.value+'"/>'}
function form_renderCaption(b){return form_renderLabel(b.text,b.label)}function form_renderLabel(b,c){var d=[];if(c!=null){d.push('<div class="control-group">');d.push('<label class="control-label">'+c+"</i></label>")}d.push('<div class="controls">'+b+"</div>");c!=null&&d.push("</div>");return d.join("")}function form_prepareDataEntry(b,c,d){var e={};e.id=b;e.bezeichnung=c;if(d!=null)e.sortkey=d;return e}
function form_renderSelect(b){var c=b.separator!=null?b.separator:" ",d=b.controlgroup==null||b.controlgroup;if(b.controlgroup_start!=null)d=false;if(b.controlgroup_end!=null)d=false;var e=b.multiple!=null&&b.multiple?" multiple":"",f="";b.fields!=null&&$.each(b.fields,function(j,i){f=f+" "+j+'="'+i+'"'});var g=[];if(d||b.controlgroup_start!=null)g.push('<div class="control-group">');if(b.label!=null){g.push('<label class="control-label" for="'+b.cssid+'">'+b.label+"</i></label>");g.push(c)}c="";
if(b.cssid!=null)c='id="'+b.cssid+'"';var h="";if(b.htmlclass!=null)h=b.htmlclass;if(b.type!=null)h=h+" input-"+b.type;if(d||b.controlgroup_start!=null)g.push('<div class="controls">');b.disabled!=null&&b.disabled?g.push("<select "+c+' class="'+h+'" '+f+' disabled="true"'+e+">"):g.push("<select "+c+' class="'+h+'" '+f+e+">");b.freeoption!=null&&b.freeoption&&g.push('<option value=""/>');if(b.data!=null)$.each(b.sort==null||b.sort?churchcore_sortMasterData(b.data):b.data,function(j,i){if(typeof b.func!=
"function"||b.func(i))b.selected!=null&&i.id==b.selected?g.push('<option selected value="'+i.id+'">'+i.bezeichnung+"</option>"):g.push('<option value="'+i.id+'">'+i.bezeichnung+"</option>")});g.push("</select>");b.html!=null&&g.push(b.html);if(d||b.controlgroup_end!=null)g.push("</div></div>");return g.join("")}function form_getDateFromForm(b){var c=$("#"+b+"date").val();if($("#"+b+"hour").val()!=null)c=c+" "+$("#"+b+"hour").val()+":"+$("#"+b+"minutes").val();return new Date(c.toDateDe(true))}
function _getMinutesArray(){var b=[];form_addEntryToSelectArray(b,0,"00");form_addEntryToSelectArray(b,15,"15");form_addEntryToSelectArray(b,30,"30");form_addEntryToSelectArray(b,45,"45");return b}function _getHoursArray(){for(var b=[],c=0;c<24;c++)form_addEntryToSelectArray(b,c,c,c);return b}
function _renderDateForms(b){var c=[],d=b.data.startdate,e=b.data.enddate;d=b.data.startdate;var f=b.data.repeat_id,g=b.data.repeat_frequence,h=b.data.repeat_until,j=b.data.repeat_option_id,i=b.data.exceptions,l=b.data.additions,m=b.authexceptions==null?true:b.authexceptions,q=b.authadditions==null?true:b.authadditions,k=b.disabled!=null&&b.disabled==true,n=_getMinutesArray(),r=_getHoursArray(),s=churchcore_isAllDayDate(d,e);c=[];c.push(form_renderCheckbox({label:" Ganzt&auml;gig",controlgroup:true,
cssid:"inputAllDay",checked:s,disabled:k}));if(s){c.push(form_renderInput({cssid:"inputStartdate",label:"Startdatum",controlgroup:true,value:d.toStringDe(),disabled:k,type:"small"}));c.push('<div id="dp_startdate" style="position:absolute;background:#e7eef4;z-index:8001;"/>')}else{c.push(form_renderInput({cssid:"inputStartdate",label:"Startdatum",controlgroup_start:true,separator:"<nobr>",value:d.toStringDe(),disabled:k,type:"small"})+"&nbsp;");c.push('<div id="dp_startdate" style="position:absolute;background:#e7eef4;z-index:8001;"/>');
c.push(form_renderSelect({data:r,cssid:"inputStarthour",selected:d.getHours(),htmlclass:"input-mini",disabled:k,controlgroup:false})+" : ");c.push(form_renderSelect({data:n,cssid:"inputStartminutes",selected:d.getMinutes(),type:"mini",disabled:k,controlgroup_end:true}))}c.push("</nobr>");if(s){c.push(form_renderInput({cssid:"inputEnddate",label:"Enddatum",controlgroup:true,value:e.toStringDe(),disabled:k,type:"small"}));c.push('<div id="dp_enddate" style="position:absolute;background:#e7eef4;z-index:8001;"/>')}else{c.push(form_renderInput({cssid:"inputEnddate",
label:"Enddatum",controlgroup_start:true,separator:"<nobr>",value:e.toStringDe(),disabled:k,type:"small"})+"&nbsp;");c.push('<div id="dp_enddate" style="position:absolute;background:#e7eef4;z-index:8001;"/>');c.push(form_renderSelect({data:r,cssid:"inputEndhour",selected:month&&e.getHours()==0?11:e.getHours(),htmlclass:"input-mini",disabled:k,controlgroup:false})+" : ");c.push(form_renderSelect({data:n,cssid:"inputEndminutes",selected:e.getMinutes(),type:"mini",disabled:k,controlgroup_end:true}))}c.push("</nobr>");
c.push(form_renderSelect({data:masterData.repeat,cssid:"inputRepeat_id",selected:f,disabled:k,type:"big",label:"Wiederholungen"}));c.push('<div id="repeats_select">');if(f!=null&&f>0){if(g==null||g==0)g=1;if(f==32){e=[];n=dayNames[d.getDay()]+" im Monat";e.push(form_prepareDataEntry(1,"Erster "+n,1));e.push(form_prepareDataEntry(2,"Zweiter "+n,2));e.push(form_prepareDataEntry(3,"Dritter "+n,3));e.push(form_prepareDataEntry(4,"Vierter "+n,4));e.push(form_prepareDataEntry(5,"F&uuml;nter "+n+" (falls vorhanden)",
5));e.push(form_prepareDataEntry(6,"Letzter "+n,6));if(j==null){j=new Date(d);j.setDate(0);for(n=0;j<d;){j.addDays(1);if(j.getDay()==d.getDay())n+=1}j=n}c.push(form_renderSelect({data:e,cssid:"inputRepeatOptionId",disabled:k,selected:j,type:"medium",label:""}))}if(f!=999){c.push('<div class="control-group"><label class="control-label"></label>');c.push('<div class="controls">');c.push("alle&nbsp;");c.push(form_renderInput({value:g,disabled:k,controlgroup:false,cssid:"inputRepeatFrequence",type:"xxmini"}));
if(h==null){h=new Date(d);h.addDays(f*1)}}if(f==1)c.push("&nbsp;Tag(e) bis&nbsp;");else if(f==7)c.push("&nbsp;Woche(n) bis&nbsp;");else if(f==31)c.push("&nbsp;Monat(e) bis&nbsp;");else if(f==32)c.push("&nbsp;Monat(e) bis&nbsp;");else f==365&&c.push("&nbsp;Jahr(e) bis&nbsp;");if(f!=999){if(h==null||h.getFullYear()==1899){h=new Date(d);h.addDays(f*1)}c.push(form_renderInput({value:h.toStringDe(),controlgroup:false,disabled:k,cssid:"inputRepeatUntil",type:"small"}));c.push('<div id="dp_repeatuntil" style="position:absolute;background:#e7eef4;z-index:8001;"/></div></div>')}if(f>
0&&f!=999){c.push('<div id="repeats_exceptions">');c.push('<div class="control-group"><label class="control-label">Ausnahmen</label>');c.push('<div class="controls">');i!=null&&$.each(churchcore_sortData(i,"exception_start_date"),function(p,o){c.push('<span class="label label-default" title="id:'+o.id+'">');o.except_date_end!=o.except_date_start?c.push(o.except_date_start.toDateEn().toStringDe()+"-"+o.except_date_end.toDateEn().toStringDe()+"&nbsp;"):c.push(o.except_date_start.toDateEn().toStringDe()+
"&nbsp;");b.deleteException!=null&&m&&c.push(form_renderImage({src:"trashbox.png",width:16,cssid:"delException"+o.id}));c.push("</span>&nbsp; ")});if(m&&!k){c.push(form_renderImage({src:"plus.png",width:20,cssid:"addException"}));c.push('<div id="dp_addexception" style="position:absolute;background:#e7eef4;z-index:8001;"/></div></div>')}c.push("</div></div>");c.push("</div>")}if(f>0&&f!=1||l!=null){c.push('<div id="repeats_addition">');c.push('<div class="control-group"><label class="control-label">Weitere Termine</label>');
c.push('<div class="controls">');l!=null&&$.each(churchcore_sortData(l,"add_date"),function(p,o){c.push('<span class="label label-default" title="id:'+o.id+'">');c.push(o.add_date.toDateEn().toStringDe()+"&nbsp;");p="recurring_bw.png";if(o.with_repeat_yn==1)p="recurring.png";b.addAddition!=null&&q?c.push(form_renderImage({src:p,width:16,label:"Soll der manuelle Termin auch wiederholt werden",cssid:"changeAdditionRepeat"+(1-o.with_repeat_yn)+o.id})):c.push(form_renderImage({src:p,width:16}));b.addAddition!=
null&&q&&c.push(form_renderImage({src:"trashbox.png",width:16,label:"Entferne den manuellen Termin",cssid:"delAddition"+o.id}));c.push("</span>&nbsp; ")});if(q&&!k){c.push(form_renderImage({src:"plus.png",width:20,cssid:"addAddition"}));c.push('<div id="dp_addaddition" style="position:absolute;background:#e7eef4;z-index:8001;"/></div></div>')}c.push("</div></div>");c.push("</div>")}}c.push("</div>");return c.join("")}
function form_renderDates(b){debug&&console.log(b);if(b.data.exceptions!=null)b.data.exceptions=jQuery.extend({},b.data.exceptions);if(b.data.additions!=null)b.data.additions=jQuery.extend({},b.data.additions);b.elem.html(_renderDateForms(b));$("#inputAllDay").change(function(c){if($(this).attr("checked")=="checked"){b.data.startdate.setHours(0);b.data.startdate.setMinutes(0);b.data.enddate.setHours(0);b.data.enddate.setMinutes(0)}else{b.data.startdate.setHours(10);b.data.enddate.setHours(11)}form_renderDates(b)});
$("#inputStartdate").click(function(){form_implantDatePicker("dp_startdate",b.data.startdate,function(c){$("#inputStartdate").val(c);$("#inputStartdate").keyup()})});$("#inputEnddate").click(function(){form_implantDatePicker("dp_enddate",b.data.enddate,function(c){$("#inputEnddate").val(c);$("#inputEnddate").keyup()})});$("#inputStartdate").keyup(function(){if($("#inputStartdate").val().isGermanDateFormat()){$("#inputEnddate").val($("#inputStartdate").val());form_getDatesInToObject(b.data);b.data.repeat_option_id=
null;form_renderDates(b)}});$("#inputStarthour").change(function(){b.data.startdate.setHours($("#inputStarthour").val());if(form_getDateFromForm("inputStart")>=form_getDateFromForm("inputEnd")){b.data.enddate.setHours($("#inputStarthour").val()*1+1);form_renderDates(b)}});$("#inputEndhour").change(function(){form_getDateFromForm("inputStart")>=form_getDateFromForm("inputEnd")&&$("#inputStarthour").val($("#inputEndhour").val()*1-1)});$("#repeats_exceptions a").click(function(){if($(this).attr("id").indexOf("delException")==
0){if(b.deleteException!=null){var c=b.data.exceptions[$(this).attr("id").substr(12,99)];b.deleteException(c);form_renderDates(b)}return false}else if($(this).attr("id")=="addException"){form_getDatesInToObject(b.data);form_implantDatePicker("dp_addexception",null,function(d){if(b.addException!=null){b.data=b.addException(b.data,d);form_renderDates(b)}},function(d){var e=false;d.sameDay(b.data.startdate)||$.each(churchcore_getAllDatesWithRepeats(b.data),function(f,g){if(g.startdate.toStringEn(false).toDateEn(false).getTime()==
d.getTime())e=true});return[e]});return false}});$("#repeats_addition a").click(function(){if($(this).attr("id").indexOf("delAddition")==0){if(b.deleteAddition!=null){var c=b.data.additions[$(this).attr("id").substr(11,99)];b.deleteAddition(c);form_renderDates(b)}return false}else if($(this).attr("id").indexOf("changeAdditionRepeat")==0){if(b.deleteAddition!=null&&b.addAddition!=null){c=b.data.additions[$(this).attr("id").substr(21,99)];b.deleteAddition(c);b.data=b.addAddition(c.data,c.add_date.toDateEn().toStringDe(),
$(this).attr("id").substr(20,1));form_renderDates(b)}return false}else if($(this).attr("id")=="addAddition"){form_getDatesInToObject(b.data);form_implantDatePicker("dp_addaddition",null,function(d){if(b.addAddition!=null){b.data=b.addAddition(b.data,d,1);form_renderDates(b)}},function(d){var e=d>b.data.startdate;$.each(churchcore_getAllDatesWithRepeats(b.data),function(f,g){if(g.startdate.toStringEn(false).toDateEn(false).getTime()==d.getTime())e=false});return[e]});return false}});$("#inputRepeat_id").change(function(c){form_getDatesInToObject(b.data);
form_renderDates(b)});$("#inputRepeatUntil").click(function(){form_getDatesInToObject(b.data);form_implantDatePicker("dp_repeatuntil",b.data.repeat_until,function(c){$("#inputRepeatUntil").val(c)})});$("#inputRepeatFrequence").change(function(){if($("#inputRepeatFrequence").val()=="0"||$("#inputRepeatFrequence").val()=="")$("#inputRepeatFrequence").val("1")})}
function form_getDatesInToObject(b){b.startdate=form_getDateFromForm("inputStart");b.enddate=form_getDateFromForm("inputEnd");b.repeat_id=$("#inputRepeat_id").val();b.repeat_until=$("#inputRepeatUntil").val();if(b.repeat_until!=null)b.repeat_until=b.repeat_until.toDateDe();b.repeat_frequence=$("#inputRepeatFrequence").val();b.repeat_option_id=$("#inputRepeatOptionId").val()}
function form_implantWysiwygEditor(b,c,d){if(!churchcore_isObjectEmpty($("#"+b))){if(c==false)toolbar=[{name:"clipboard",groups:["clipboard","undo"],items:["Cut","Copy","Paste","-","Undo","Redo"]},{name:"basicstyles",groups:["basicstyles","cleanup"],items:["Bold","Italic","Underline","Strike","-","RemoveFormat"]},{name:"colors",items:["TextColor","BGColor"]},{name:"insert",items:["Image","Smiley"]},{name:"serienfeld",items:["vorname","spitzname","nachname"]}];else if(c==true)toolbar=[{name:"basicstyles",
groups:["basicstyles","cleanup"],items:["Bold","Italic","Underline","Strike","-","RemoveFormat"]},{name:"colors",items:["TextColor","BGColor"]},{name:"insert",items:["Image","Smiley","SpecialChar"]}];else if(c==null)toolbar=[{name:"basicstyles",groups:["basicstyles","cleanup"],items:["Bold","Underline"]}];CKEDITOR.config.extraPlugins="churchtools";d==null||d==false?CKEDITOR.replace(b,{toolbar:toolbar}):CKEDITOR.inline(b,{toolbar:toolbar})}}
function CC_MultiSelect(b,c){this.selected=[];this.func=c;this.data=b;this.allSelected=true;this.addFunctions=[]}a=CC_MultiSelect.prototype;a.isSelected=function(b){if(this.selected.length==0||b==null)return false;return churchcore_inArray(b,this.selected)?true:false};
a.render2Div=function(b,c){var d=this;if(c==null)c={};var e=[],f=c.controlgroup==null||c.controlgroup;f&&e.push('<div class="control-group">');e.push("<label>"+c.label+"</label>");f&&e.push('<div class="control">');var g="",h=0;this.data!=null&&$.each(this.data,function(i,l){l!=null&&l.bezeichnung!="-"&&h++});if(this.selected.length==0)g="keine ausgew&auml;hlt";else if(this.selected.length==1)g=this.data[this.selected[0]].bezeichnung;else if(this.selected.length==h){g="alle ausgew&auml;hlt";d.allSelected=
false}else g=this.selected.length+" ausgew&auml;hlt";e.push('<div class="dropdown '+(c.open?"open":"")+'" id="'+c.cssid+'">');e.push('<a style="widt_h:124px" class="btn dropdown-toggle" id="dLabel" role="button" data-toggle="dropdown" data-target="#" href="#">'+g+'&nbsp;<b class="caret"></b> </a>');var j=1;if(h>8)j=2;if(h>16)j=3;e.push('<ul class="dropdown-menu" style="width:'+240*j+'px">');if(h>1){e.push('<li><a style="padding:0" href="#" id="allSelected" class="multicheck">');e.push('<label style="margin:0;padding: 3px 20px 3px 20px;width:100%;height:100%;cursor:pointer;">');
this.allSelected?e.push('<input type="checkbox" style="margin-bottom:5px;" /> <i>Alle ausw&auml;hlen</i></label></a>'):e.push('<input type="checkbox" style="margin-bottom:5px;" checked/> <i>Alle abw&auml;hlen</i></label></a>');$.each(this.addFunctions,function(i,l){e.push('<li><a style="padding:0" href="#" id="addfunc_'+i+'" class="multicheck">');e.push('<label style="margin:0;padding: 3px 20px 3px 20px;width:100%;height:100%;cursor:pointer;">');e.push('<input type="checkbox" style="margin-bottom:5px;" '+
l.checked+"/> <i>"+l.bezeichnung+"</i></label></a>")});e.push('<li class="divider">')}this.data!=null&&$.each(churchcore_sortMasterData(this.data),function(i,l){if(l.bezeichnung!="-"){e.push('<li style="float:left;width:240px"> ');e.push('<a style="padding:0" href="#" id="'+l.id+'" class="multicheck">');e.push('<label style="margin:0;padding: 3px 20px 3px 20px;width:100%;height:100%;cursor:pointer;">');e.push('<input type="checkbox" style="margin-bottom:5px;" '+(d.isSelected(l.id)?"checked":"")+"/> ");
e.push(l.bezeichnung);e.push("</label></a>")}else e.push('<li style="float:left;width:'+240*j+'px" class="divider">')});e.push("</ul>");e.push("</div>");e.push("</div>");e.push("</div>");f&&e.push("</div></div>");$("#"+b).html(e.join(""));$("#"+b+" a.multicheck").click(function(){var i=$(this).attr("id");if(i=="allSelected"){if(d.allSelected){d.allSelected=false;d.selectAll()}else{d.selected=[];d.allSelected=true}$.each(d.addFunctions,function(l,m){m.checked=""});typeof d.func=="function"&&d.func(i,
d.isSelected(i))}else if(i.indexOf("addfunc")==0)$.each(d.addFunctions,function(l,m){if(i=="addfunc_"+l){m.checked=m.checked=="checked"?"":"checked";d.allSelected=true;$.each(d.data,function(q,k){if(m.checked=="checked"){if(m.func(k)&&!churchcore_inArray(k.id,d.selected)){d.selected.push(k.id);typeof d.func=="function"&&d.func(k.id,true)}}else if(m.func(k)){$.each(d.selected,function(n,r){if(r==k.id){d.selected.splice(n,1);return false}});typeof d.func=="function"&&d.func(k.id,false)}})}});else{d.toggleSelected(i);
d.allSelected=churchcore_countObjectElements(d.data)==d.selected.length?false:true;$.each(d.addFunctions,function(l,m){m.checked=""});typeof d.func=="function"&&d.func(i,d.isSelected(i))}c.open=true;d.render2Div(b,c);return false})};a.getSelected=function(){return this.selected};a.toggleSelected=function(b){if(this.isSelected(b)){var c=[];$.each(this.selected,function(d,e){e!=b&&c.push(e)});this.selected=c}else this.selected.push(b)};
a.selectAll=function(){var b=this;b.selected=[];$.each(b.data,function(c,d){d!=null&&d.bezeichnung!="-"&&b.selected.push(d.id)})};a.setSelectedAsArrayString=function(b){var c=this;if(b!=null&&b!=""){b=b.substr(1,b.length-2);var d=[];$.each(b.split(","),function(e,f){c.data!=null&&c.data[f]!=null&&d.push(f)});this.selected=d}};a.getSelectedAsArrayString=function(){return"["+this.selected.join(",")+"]"};a.addFunction=function(b,c){this.addFunctions.push({bezeichnung:b,func:c,checked:""})};
a.filter=function(b){if(this.selected.length!=0&&!this.isSelected(b))return true;return false};a.toString=function(){return this.getSelectedAsArrayString()};function CC_Menu(b){this.label=b;this.entries=[]}CC_Menu.prototype.getLabel=function(){return this.label};CC_Menu.prototype.addEntry=function(b,c,d){var e={};e.caption=b;e.id=c;e.icon=d;this.entries.push(e)};
CC_Menu.prototype.renderDiv=function(b,c){if(this.entries.length==0)return false;var d=[];if(c==null||c==false){d.push('<div class="well sidebar-nav"><ul class="nav nav-list">');d.push('<li class="nav-header">Men&uuml;');jQuery.each(this.entries,function(e,f){d.push('<li><a href="#" id="'+f.id+'"><i class="icon-'+f.icon+'"></i> '+f.caption+"</a>")})}else{d.push('<div class="btn-group">');d.push('<button class="btn dropdown-toggle" data-toggle="dropdown">Men&uuml; <span class="caret"></span></button>');
d.push('<ul class="dropdown-menu">');jQuery.each(this.entries,function(e,f){d.push('<li><a href="#" id="'+f.id+'"><i class="icon-'+f.icon+'"></i> '+f.caption+"</a>")})}d.push("</ul></div>");jQuery("#"+b).html(d.join(""));return true};var form_count=0;function CC_Form(b,c,d){this.rows=[];this.label=b;this.help=this.surroundDiv=null;this.fields=[];this.value_container=c;if(d!=null)this.cssid=d;else{this.cssid="form"+form_count;form_count+=1}}a=CC_Form.prototype;a.getLabel=function(){return this.label};
a.getCSSId=function(){return this.cssid};a.setLabel=function(b){this.label=b};a.surroundWithDiv=function(b){this.surroundDiv=b};a.getVal=function(b){b=$("#"+this.cssid+" #"+b).val();return b!=null?b.trim():null};a.getChecked=function(b){return $("#"+this.cssid+" #"+b).attr("checked")=="checked"?1:0};
a.addStandardField=function(b,c){var d=null;if(this.value_container!=null)d=this.value_container[b.sql];var e={};e.label=b.text;e.cssid=b.sql;if(b.auth!=null&&masterData.auth[b.auth]==null&&c!=null&&!churchcore_inArray(b.auth,c))e.disabled=true;switch(b.type){case "select":c=null;c=b.selector.indexOf("code:")==0?this.standardFieldCoder(b.selector.substr(5,99),arr):masterData[b.selector];e.selected=d;e.data=c;this.addSelect(e);break;case "date":if(d!=null)e.value=d.toDateEn(false).toStringDe(false);
this.addDate(e);break;case "checkbox":e.checked=d!=null&&d==1;this.addCheckbox(e);break;case "textarea":e.maxlength=b.length;e.data=d;this.addTextarea(e);break;default:e.email=b.sql=="email";e.value=d;e.maxlength=b.length;this.addInput(e);break}};
a.getAllValsAsObject=function(b){var c=this;if(b==null)b=true;var d={};$.each(this.fields,function(e,f){if(b||f.required||c.getVal(f.cssid)!=""){if(f.fieldtype=="input")d[f.cssid]=c.getVal(f.cssid).trim();else if(f.fieldtype=="date")d[f.cssid]=c.getVal(f.cssid)!=""?c.getVal(f.cssid).trim().toDateDe(false).toStringEn(false):"";else if(f.fieldtype=="textarea")d[f.cssid]=c.getVal(f.cssid);else if(f.fieldtype=="checkbox")d[f.cssid]=c.getChecked(f.cssid);else if(f.fieldtype=="select")d[f.cssid]=c.getVal(f.cssid);
else if(f.fieldtype=="hidden")d[f.cssid]=c.getVal(f.cssid);else alert("Bei getAllValsAsObject ist "+f.fieldtype+" nicht nicht implementiert");if(f.required&&d[f.cssid]==""){e=$("#"+c.cssid+" #"+f.cssid).parent(".controls");e.append('<span class="help-inline error">Bitte das Feld ausf&uuml;llen!</span>');e.parent(".control-group").addClass("error");d=null;return false}}});return d};
a.addLink=function(b,c,d,e){_text='<label class="button ">';_text="";if(b!="")_text=_text+"<label>"+b+"</label>";if(e==null)e="";e+=" btn";_text=_text+'<a href="#" id="'+c+'" class="'+e+'"';_text=_text+">"+d+"</a>&nbsp;&nbsp;&nbsp;";this.rows.push(_text)};a.addSeparator=function(){this.rows.push("<br/>")};a.addImage=function(b){this.rows.push(form_renderImage(b))};
a.renderField=function(b){debug&&console.log(b);var c=true;if(b.fieldtype=="select")this.rows.push(form_renderSelect(b));else if(b.fieldtype=="input"||b.fieldtype=="date")this.rows.push(form_renderInput(b));else if(b.fieldtype=="textarea")this.rows.push(form_renderTextarea(b));else if(b.fieldtype=="checkbox")this.rows.push(form_renderCheckbox(b));else if(b.fieldtype=="hidden")this.rows.push(form_renderHidden(b));else{alert("Fieldtype "+b.fieldtype+" nicht gefunden!");c=false}c&&this.fields.push(b)};
a.addSelect=function(b){this.renderField(this.prepareOptionsAsField(b,"select"))};a.addMultiSelect=function(b){this.rows.push(form_renderMultiSelect(b))};a.addHidden=function(b){this.renderField(this.prepareOptionsAsField(b,"hidden"))};a.addCaption=function(b){this.rows.push(form_renderCaption(b))};a.addButton=function(b){this.rows.push(form_renderButton(b))};a.addCheckbox=function(b){this.renderField(this.prepareOptionsAsField(b,"checkbox"))};
a.prepareOptionsAsField=function(b,c){var d=$.extend({},b);if(b.cssid==null)if(b.label!=null)d.cssid=b.label.replace(" ","_");else if(b.name!=null)d.cssid=b.name.replace(" ","_");if(d.value==null&&this.value_container!=null)if(c=="checkbox")d.checked=this.value_container[d.cssid]==1;else if(c=="select")d.selected=this.value_container[d.cssid];else if(c=="textarea")d.data=this.value_container[d.cssid];else d.value=this.value_container[d.cssid];d.fieldtype=c;return d};
a.addInput=function(b){this.renderField(this.prepareOptionsAsField(b,"input"))};a.addDate=function(b){this.renderField(this.prepareOptionsAsField(b,"date"))};a.addTextarea=function(b){this.renderField(this.prepareOptionsAsField(b,"textarea"))};a.addHtml=function(b){this.rows.push(b)};a.setHelp=function(b){this.help=b};
a.render=function(b,c){if(this.rows.length==0)return"";var d=[];this.surroundDiv!=null&&d.push('<div class="'+this.surroundDiv+'">');this.label!=null&&d.push("<legend>"+this.label+"</legend>");d.push('<form id="'+this.cssid+'" class="'+(b?"well":"")+" "+(c==null?"":"form-"+c)+'">');this.help!=null&&d.push('<p class="pull-right">'+form_renderHelpLink(this.help,true)+"</p>");d.push(this.rows.join(""));d.push("</form>");this.surroundDiv!=null&&d.push("</div>");return d.join("")};
function CC_Navi(b){this.entries=[];this.search=null;this.name=b}a=CC_Navi.prototype;a.addEntry=function(b,c,d){var e=[];e.active=b;e.id=c;e.label=d;this.entries.push(e)};a.addSearch=function(b){this.search='<input type="text" id="searchEntry" placeholder="Suche" class="input-medium search-query pull-right" value="'+b+'"/>'};
a.render=function(b){var c=[];if(b){if(this.entries.length>1){var d=this.name;jQuery.each(this.entries,function(){if(this.active)d=this.label});c.push('<span class="btn-group">');c.push('<button class="btn dropdown-toggle" data-toggle="dropdown">'+d+' <span class="caret"></span></button>');c.push('<ul class="dropdown-menu">');jQuery.each(this.entries,function(){c.push('<li class="'+(this.active?"active":"")+'"><a href="#" id="'+this.id+'">'+this.label+"</a></li>")});c.push("</ul></span>")}this.search!=
null&&c.push(this.search);c.push("<br/><br/>")}else{c.push('<ul class="nav nav-tabs '+(churchcore_handyformat()?"nav-stacked":"")+'">');jQuery.each(this.entries,function(){c.push('<li class="'+(this.active?"active":"")+'"><a href="#" id="'+this.id+'">'+this.label+"</a></li>")});this.search!=null&&c.push('<li class="pull-right">'+this.search);c.push("</ul>")}return c.join("")};a.renderDiv=function(b,c){jQuery("#"+b).html(this.render(c))};
a.activate=function(b){$("ul.nav li.active").removeClass("active");$("ul.nav a[id="+b+"]").parent().addClass("active")};function form_showDialog(b,c,d,e,f){var g=$('<div id="cdb_dialog">'+c+"</div>").appendTo("#page");if(d>$(window).width())d=$(window).width();g.dialog({autoOpen:true,width:d,height:e,modal:true,title:b,buttons:f,close:function(){g.empty().remove()}});shortcut.add("esc",function(){g.dialog("close")});return g}
function form_showCancelDialog(b,c,d,e){if(d==null)d=350;if(e==null)e=400;return form_showDialog(b,c,d,e,{Abbruch:function(){$(this).dialog("close")}})}function form_showOkDialog(b,c,d,e){if(d==null)d=350;if(e==null)e=400;return form_showDialog(b,c,d,e,{Ok:function(){$(this).dialog("close")}})}function form_addEntryToSelectArray(b,c,d,e){var f={};f.id=c;f.bezeichnung=d;if(e!=null)f.sortkey=e;b[c]=f}
function form_implantDatePicker(b,c,d,e){if(typeof c=="string")c=c.toDateDe();if($("#"+b).html()==""){$("#"+b).datepicker({dateFormat:"dd.mm.yy",showButtonPanel:true,dayNamesMin:["So","Mo","Di","Mi","Do","Fr","Sa"],currentText:"Heute",firstDay:1,beforeShowDay:e,onSelect:function(f,g){d(f,b);$("#"+b).datepicker("destroy");$("#"+b).html("")}});$("#"+b).datepicker($.datepicker.regional.de);$("#"+b).datepicker("setDate",c)}else{$("#"+b).datepicker("destroy");$("#"+b).html("")}shortcut.add("esc",function(){$("#"+
b).datepicker("destroy");$("#"+b).html("")})}function form_renderHelpLink(b,c){return c==null||c==false?'<a href="http://intern.churchtools.de?q=help&doc='+b+'" target="_clean"><i class="icon-question-sign"></i></a>':'<a href="http://intern.churchtools.de?q=help&doc='+b+'" target="_clean"><i class="icon-question-sign icon-white"></i></a>'};
