var a;debug=false;dayNames=["Sonntag","Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag"];function l(b){return b}function churchcore_handyformat(){return $(window).width()<767}function churchcore_getBezeichnung(b,c){if(masterData[b]==null)return'<span class="error">Stammdaten '+b+"?</span>";if(masterData[b][c]==null)return'<span class="error">Id:'+c+"?</span>";return masterData[b][c].bezeichnung}
function churchcore_sortData(b,c,e,f,h){return f==null||f==true?churchcore_sortData_alpha(b,c,e,h):churchcore_sortData_numeric(b,c,e,h)}function churchcore_isObjectEmpty(b){if(b==null)return false;var c=true;$.each(b,function(e,f){return c=false});return c}function churchcore_countObjectElements(b){if(b==null)return 0;var c=0;$.each(b,function(e,f){c++});return c}function churchcore_getFirstElement(b){if(b==null)return null;var c=null;$.each(b,function(e,f){c=f;return false});return c}
function churchcore_sortData_alpha(b,c,e,f){function h(o,k){if(o==null||k==null)return 0;var p=o[c],m=k[c];if(o[c]==null)if(o[f!=null]&&k[f]!=null){p=o[f];m=k[f]}else return 1*g;else if(m==null)if(o[f!=null]&&k[f]!=null){p=o[f];m=k[f]}else return-1*g;if(typeof p=="string"&&typeof m=="string"){p=p.toLowerCase();p=p.replace(/\u00e4/g,"azz");p=p.replace(/\u00f6/g,"ozz");p=p.replace(/\u00fc/g,"uzz");p=p.replace(/\u00df/g,"szz");m=m.toLowerCase();m=m.replace(/\u00e4/g,"azz");m=m.replace(/\u00f6/g,"ozz");
m=m.replace(/\u00fc/g,"uzz");m=m.replace(/\u00df/g,"szz")}return p==m?0:p>m?1*g:-1*g}if(b==null)return null;var g=1;if(e)g=-1;var j=[],n=0;jQuery.each(b,function(o,k){j[n]=k;n+=1});j.sort(h);obj={};jQuery.each(j,function(o,k){if(k!=null)obj[o]=k});return obj}
function churchcore_sortData_numeric(b,c,e,f){function h(j,n){if(j==null||n==null)return 0;var o=j[c],k=n[c];if(j[c]==null)if(j[f!=null]&&n[f]!=null){o=j[f];k=n[f]}else return 1*g;else if(k==null)if(j[f!=null]&&n[f]!=null){o=j[f];k=n[f]}else return-1*g;return o*1>k*1?1*g:-1*g}if(b==null)return null;var g=1;if(e)g=-1;arr=[];jQuery.each(b,function(j,n){arr[j]=n});arr.sort(h);obj={};jQuery.each(arr,function(j,n){if(n!=null)obj[j]=n});return obj}
function churchcore_sortArray(b,c,e,f){return f==null||f==true?churchcore_sortArray_alpha(b,c,e):churchcore_sortArray_numeric(b,c,e)}function churchcore_sortArray_alpha(b,c,e){function f(g,j){if(g==null||j==null)return 0;else if(g[c]==null)return 1*h;else if(j[c]==null)return-1*h;return g[c].toLowerCase()>j[c].toLowerCase()?1*h:-1*h}var h=1;if(e)h=-1;return b.sort(f)}
function churchcore_sortArray_numeric(b,c,e){function f(g,j){if(g==null||j==null)return 0;else if(g[c]==null)return 1*h;else if(j[c]==null)return-1*h;return g[c]*1>j[c]*1?1*h:-1*h}var h=1;if(e)h=-1;return b.sort(f)}
churchcore_sortMasterData=function(b){function c(e,f){if(e==null||f==null)return 0;if(e.sortkey!=null||f.sortkey!=null){if(e.sortkey==null)return 1;if(f.sortkey==null)return-1;return e.sortkey*1>f.sortkey*1?1:-1}else{if(e.id!=null&&e.id==0)return-1;if(f.id!=null&&f.id==0)return 1;if(e.bezeichnung==null)return 1;if(f.bezeichnung==null)return-1;return e.bezeichnung.toLowerCase()>f.bezeichnung.toLowerCase()?1:-1}}arr=[];jQuery.each(b,function(e,f){arr.push(f)});arr.sort(c);obj={};jQuery.each(arr,function(e,
f){if(f!=null)obj[e]=f});return obj};function churchcore_sendEmail(b,c,e,f){jQuery.getJSON("index.php?q="+b+"/ajax",{func:"send_email",subject:e,body:f,to:c},function(h){})}function churchcore_inObject(b,c){if(b==null||c==null)return false;ret=false;jQuery.each(c,function(e,f){if(f==b)ret=true});return ret}function churchcore_inArray(b,c){if(b==null||c==null)return false;ret=false;jQuery.each(c,function(e,f){if(f==b)ret=true});return ret}
function isNumber(b){return!isNaN(parseFloat(b))&&isFinite(b)}String.prototype.endsWith=function(b){return this.indexOf(b,this.length-b.length)!==-1};String.prototype.trim=function(b){var c=this.replace(/^(\s|\u00A0)+|(\s|\u00A0)+$/g,"");if(b==null)b=c.length;return c.length>b?c.substr(0,b-2)+"..":c};
String.prototype.toDateEn=function(b){if(this==null)return null;var c=this.split(" "),e=c[0].split("-");if(b!=null&&!b||c[1]==null)return new Date(e[0],e[1]-1,e[2]);else{b=c[1].split(":");return new Date(e[0],e[1]-1,e[2],b[0],b[1])}};
String.prototype.toDateDe=function(b){if(this==null)return null;if(b==null)b=false;var c=this,e=c.indexOf("."),f=0;if(e>0)f=c.substr(0,e);else{e=new Date;c=c.toLowerCase();if(c=="0")return e;else if(c.indexOf("t")>0)e.addDays(c.substr(0,c.indexOf("t"))*-1);else if(c.indexOf("w")>0)e.addDays(c.substr(0,c.indexOf("w"))*-7);else if(c.indexOf("m")>0)e.setMonth(e.getMonth()-c.substr(0,c.indexOf("m"))*1);else e=null;return e}c=c.substr(e+1,99);e=c.indexOf(".");if(e>0)month=c.substr(0,e);else return null;
c=c.substr(e+1,99);year=c.indexOf(" ")>0?c.substr(0,c.indexOf(" ")):c;if(!b)return new Date(year,month-1,f);e=c.indexOf(" ");if(e<=0)return new Date(year,month-1,f,0,0);c=c.substring(e+1,99);e=c.indexOf(":");b=c.substr(0,e);c=c.substr(e+1,99);e=c.indexOf(":");minute=e>0?c.substr(0,e):c.substr(0,99);return new Date(year,month-1,f,b,minute)};function churchcore_isAllDayDate(b,c){if(b.getMinutes()==0&&b.getHours()==0&&c!=null&&c.getMinutes()==0&&c.getHours()==0)return true;return false}
String.prototype.isGermanDateFormat=function(){return this.search(/([1-9]|0[1-9]|[12][0-9]|3[01])\.([1-9]|0[1-9]|1[012])\.(19|20)\d\d/)!=-1};
Date.prototype.toStringDe=function(b){if(this==null)return null;if(this==0)return"Kein Datum";if(b!=null&&b==true){b=" "+this.getHours()+":";if(this.getMinutes()<10)b=b+"0"+this.getMinutes();else b+=this.getMinutes()}else b="";day=this.getDate();if(day<10)day="0"+day;month=this.getMonth()+1;if(month<10)month="0"+month;return day+"."+month+"."+this.getFullYear()+b};
Date.prototype.toStringDeTime=function(){if(this==null)return null;if(this==0)return"Kein Datum";withTime=this.getHours()+":";if(this.getMinutes()<10)withTime=withTime+"0"+this.getMinutes();else withTime+=this.getMinutes();return withTime};function churchcore_getTimeDiff(b){return(new Date).getTime()-b.getTime()}a=Date.prototype;
a.toStringEn=function(b){if(this==null)return null;d=this;if(d==0)return"Kein Datum";day=d.getDate();if(day<10)day="0"+day;month=d.getMonth()+1;if(month<10)month="0"+month;return b?d.getFullYear()+"-"+month+"-"+day+" "+d.getHours()+":"+d.getMinutes():d.getFullYear()+"-"+month+"-"+day};a.addDays=function(b){this.setDate(this.getDate()+b)};
a.getKW=function(){D0=new Date(this.getFullYear(),0,4);if(D0.getDay()>0)for(;D0.getDay()>0;)D0.setDate(D0.getDate()+1);D0.setDate(D0.getDate()-7);diff=(this-D0)/6048E5;return diff=diff<=0?"53 (0)":Math.ceil(diff)};a.getAgeInYears=function(){var b=new Date;b=new Date(b.getFullYear(),b.getMonth(),b.getDate());var c=new Date(this.getTime());c.setYear(b.getFullYear());return c>b?b.getFullYear()-this.getFullYear()-1:b.getFullYear()-this.getFullYear()};
a.getDayInText=function(){return(new Array("Sonntag","Montag","Dienstag","Mittwoch","Donnerstag","Freitag","Samstag"))[this.getDay()]};a.sameDay=function(b){if(b==null)return false;return this.getFullYear()==b.getFullYear()&&this.getMonth()==b.getMonth()&&this.getDate()==b.getDate()};a.monthDiff=function(b){var c;c=(b.getFullYear()-this.getFullYear())*12;c-=this.getMonth();c+=b.getMonth();return c};a.dayDiff=function(b){return(b-this)/864E5};
a.withoutTime=function(){var b=new Date(this);b.setHours(0);b.setMinutes(0);b.setSeconds(0);return b};function churchcore_isFullDay(b,c){if(b.getHours()==0&&b.getMinutes()==0&&b.getSeconds()==0&&(c==null||c.getHours()==0&&c.getMinutes()==0&&c.getSeconds()==0))return true;return false}
function churchcore_datesInConflict(b,c,e,f){var h=c,g=f;if(churchcore_isFullDay(b,c)){h.addDays(1);h=new Date(h.getTime()-1)}if(churchcore_isFullDay(e,f)){g.addDays(1);g=new Date(h.getTime()-1)}if(g>b&&g<h||e>b&&e<h||e<=b&&g>=h||e>=b&&g<=h){debug&&console.log("DateConflict! Datum1:"+b.toStringDe(true)+"=>"+h.toStringDe(true)+"   -    Datum2:"+e.toStringDe(true)+" "+g.toStringDe(true));return true}return false}
function print_r(b,c){var e="";c||(c=0);if(c>10)return"";for(var f="",h=0;h<c+1;h++)f+="    ";if(typeof b=="object")for(var g in b){h=b[g];if(typeof h=="object"){e+=f+"'"+g+"' ...\n";e+=print_r(h,c+1)}else e+=f+"'"+g+"' => \""+h+'"\n'}else e="===>"+b+"<===("+typeof b+")";return e}function cc_copyArray(b){for(i in b)this[i]=typeof b[i]=="source"?new cloneObject(b[i]):b[i]}
jQuery.extend(jQuery.ui.dialog.prototype,{addbutton:function(b,c){var e=this.element.dialog("option","buttons");e[b]=c;this.element.dialog("option","buttons",e)}});
jQuery.fn.extend({insertAtCaret:function(b){var c;c=typeof this[0].name!="undefined"?this[0]:this;if(jQuery.browser.msie){c.focus();sel=document.selection.createRange();sel.text=b;c.focus()}else if(jQuery.browser.mozilla||jQuery.browser.webkit){var e=c.selectionStart,f=c.selectionEnd,h=c.scrollTop;c.value=c.value.substring(0,e)+b+c.value.substring(f,c.value.length);c.focus();c.selectionStart=e+b.length;c.selectionEnd=e+b.length;c.scrollTop=h}else{c.value+=b;c.focus()}}});
String.prototype.str_replace=function(b,c){if(this==null)return null;var e,f=this;for(e=f.indexOf(b);e>0;){f=f.substr(0,e)+c+f.substr(e+1,999);e=f.indexOf(b)}return f};Number.prototype.maskWithZero=function(b){for(var c=this+"";c.length<b;)c="0"+c;return c};Storage.prototype.setObject=function(b,c){if(typeof localStorage=="object")try{this.setItem(b,JSON.stringify(c))}catch(e){console.log("Fehler bei setObject von "+b+": "+e)}};
Storage.prototype.getObject=function(b){try{return typeof localStorage=="object"?JSON.parse(this.getItem(b)):null}catch(c){console.log("Fehler beim einladen von "+b+"!");return null}};function churchcore_openPopupWindow(b){window.open(b,"ctPopUp","toolbar=no, menubar=no, scrollbars=no, resizable=no, location=no, directories=no, status=no,height=550,width=550")}function churchcore_openNewWindow(b){window.open(b,"ctNew","")}
function churchcore_getAllDatesWithRepeats(b){var c=[],e=null;if(b.enddate!=null)e=b.enddate.getTime()-b.startdate.getTime();var f=new Date(b.repeat_until);f.addDays(1);var h=999;additions=b.additions!=null?$.extend({},b.additions):{};additions[0]={};additions[0].add_date=(new Date(b.startdate)).toStringEn();additions[0].with_repeat_yn=1;var g=null;$.each(additions,function(j,n){g=n.add_date.toDateEn();g.setHours(b.startdate.getHours());g.setMinutes(b.startdate.getMinutes());do{var o=false;b.exceptions!=
null&&$.each(b.exceptions,function(p,m){if(m!=null&&churchcore_datesInConflict(m.except_date_start.toDateEn(),m.except_date_end.toDateEn(),g,e!=null?new Date(g.getTime()+e):g)){o=true;return false}});o||(e!=null?c.push({startdate:new Date(g),enddate:new Date(g.getTime()+e)}):c.push({startdate:new Date(g),enddate:null}));if(b.repeat_id==1||b.repeat_id==7)g.addDays(b.repeat_id*b.repeat_frequence);else if(b.repeat_id==31){j=0;do{var k=new Date(g);k.setMonth(g.getMonth()+j+1*b.repeat_frequence);if(k.getDate()==
g.getDate()){g.setMonth(g.getMonth()+j+1*b.repeat_frequence);j=999}j+=1}while(j<999)}else if(b.repeat_id==32)if(b.repeat_option_id==6){g.setMonth(g.getMonth()+1+1*b.repeat_frequence,1);for(g.addDays(-1);g.getDay()!=n.add_date.toDateEn().getDay();)g.addDays(-1)}else{j=0;for(g.setMonth(g.getMonth()+1*b.repeat_frequence,0);j<b.repeat_option_id;){k=g.getMonth();g.addDays(1);if(g.getMonth()!=k)j=0;if(g.getDay()==n.add_date.toDateEn().getDay())j+=1}}else b.repeat_id==365&&g.setFullYear(g.getFullYear()+
1*b.repeat_frequence);h-=1}while(g<f&&h>0&&n.with_repeat_yn==1&&b.repeat_id>0&&b.repeat_frequence>0)});h==0&&alert("Maximale Wiederholung erreicht! ["+b.id+"]");return c}$(document).ready(function(){window.setTimeout(function(){$("div.hide_automatically").hide("slow")},5E3)});
